### ISSUE TITLE
[RFC] There should be a test suite

### ISSUE THREAD

**Issue by ghost** [libass/libass#108]
This was often discussed and everyone agrees it would be good. (I thought we had a ticket for it, but apparently not.)

There are some fundamental issues, in particular: how to verify the rasterized results? For now, we could probably get away with a naive image difference algorithm. (Sum of squared values of subtracted color values?) We probably also need to force a fixed font, because I think as long as we query system fonts, we won't be able to get truly reproducible results.

Here are some ideas how to organize and run tests. Every numbered option is a way how we could do it, pick one.
1. Every test is an .ass file, and we add special headers to it, such as:
   - list of timestamps to render
   - resolution to render
   - filename of image to compare with (or if possible: a textual hash or whatever that is to check for success or failure; is that even possible?)
   - allowable deviation before a failure is reported
   
   The test program loads the ASS file using libass, but also parses these extra headers by parsing some of the text itself. It then runs all the requested tests, prints out success, and sets the process exit value according to the success. This test program can be called by a script, which calls it for every .ass file in the test directory.
2. Similar to 1., but store the test metadata in a separate text file. Then a single script could for example be used for multiple tests. We also could possibly test mkv files too (with 1., it would be too hard to add custom headers to the embedded script to drive the test runner).
3. Pass all test parameters as command line options to the test program directly. Then the whole test suite would be a huge script calling the test program over and over (with 1. and 2., the script would merely loop over all files automatically).
4. In a variation, the test program could output raw pixel data to stdout, and leave checking the result to an external program.

Also, if we want to test mkv files directly (for the sake of embedded fonts), we'd need a small mkv demuxer. Probably easier not to use mkv files, but instead load fonts from a directory or so.

**Comment by TheOneric** [comment]
We now have [libass/libass-tests](https://github.com/libass/libass-tests).
