### ISSUE TITLE
Collision repositioning seems to be accounting for blur

### ISSUE THREAD

**Issue by rcombs** [libass/libass#112]
![](http://puu.sh/9Q6gC/fc2b6fa4aa.png)

```
Dialogue: 2,0:22:31.41,0:22:36.56,flaped1-1rb,,0,0,0,,{\blur3\fad(150,150)}{\3c&HC1D656&}tenohira ni itoshii kibou
Dialogue: 3,0:22:31.41,0:22:36.56,flaped1-1tb,,0,0,77,,{\blur3\fad(150,150)}{\3c&HC1D656&}The warmth of the hope in the palm of your hand
Dialogue: 4,0:22:31.41,0:22:36.56,flaped1-1r,,0,0,0,,{\fad(150,150)}{\c&HC1D656&}tenohira ni itoshii kibou
Dialogue: 4,0:22:31.41,0:22:36.56,flaped1-1t,,0,0,0,,{\fad(150,150)}{\c&HC1D656&}The warmth of the hope in the palm of your hand
Dialogue: 9,0:22:33.49,0:22:38.82,Default,,0,0,0,,{\bord5\blur2}In fact, once I close this deal, \NI'm going to marry her.{Matched to E1}
```

**Comment by astiob** [comment]
Is the full sample available/can this be retested?

VSFilter accounts for _border_ in collision repositioning, and this discrepancy has now been fixed in libass. I don’t think VSFilter accounts for _blur,_ but I may be wrong, so I’m hesitant to close this issue.

**Comment by rcombs** [comment]
Looks to still be wrong:
![screenshot-1353 018000](https://user-images.githubusercontent.com/819638/87001333-d1e87780-c17c-11ea-85ba-57fd52b37fa3.png)

**Comment by astiob** [comment]
I can’t seem to reproduce the supposedly expected behaviour in either xy-VSFilter or MPC-HC ISR.

**Comment by rcombs** [comment]
I can't repro this anymore either, so closing this out.

Attaching script and font for future reference: [flag-13.ass.txt](https://github.com/libass/libass/files/8127524/flag-13.ass.txt) / [PASSINGNOTES.TTF.zip](https://github.com/libass/libass/files/8127527/PASSINGNOTES.TTF.zip)
