### ISSUE TITLE
Error "Failed to process glyph outline!"

### ISSUE THREAD

**Issue by Akemi** [libass/libass#113]
the following sample broke with the new rasterizer i believe. i get following error: "Failed to process glyph outline!". see the 'E' in the screenshots below the sample.

https://dl.dropboxusercontent.com/u/68772824/outline.mkv

how it should look like:
![out](https://cloud.githubusercontent.com/assets/680386/3449636/1cb654ec-0169-11e4-8830-5e17d25ef5f7.jpeg)
how it looks like now.
![broken](https://cloud.githubusercontent.com/assets/680386/3449635/1cb3b00c-0169-11e4-9cbe-148630cb2833.jpeg)

**Comment by MrSmile** [comment]
Internal stroker fixes that issue.
