### ISSUE TITLE
Hardcode subtitles not working

### ISSUE THREAD

**Issue by hiteshsondhi88** [libass/libass#127]
Hey

I've compiled FFmpeg with libass for Android (static binary). I've used this configure script

./configure \
  --disable-dependency-tracking \
  --with-pic \
  --host=arm-linux-androideabi \
  --disable-enca \
  --enable-fontconfig \
  --disable-harfbuzz \
  --enable-static \
  --disable-shared 

Now, I am able to embed soft subs using ffmpeg (both srt and ass). But I am not able to hardcode these subs to file. Can you please guide me here ? Is the issue related to FFmpeg or libass ? Do I need to enable one of the libraries I've disabled with libass (enca, harfbuzz).

P.S - I am using my custom pkg-config to provide fontconfig, fribidi, freetype2 (libs and cflags) which I've compiled specifically for Android.

**Comment by tomorrowbetter** [comment]
I use a software called iDealshare VideoGo to hardcode subtitles to video files like MP4, AVI, MKV.

Now i like to share this step by step guide here http://www.idealshare.net/hardcode-subtitles.html

Hope it also helps for you more or less

**Comment by grownbetterwe** [comment]
You may also try this method to hardcode subtitles at http://www.idealshare.net/hardcode-subtitles.html

**Comment by workpanda** [comment]
Hi, hiteshsondhi
I also can not know why don't work hardcode subtitles on android.
Please can you tell me how to custom fontconfig configuration?
Thanks.

**Comment by s9iper1** [comment]
@hiteshsondhi88 can you share your custom font config ?

**Comment by hiteshsondhi88** [comment]
@s9iper1 @workpanda you can check readme of my ffmpeg project here https://github.com/writingminds/ffmpeg-android

**Comment by s9iper1** [comment]
@hiteshsondhi88  i am using this command in linux to burn subtitles on a video but why can't i not use it in android.
fmpeg -i /home/s9iper1/a.mp4 -vf "subtitles=/home/s9iper1/titles.srt:force_style='Fontsize=24,PrimaryColour=&H0000ff&'" -c:a copy /home/s9iper1/out.mp4
