### ISSUE TITLE
"Failed to process glyph outline!"

### ISSUE THREAD

**Issue by rcombs** [libass/libass#133]
When using the internal rasterizer with this script: http://puu.sh/bnH89/0d28d4b54a.ass
The error "Failed to process glyph outline!" is printed repeatedly, and a drawing isn't displayed.

**Comment by Adithya-Sekhar** [comment]
Check if the font name is specified correctly, happened to me just now!

**Comment by rcombs** [comment]
Assuming this was fixed by either stroker or rasterizer changes since.
