### ISSUE TITLE
Failed Arabic fonts rendering

### ISSUE THREAD

**Issue by Samer-** [libass/libass#134]
Arabic fonts aren't shown well with libass compared to vsfilter or other applications. The problem is mostly with diacritics but sometimes with the letters themselves or with spaces.

Pictures comparing libass with Wordpad under Windows: https://www.dropbox.com/s/acgxpebqj1g14gv/ArabicBugsV2.zip?dl=2

**Comment by TheOneric** [comment]
iiuc this issue only manifested when libass was built without Harfbuzz. With #399 merged, Harfbuzz is now required in all libass builds, so this shouldn't happen anymore.

Feel free to reopen if the issue persists.
