### ISSUE TITLE
Invalid inline drawing command causes incorrect render.

### ISSUE THREAD

**Issue by torque** [libass/libass#144]
This happens for me with libass 26ccc19 (built with freetype 2.5.3, fribidi 0.19.6 and harfbuzz-ng 0.9.35) on OS X. It does not happen with the libass shipped with Aegisub 3.2.1 on Windows, which, as I recall, is built without harfbuzz.

For example, given the line:

```
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,Mysterious{\p1}z {\p0} Disappearance
```

[Full script](https://gist.github.com/torque/8e0d45454133cd13ea8c).

libass on OS X:
![libass-osx](https://cloud.githubusercontent.com/assets/949138/4944333/93bae9ca-65fc-11e4-851d-89e7431b4bba.png)

xy-vsfilter/libass from Aegisub 3.2.1 on Windows:
![xy-vsf](https://cloud.githubusercontent.com/assets/949138/4944337/9bf25ce0-65fc-11e4-9e0a-24d508926a64.png)

**Comment by astiob** [comment]
This appears to have been fixed in b63d8931845af256523d1142abea5caf2f65685d.
