### ISSUE TITLE
Outlines are different with VSFilter

### ISSUE THREAD

**Issue by pingplug** [libass/libass#154]
PlayResX and PlayResY are 848 and 480, rendered on 1280 x 720 video

Style: Default,Arial,31,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,30,30,15,1
Dialogue: 0,0:00:00.00,1:00:00.00,Default,NTP,0000,0000,0000,,This is a test
Dialogue: 0,0:00:00.00,1:00:00.00,Default,NTP,0000,0000,0000,,This is a test

this is for libass
![libass](https://cloud.githubusercontent.com/assets/6712475/5561439/7a7f86de-8e13-11e4-9653-b780a6aecf94.png)
this is for VSFilter
![vsfilter](https://cloud.githubusercontent.com/assets/6712475/5561440/7e7de8ac-8e13-11e4-9457-45e631598dd3.png)
## 2015-01-03 update
1. the outlines are different(3px in VSFilter, 4.5px in libass)
   I think this is caused by the default ScaledBorderAndShow(1 in libass, 0 in VSFilter)
2. VSFilter add borders(top/bottom, = max border_y of the top/bottom line) between texts
   makes the collision text 6px(2 \* 3px border) higher than libass

**Comment by CarVac** [comment]
I believe the issue may be that in libass, the border widths aren't scaling with the rendering resolution.

Playing back 480p video stretched to fit my 4k screen, the borders are way too tiny: they stay the same size even as the subs themselves change size.

**Comment by grigorig** [comment]
It's actually the opposite. libass scales the borders with resolution by default, VSFilter does not.

**Comment by astiob** [comment]
Let’s split this into #287 for `ScaledBorderAndShadow` and #304 for the space between events during collision detection.
