### ISSUE TITLE
font not work

### ISSUE THREAD

**Issue by realfinder** [libass/libass#156]
there are some fonts not work with libass

like:-

http://www.mediafire.com/download/axaxxa8ewhbwj0s/SKR+Head1.zip

http://www.mediafire.com/download/942swxekejb25er/Osama+Subtitle+Font.zip

**Comment by grigorig** [comment]
Hi, can you please describe what "does not work" means?

**Comment by realfinder** [comment]
hi grigorig, When you use the mentioned fonts will appear in another font (the default program font)

vs filter
![vs filter](https://cloud.githubusercontent.com/assets/2512153/7812556/e8fc3e0e-03bb-11e5-95ec-fe7cbdb94811.png)

libass
![libass](https://cloud.githubusercontent.com/assets/2512153/7812561/f6933e46-03bb-11e5-9df4-57aeb4583c42.png)

sub + font in it
http://www.mediafire.com/download/0h3s26z60pw6uas/test.ass

**Comment by grigorig** [comment]
Hm... the font uses the private use area (U+F200 - U+F30F) for storing Arabic presentation forms. This is a really old font, so it's probably some legacy thing. I need to investigate how to properly handle this.

**Comment by grigorig** [comment]
So, I did research a bit: the font in question uses an old and proprietary encoding that isn't really documented anywhere. It was only used by a handful of fonts, as far as I can tell. We would need special handling for this in libass and a special Arabic fallback shaper which possibly could be added to HarfBuzz. It would be a tremendous amount of work that involves some reverse engineering of the used encoding.

So, WONTFIX, for now. Maybe if HarfBuzz adds support for this encoding we can look into it. But that is very unlikely according to feedback from @behdad.

**Comment by behdad** [comment]
I'm willing to add it to HarfBuzz if Windows handles it by default.

**Comment by khaledhosny** [comment]
There are quite a few Arabic fonts circulating around the web that were built this way (mostly abandoned fonts but people are still using them because they work on Windows). I once wrote a [script](http://svn.arabeyes.org/viewvc/art/khotot/tools/legacy2opentype.py?view=markup) to remap those fonts, but I couldn’t find any sort of documentation so it was based on some quick reverse engineering, it works for most of the fonts I tried it on but not all of them. I’m not sure about the importance of supporting such fonts, but I think some sort of documentation would be needed first.

**Comment by khaledhosny** [comment]
Hmm, this looks like a different issue. The font has a symbol cmap subtable (Platform ID 3, Encoding ID 0) which FreeType seems to ignore and libass is using FreeType font functions. If I use HarfBuzz’s built in font functions (e.g. by passing `--font-funcs=ot` to `hb-view`) the font works just fine as the font functions fall back to this encoding if none else is available.

**Comment by grigorig** [comment]
libass doesn't ignore symbol encodings. We use our own code to choose cmaps and that includes some handling for symbol fonts (which by convention store characters mapped to the Unicode PUA at U+F000-U+F0FF). However, that doesn't help in this case. I think there are two different problems still. The fonts linked in the first post have different issues.

The font "SKR Head 1" uses the custom encoding inside the private use area I earlier talked about. A large number of precomposed forms is stored starting at U+F200.

The font "Osama Subtitle Font" uses a different encoding that only stores some precomposed forms at U+0000 to U+00FF. It uses the Windows symbol encoding and that is not consistent with standard symbol fonts, as described above. That is why the font won't work at all. It still doesn't matter: even if we 'fix' that issue with the U+F200 offset, the encoding needs to be handled by glyph fallback and shaping somehow.

I'm really tempted to completely ignore all these strange legacy encodings. They desperately need to die.

**Comment by khaledhosny** [comment]
My last comment was about “Osama Subtitle Font”. It uses the symbol encoding subtable, but it still has the correct code points for Arabic. Here are few entries rom `ttx` dump:
```
      <map code="0x627" name="A175"/><!-- ARABIC LETTER ALEF -->
      <map code="0x628" name="A178"/><!-- ARABIC LETTER BEH -->
      <map code="0x629" name="A179"/><!-- ARABIC LETTER TEH MARBUTA -->
      <map code="0x62a" name="A181"/><!-- ARABIC LETTER TEH -->
      <map code="0x62b" name="A183"/><!-- ARABIC LETTER THEH -->
      <map code="0x62c" name="A185"/><!-- ARABIC LETTER JEEM -->
      <map code="0x62d" name="A187"/><!-- ARABIC LETTER HAH -->
      <map code="0x62e" name="A189"/><!-- ARABIC LETTER KHAH -->
      <map code="0x62f" name="A190"/><!-- ARABIC LETTER DAL -->
      <map code="0x630" name="A191"/><!-- ARABIC LETTER THAL -->
      <map code="0x631" name="A192"/><!-- ARABIC LETTER REH -->
      <map code="0x632" name="A193"/><!-- ARABIC LETTER ZAIN -->
      <map code="0x633" name="A195"/><!-- ARABIC LETTER SEEN -->
      <map code="0x634" name="A197"/><!-- ARABIC LETTER SHEEN -->
```
The fact that it has some private use area or presentation forms characters is irrelevant as both are accessed through `GSUB` features.

“SKR Head1” is indeed one of the fonts using the legacy encoding that I referred to in my first comment.

**Comment by khaledhosny** [comment]
Here is the output of `hb-view "Osama Subtitle Font.ttf" "عربي" --font-funcs=ot`:
![o](https://cloud.githubusercontent.com/assets/93914/8639382/948d6b9e-28d8-11e5-9e44-ea8200c74117.png)

**Comment by grigorig** [comment]
Oh, I missed that this font actually has a GSUB table, sorry. libass right now implements glyphs substitution before shaping, which fails with fonts that don't have the characters in the cmap. I think this should be considered a font bug, but maybe we should be able to handle these scenarios.
