### ISSUE TITLE
libass rendering Numbers different from vsfilter

### ISSUE THREAD

**Issue by realfinder** [libass/libass#166]
vsfilter
![vs](https://cloud.githubusercontent.com/assets/2512153/6648918/3136f72c-c9f1-11e4-9b18-26a4ba609c13.png)

libass
![libass](https://cloud.githubusercontent.com/assets/2512153/6648919/395d53ba-c9f1-11e4-8497-d345e1b41e8b.png)

font is arial 
text is
دار 89

**Comment by wm4** [comment]
So ASCII ``89`` renders in arabic as ``۸۹`` when it's paired up with arabic text? Can you explain the mechanism behind this? (I.e. how it's supposed to work.) I would think that ASCII 89 stays ASCII 89.

**Comment by astiob** [comment]
Yeah, is that actually “89” or “٨٩”? If it’s “89” (the plain ASCII characters), then why does it show up as ٨٩ in Aegisub and VSFilter?

**Comment by realfinder** [comment]
it should be ٨٩ in arabic text, in vsfilter if the number come in beginning of text it will be 89 like libass, and that wrong too, but if I use RLE (Unicode control characters) in the beginning then write the number it will be ٨٩ and that what it should, but that not work in libass

I use ٨٩\89 for example only, the problem appear in any number

**Comment by wm4** [comment]
I can't find anything on Linux that handles text like this. I tried: gtk2, gtk3, firefox, chromium, kde (qt4 I think), qtcreator (qt5 probably), kate.

**Comment by realfinder** [comment]
let see @behdad opinion

**Comment by realfinder** [comment]
and @khaledhosny too

**Comment by behdad** [comment]
It's Windows that sometimes replaces ASCII digits with their local counterparts.  That's discouraged practice and can be turned off in Windows localization settings.

**Comment by realfinder** [comment]
I think most people use the default setting that I use above

and how I can write ٨٩ in libass then? in the keyboard even with arabic write the Numbers like 89

**Comment by behdad** [comment]
I don't know what to use to enter those with Windows's default Arabic keyboard layout.

If libass wants to do the same mapping (which I don't support), APIs listed here might help:

https://msdn.microsoft.com/en-us/goglobal/bb688127.aspx

**Comment by wm4** [comment]
So this seems rather unusual, depends on the system locale, is discouraged by MS (apparently), and hard to implement. So, I'm tempted to ignore this and close it as WONTFIX.

Those who insist on "native" numerals can still use the actual unicode codepoints; these should behave the same in vsfilter and libass.

**Comment by khaledhosny** [comment]
I agree that this should be closed as WONTFIX; it is bad practice that should be discouraged. Both Linux and Mac OS X have keyboard layouts with Arabic-Indic digits, and I think one can find something similar for Windows.

**Comment by realfinder** [comment]
all old subtitle files written like this, and the new one on windows too, no one will buy new keyboard for this if the problem in it in first place

**Comment by rcombs** [comment]
Agreed, this is a locale-setting-specific bit of Windows nonsense that libass has no business emulating. I might think otherwise if this was an always-on quirk of GDI, but no, it's an option.

**Comment by realfinder** [comment]
grigorig was write code that autodetect direction, I think it can be used here, or something like it but with autodetect Language

I don't know how libass work, even I don't know how to compile it, so I not sure

**Comment by grigorig** [comment]
I think we have a consensus here. It's an obscure feature, it is discouraged and it is an optional locale-specific even on Windows. WONTFIX.
