### ISSUE TITLE
Crash while using AVX2 on Windows 7 without Service Pack

### ISSUE THREAD

**Issue by zaps166** [libass/libass#169]
Windows 7 without Service Pack doesn't support AVX/AVX2, so library should check OS version :) Currently there is a crash - SIGILL.

**Comment by rcombs** [comment]
Do we care? (I personally don't; upgrade your OS.)

**Comment by wm4** [comment]
Isn't there a mechanism to determine whether the OS enabled a certain instruction set? We should respect this.

**Comment by rossy** [comment]
I think that's what the ``xgetbv`` instruction in FFmpeg is for, but I don't have a Windows 7 SP0 machine to test on.

https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/x86/cpu.c#L129

**Comment by rcombs** [comment]
Now that's actually reasonable. Try this patch? https://gist.github.com/0d82ba7cf5110e2fce74

**Comment by rcombs** [comment]
Can anyone confirm if that patch works as expected on the relevant Win32 versions?

**Comment by grigorig** [comment]
So there isn't anyone willing to test it, apparently. So just push it then? In the worst case, it won't change the status quo, but the code is simple enough and it should work.

**Comment by zaps166** [comment]
I've tried to test it on Qemu+AVX2, but Windows 7 SP0 doesn't want to start (BSOD, bad Qemu version? Does qemu emulate AVX2 correctly?). I don't have real hardware with AVX2 (only AVX). I can test it using someones computer, but I don't know when. I've found this bug using remote desktop + gdb.

**Comment by zaps166** [comment]
I compiled it a few months ago (I assume it was compiled OK), but I tested it last week and it works.

**Comment by grigorig** [comment]
rcombs, can you commit this please?

**Comment by rcombs** [comment]
fixed in dc78d6a0ce5a95a112b96d3b029172bb64d83252
