### ISSUE TITLE
Render ASS subtitle to video resolution and not to desktop res by default

### ISSUE THREAD

**Issue by Varshnyar** [libass/libass#172]
I think this is very important because styled subtitles have very ellaborate signs that looks good at video resolution, but when a HD video is in fullscreen mode on a FullHD monitor, the subtitles looks anormally sharp, as if they were not part of the video. And this problem is aggravated when the video is 480p.

**Comment by rcombs** [comment]
That's the player's call, not the renderer's, and the consensus is that nobody wants 480p dialogue on a 1800p monitor. Feel free to open an issue for providing an API to attempt to render TS at video resolution (which will be an ASSv5 feature, but could in theory be attempted in ASSv4++ using heuristics).

**Comment by astiob** [comment]
@Varshnyar I’m with you, but noöne else seems to be. If you’re using MPlayer or mplayer2, add `-vf-pre ass` to your command line. If you’re using mpv, add `--vf-pre=sub`. If you’re using MPlayer OSX Extended, alternatively you can check the ‘Render subtitles before all other filters’ checkbox on the Text tab. For other players, I don’t know, sorry.

And if you’re a fansubber, add some blur to your signs to ensure they will look good even when rendered at high resolutions. And if you’re not, ~~pester~~ nicely ask fansubbers whose work you watch to do that.

**Comment by wm4** [comment]
>If you’re using mpv, add --vf-pre=sub to your command line.

This is pretty bad and pretty slow. mpv could have a switch to do this directly (at least with vo_opengl), though that would require someone to care.

**Comment by wm4** [comment]
mpv now has a more efficient way to do this, and it also does this in RGB (avoids chroma-subsampling uglinesson text). See the mpv issue linked above.
