### ISSUE TITLE
New change detection has more false positives

### ISSUE THREAD

**Issue by Andrea3000** [libass/libass#173]
After the new image change detection algorithm introduced in commit dc0a14e61a1c454d593db5a91de0819921a2ddc9, the "ass_detect_change" function return 2 for certain subtitles, even if the content is static.

It's fine with most of the subtitles and when it fails it doesn't happen an all lines (some are fine).
I've never encountered this issue before the aforementioned commit.

**Sample file:** https://dl.dropboxusercontent.com/u/11879013/haibara.m4.kioku.arb.ass

**My system:**
- Mac OSX 10.8
- Latest libass from git
- freetype2 2.5.5
- fribidi 0.19.6
- harfbuzz 0.9.40

I use libass as a library in an app that I'm developing.

**From the sample file I've linked, the issue is visible between the following dialogues (included):**
- Dialogue: 0,0:00:17.22,0:00:18.64,Default,,0000,0000,0000,,ماللذي تقولينه
- …
- Dialogue: 0,0:00:32.17,0:00:38.82,Default,,0000,0000,0000,,لو نسيت كل ذلك, و بقيت فقط ”هايبرا آي“ طالبة الابتدائية, ما احلى ذلك

Let me know if you need other info
Thank you

**Comment by wm4** [comment]
Well yes, basically we gave up on doing changed detection if clipping is involved. But I'm not sure why this would happen in your case - maybe something is actually clipped, possibly just transparent parts of an image.

**Comment by TheOneric** [comment]
The change detection won't be 100% accurate, however there must never be false negatives *(claiming no change if there was one)* as this would lead to necessary redraws being omitted. Of course having fewer false positives *(claiming change if there was none)* is generally a good thing to avoid unneeded redraws, but it isn't always worth the complexity or possible. Perhaps we should make the reliability more clear in our documentation?
```diff
 * \param detect_change compare to the previous call and set to 1
- * if positions changed, or set to 2 if content changed.
+ * if positions might have changed, or set to 2 if content might have changed.
```


In the specific case, *maayybe* the clipping of glyphs will be moved or no longer be done (instead clipping the whole event); our clipping is curretnly not ideal clipping some things too early (before processing collisions: #121) and too late from a performance standpoint in other cases (#454). But you shouldn't rely on that.
