### ISSUE TITLE
Subtitles display outside of video frame

### ISSUE THREAD

**Issue by wm4** [libass/libass#177]
libass should clip all drawings against the margins which represent the area of the actual video frame. Currently, it seems to clip them only against the display, at least in some cases.

From the original report:

mpv: [1](http://puu.sh/hNXqx/7a56148977.jpg) [2](http://puu.sh/hNXqH/7f00227958.jpg)
expected: [1](http://puu.sh/hNXrI/51807ac2f7.png) [2](http://puu.sh/hNXsa/97a1a1d669.png)
[test.mkv](http://puu.sh/hNXBL/b04779258e.mkv) - just 5 seconds of blue at 720x200
[test.ass](http://puu.sh/hNXDC/d6192a6a90.ass) - ` {\an5\frz45\p1\clip(-80,-100,800,300)}m 0 0 l 600 0 600 600 0 600`

This was reported by a user: https://github.com/mpv-player/mpv/issues/1934

**Comment by astiob** [comment]
The original bug report has this tidbit:

> Without a \clip tag on the line it displays as expected but if the \clip goes outside of the video's frame then this happens
