### ISSUE TITLE
Subtitle problem

### ISSUE THREAD

**Issue by Lalaiandro** [libass/libass#179]
https://trac.videolan.org/vlc/ticket/14536

I test with current version libass 0.12.2. No improvement!!

**Comment by astiob** [comment]
Duplicate of #3.

**Comment by astiob** [comment]
Because the link is currently dead, here’s what Google’s cache has:

> Sample: ​https://drive.google.com/file/d/0BzWbz74_aanZdW5rTDZFZVF5YzA/view?usp=sharing
> Screenshot: ​http://imgur.com/a/cSEQE
