### ISSUE TITLE
Stroker mishandles complicated glyphs

### ISSUE THREAD

**Issue by ghost** [libass/libass#182]
Here the sample:
- Subtitle
- Font
- Compare with XySubFilter

https://www.dropbox.com/sh/08typy5d54lwn4j/AABahotK17kTyXFeP1yAzhHla?dl=0

**Comment by astiob** [comment]
I thought we had an issue open for this, but I couldn’t find it either here or on the old Google Code tracker.

@Morecutter Thanks for the report, but in the future please try to describe the actual problem in the title and in the report.

Basically, the way we currently use the FreeType stroker means we get bad output if the outlines contain self-intersections and in some other odd cases. For self-intersections, which is the only case I’ve seen in the wild so far, the badness of the output typically manifests as visible gaps in the border around the glyph like in the provided screenshots.

I remember investigating this, so I’ll dig out additional artificial broken examples at some point. In fact, I even have a [branch](https://github.com/astiob/libass/tree/stroke-gaps) where I attempted to fix this but failed; I think I fixed some things and broke others.

**Comment by wm4** [comment]
>@Morecutter Thanks for the report, but in the future please try to describe the actual problem in the title and in the report.

Also don't use dropbox, it's god-awful. Filing your taxes is easier than making dropbox actually display these images unscaled (which matters here a lot to see the actual problem).

**Comment by astiob** [comment]
This was fixed by #236, released in libass 0.14.0.
