### ISSUE TITLE
Underline `j` has too long underline

### ISSUE THREAD

**Issue by avih** [libass/libass#193]
Underlining `j` extends too much to the left (the right side seems OK).

It seems the issue is worse the smaller the font size is, and I didn't notice this issue with underlining chars other than `j`:

Using the following string:
`x{\u1}j{\u0}x`

(note that github sanitizes the image display size, but the second image is more than twice bigger than the first)

![](https://0x0.st/zm8.jpg)

![](https://0x0.st/zmK.jpg)

I'm testing with mpv master with libass 0.12.3, but this also reproduces with lachs0r's build with libass from 2015-09-03 (the "fonts" branch).

Testing with the following Lua script:
```
mp.osd_message(mp.get_property_osd("osd-ass-cc/0") .. 'x{\\u1}j{\\u0}x' .. mp.get_property_osd("osd-ass-cc/1"), 10)
```

Or from an `.ass` subtitles file (without the extra backslash escaping that the lua script has).

**Comment by grigorig** [comment]
FIY, I already investigated this, looks like something related to scaling is messed up. I'll get back it to it later today, hopefully.

**Comment by grigorig** [comment]
Please test the referenced commit. Does it fix it for you?

**Comment by avih** [comment]
Thanks. I don't have a setup to test custom builds right now. Hope I'll manage to test it tomorrow.

**Comment by avih** [comment]
Ah, the patch applies cleanly to 0.12.3, so it was easier for me to test, and I tested with patched 0.12.3 .

It fixes half the problem - it indeed no longer depends on the font size.

However, `j` (lowercase only) underline still extends too much to the left IMO. I tested it with `DejaVuSans.ttf` and `times.ttf` (Windows Times New Roman) and both exhibit the same issue. The issue does not happen with monospace fonts (tried Consolas and Monaco).

I looked around a bit, and I found two places lower which sort of suggect that `j` could be "special" - by having a negative left side unlike most other chars:

> [1] ... but if the j is always (or nearly always) meant to be closer to its left neighbors, then having the negative left sidebearing means that you have less kerning to do ...

and

> [2] Note that the left margins of 'f' and 'g' are zero, (light green arrows) and 'j' is negative ...

So maybe handling of negative left side is what's essentially need improving.

This might or might not be related, but on #194 I asked how to have `\` immediately followed by an override tag without escaping the `{`, and one of the suggestions was to use a zero-length-space between them. So I added a `U200B` char between `{\u1}\` and `{\u0}` which should have zero width, and while it didn't escape the `{` anymore and did terminate the underline, it also extend the underline too much to the right of the `\` as if it's also underlining the invisible char.

So the zero-length-space char is getting an underline while I think it shouldn't. So it might or might not be related to this, assuming this issue is of incorrectly interpreting the left and right edges of the char while underlining.

----
[1] http://ilovetypography.com/2007/10/29/so-you-want-to-create-a-font-part-2/
[2] https://courses.engr.illinois.edu/ece390/resources/varfont/varfont.html

**Comment by grigorig** [comment]
Well, there is only some much we can do with the given metrics. It might be possible to simply ignore the bearing (the distance between pen position and actual start of the character), but then the line will probably be too short.

**Comment by avih** [comment]
> Well, there is only some much we can do with the given metrics.

Does this imply that the font data could be "bad"? at which case I'd agree libass shouldn't try to "fix" it.

However, my hunch right now is that the metrics are not interpreted correctly in libass. Other renderers don't seem to have this issue, so either they all work around it, or the metrics could be interpreted more correctly than libass does.

Here's how Firefox (windows) renders it (I also tested on Firefox-linux, Chrome, IE and Wordpad and they all seem to agree on where the underline starts/ends) :
![Firefox](https://0x0.st/z_p.jpg)

And that's how Libass renders it (regardless of font size):
![libass](https://0x0.st/z_f.jpg)
Note how while the DejaVu rendering seems reasonable, and the Verdana rendering seems acceptable, the Times rendering looks plain wrong. In fact, when underlining the `j` in `xj`, the underline extends longer to the left than when underlining the `x` in `xj`...


> It might be possible to simply ignore the bearing, but then the line will probably be too short.

Not sure actually. While I didn't compare it pixel to pixel, it does seem to me that the common way to render it outside of libass is to start the underline of the current char exactly where the underline of the previous char would have ended, thus possibly ignoring the bearing.

**Comment by grigorig** [comment]
Then let's just do this.

The issue with U+200B and other space character is due to some relatively complex interaction between HarfBuzz and the rest of libass' layout code: HarfBuzz actually just uses U+0020 (the regular space) as the glyph image for these characters, likely to avoid problems with missing glyphs in fonts. The low-level font loading code of course doesn't know about this. So HarfBuzz is too clever here. Not sure if there is an easy fix (except switching to 'simple' shaping), but handling strikes at this point in rendering isn't the greatest idea anyway. libass really needs to move away from that long term.

**Comment by avih** [comment]
So I tried 794ec32, much better! it's now quite consistent with other font renderers and fixes the initial issue of wrong `j` underline. I tested underline in all three fonts (and a monospace font) and with all letters/plain-symbols, and I think they all look good.

I noticed another underline issue, however. It's minor IMO so not sure if it's worth handling:

When underlining some letters or the following or preceding space for those letters (some only one of following/preceding), then the width with underline is different than the width without it. It didn't happen with Verdana or DejaVu Sans, but it did happen with Times new roman.

These combinations were affected - all of them capital (on each one underlining the letter or the space changed the width): A/T/V/W/Y - with space either before/after, L/P - with space after.

But this seems very minor to me since it should be quite rare to render with/without the underline in quick succession, and so very unlikely that someone would notice the difference.

Overall, this patch improves underlining a lot already as is. Thank you.

**Comment by grigorig** [comment]
> When underlining some letters or the following or preceding space for those letters (some only one of following/preceding), then the width with underline is different than the width without it. It didn't happen with Verdana or DejaVu Sans, but it did happen with Times new roman.

Which width? In some cases, the glyph bounding box is used to calculate layout sizes. And of course the bounding box with underline can be larger than without.

If this is actually a problem, we should open a separate issue for this.

**Comment by avih** [comment]
> Which width?

Hard for me to tell if it's of the letter itself or of the space, but I'll give an example.
- `XAXX` is always fine,
- `X AXX` -> when either the space or the A are underlined, the `AXX` part is shited to the right by few pixels.

`X A XX`
- when the first space is underlined, the `A XX` part is shifted right by few pixels.
- When the A is underlined, the spaces on _both_ its sides seems bigger than when the A is not underlined.
- When the second space is underlined, the `XX` part is shifted to the right by few pixels.

However, if you replace A with R at all these examples, then the width of all chars remains constant regardless of which char is underlined.

> In some cases, the glyph bounding box is used to calculate layout sizes. And of course the bounding box with underline can be larger than without.

I'm not a fonts expert, but could it? When I tested these exact strings in Wordpad, none of them resulted in any change to the width of any char. They only changed whether or not there was a visible underline to each char.

> If this is actually a problem, we should open a separate issue for this.

Depends on the definition of "actually a problem". Technically I'd think the behavior is incorrect. But it doesn't bother me personally, and like I noted earlier I think it's highly unlikely that users would notice it in practice.

Up to you if you feel like doing something about it or not.

**Comment by grigorig** [comment]
I was thinking this might just affect placement of events, centering of lines and things like that, i.e. nothing per glyph. Your description makes it clear that is not the case. This definitely looks iffy. I'll try to reproduce it later.
