### ISSUE TITLE
Invalid loop condition on line 195 of ass_font.c causing "Error opening font" issues.

### ISSUE THREAD

**Issue by mattgallagher** [libass/libass#198]
Line 195 of ass_font.c is:

            for (int i = 0; face->num_faces; i++) {

it should be:

            for (int i = 0; i < face->num_faces; i++) {

The incorrect loop counter is causing "Error opening font" errors for me looking up fallback glyphs "Glyph 0xB098 not found, selecting one more font for (Arial, 400, 0)" on a Mac (fallback font AppleSDGothicNeo-Regular.otf has face->num_faces == 1 but it iterates over that face and fails on the next, non-existent face).

Fixing the loop counter fixes the problem.

**Comment by wm4** [comment]
Thanks! Next time just a pull request would be nice too.
