### ISSUE TITLE
enca support is missing in 0.13

### ISSUE THREAD

**Issue by Civil** [libass/libass#204]
I know that it was removed, but it's actually useful for Russian subtitles, as there several encodings for Russian language (cp1251, koi8r and of course utf8 + utf16), and actually all of them are still in use.

Without enca (or other char detection support) I'm, as a user, forced to try different encodings by myself. So please bring it back, until you implement better way to handle multiple encodings.

Thanks!

**Comment by grigorig** [comment]
We decided that charset detection is out of scope for libass. So if you need that, please ask the maintainers of your media player to add such a feature.
