### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by dalent** [libass/libass#205]
i cant build it for arm64(iphone)  with macos, why?  not supported for armv8/arm64?

**Comment by astiob** [comment]
Can you describe your problem in more detail? How exactly are you building it and what exactly fails?

**Comment by dalent** [comment]
```javascript
 ./configure --build=armv8 
 ./configure --build=armv8  --host=armv8  
 ./configure  --host=armv8 
```
but no one works. Is the cofigure right?

**Comment by dalent** [comment]
i also with 
```javascript
./configure --host=arm-apple-darwin
```
it report an error 
symbol(s) not found for architecture x86_64

**Comment by astiob** [comment]
I assume you’re trying to build with Apple’s SDK for iOS.

`--host=arm-apple-darwin` is correct (although it’s missing the Darwin version number, but I don’t think this matters).

I’m not sure about now, but a few years ago it used to be the case that just specifying `--host` wasn’t enough due to the iOS SDK occupying a separate directory within the Xcode installation. Try to add:

```shell
SDKROOT=iphoneos
CFLAGS="-isysroot `xcodebuild -version -sdk iphoneos Path` -arch arm64"
LDFLAGS="-isysroot `xcodebuild -version -sdk iphoneos Path` -arch arm64"
CC="xcrun clang"
export SDKROOT CFLAGS LDFLAGS CC
# or don't export and just run SDKROOT=... CFLAGS=... LDFLAGS=... CC=... ./configure ...
```

In any case, keep in mind that you also need to have (at least) FreeType and fribidi already built for arm64 for libass to build successfully.

**Comment by nomadli** [comment]
i build arm64 ok, but build  armv7 and armv7s is error:
`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: library member: .libs/libass.a(libfribidi.a) is not an object file (not allowed in a library with multiple architectures)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: internal ranlib command failed`

my script
`./autogen.sh
./configure --prefix=${TMPROOT} --disable-enca \
      --host="arm-apple-darwin" \
      --enable-static=yes \
      --enable-shared=no \
      CC="$(xcrun -find -sdk iphoneos clang)" \
      AR="$(xcrun -find -sdk iphoneos ar)" \
      LD="$(xcrun -find -sdk iphoneos ld)" \
      LDFLAGS="-arch armv7 -isysroot `xcodebuild -version -sdk iphoneos Path` "  \
      CFLAGS="-arch armv7 -isysroot `xcodebuild -version -sdk iphoneos Path" \
      FRIBIDI_CFLAGS="-I${ROOT}/../libfribidi/include" \
      FRIBIDI_LIBS="${ROOT}/../libfribidi/libfribidi.a" `

**Comment by TheOneric** [comment]
libass does build on arm64 and other arm-targets *(but there's no optimised assembly)*; see eg [here](https://github.com/TheOneric/libass-regression-tests-tmp/runs/2568688966?check_suite_focus=true) or [Debian's build logs](https://buildd.debian.org/status/package.php?p=libass)
*(Debian's `armhf` ABI is armv7 with hard-float EABI; `armel` uses soft-float EABI and it's current baseline is armv5T, [before Buster](https://packages.debian.org/stretch/libass5) the baseline was armv4T)*
