### ISSUE TITLE
Subtitles suddenly stop now and then

### ISSUE THREAD

**Issue by CreamyCookie** [libass/libass#206]
There's an anime I'm watching with SMPlayer (which is using libass). Now and then (often after the first half of the video) the subtitles are simply gone. However, when I then restart SMPlayer and rewind a bit the subtitles are often displayed correctly.

What information would you need to fix that? (or figure out if it's libass' fault)

**Comment by cyberl33t** [comment]
I'm also having this problem while using SMplayer (on Gentoo). It seems that the problem is present only while using the latest (0.13.1) released version of libass, 0.13.0 and earlier seems to work fine.

**Comment by wm4** [comment]
Does this happen without smplayer too?

**Comment by CreamyCookie** [comment]
Yes, I had the same problem with VLC, which also [seems to use libass](https://github.com/videolan/vlc/blob/master/modules/codec/libass.c). I think it mostly happens after the beginning of a new chapter in the mkv file. (e.g. the anime "Nichijou" with English subtitles)

**Comment by wm4** [comment]
Are these ordered chapters, and does it happen on chapter boundaries?

**Comment by CreamyCookie** [comment]
What are ordered chapters? How can I check if it happens on chapter boundaries? The file is an mkv file where there are these chapters (although for some reason in VLC 'OP' and 'ED' are missing). 

* Prologue 
* OP
* Part A
* Part B
* ED
* Preview

I think the bug happens about when Part B starts.

**Comment by astiob** [comment]
Ordered chapters using segment linking<sup>†</sup>, which is probably what @wm4 was most interested in, are those where you have to have a separate file (containing just the chapter) in the same directory for a chapter to play, and if you don’t have the file, the chapter is simply skipped over. In fact, it sounds like the OP and ED in your case may be exactly this. (Are you playing the file from the same location when using VLC?)

<sup>†</sup> This isn’t even the most precise name for it. Thanks for making this easy, Matroska specification.

Anyway, part A and part B are unlikely to use segment linking. I can’t think of a reason why a plain chapter boundary like that could have any effect on anything…

We can try three things to narrow this down further:

* Play the file in [mpv](https://mpv.io/) and see if the problem appears there as well. We believe that mpv uses libass correctly, so if it doesn’t happen in mpv, there might be a bug of some sort in both SMPlayer and VLC that got exposed by the latest libass updates.

* If you can, build libass with the single commit de4ea4bbd1c5101bf0b572a4facd58875845f495 reverted, build/use SMPlayer or VLC with this custom build of libass and see if the problem disappears. This commit introduced some restrictions on how players can use libass, so it might be that SMPlayer and VLC are breaking these restrictions, intentionally or not. On the other hand, if the problem does not disappear, we will know that this change is unrelated and avoid a red herring.

* Tell us (privately if you wish) what specific file you’re seeing the problem in and how exactly we can reproduce it (in particular, when do we have to start playing? is it necessary to start at the beginning of the file and wait for 10 minutes or is there a quicker way?).

**Comment by wm4** [comment]
>so it might be that SMPlayer and VLC are breaking these restrictions, intentionally or not. 

I doubt it. At least I did look at the VLC code when making this change.

**Comment by CreamyCookie** [comment]
@astiob 

> Ordered chapters using segment linking†, which is probably what @wm4 was most interested in, are those where you have to have a separate file (containing just the chapter) in the same directory for a chapter to play, and if you don’t have the file, the chapter is simply skipped over. In fact, it sounds like the OP and ED in your case may be exactly this.

Wow, I didn't even know this is possible. And I was a bit puzzled why some files had opening and ending and other's don't. Turns out it was VLC's fault. 

> Are you playing the file from the same location when using VLC?
Yes

> Play the file in mpv and see if the problem appears there as well. We believe that mpv uses libass correctly, so if it doesn’t happen in mpv, there might be a bug of some sort in both SMPlayer and VLC that got exposed by the latest libass updates.

I'm currently using the mpv backend in smplayer. (I also tried the standalone version of mpv to be sure.)

> Tell us (privately if you wish) what specific file you’re seeing the problem in and how exactly we can reproduce it (in particular, when do we have to start playing? is it necessary to start at the beginning of the file and wait for 10 minutes or is there a quicker way?).

It seems that you have to start playing from the beginning. I tried to skip to before the new chapter and the bug didn't occur. If I remember correctly even speeding up resulted in the bug not appearing.

**Comment by wm4** [comment]
VLC does support ordered chapters.

I suspect this might be a problem with duplicate ReadOrder fields, although it's unlikely. You can try passing the ``--sub-clear-on-seek`` option to mpv.

I don't recommend using smplayer.

**Comment by CreamyCookie** [comment]
> I don't recommend using smplayer.

Why what's wrong with it? So far I'm really happy with the functionality of it.

**Comment by cyberl33t** [comment]
Haven't yet got time to test it with VLC or mpv, but on mplayer / smplayer the problem occurs when skipping backwards or forwards, or occasionally even when pausing the files: the subtitles are permanently lost for the rest of the file, unless the player is closed and restarted. If I play the whole file without touching anything, the subtitles work. Happens on several .mkv files.

**Comment by CreamyCookie** [comment]
@wm4 The subtitles even disappear when using `--sub-clear-on-seek`.

**Comment by astiob** [comment]
@CreamyCookie Have you tried older libass? I’ve taken a look at your file (thanks!), and it’s somewhat broken—at least in our understanding, maybe we’re wrong.

Each subtitle line in a Matroska (MKV) file has a field called “ReadOrder”, which specifies the ordinal number of the line in the original subtitle file before it was put inside Matroska. A renderer such as libass needs this number to be able to show the subtitles in the right order.

Libass also uses ReadOrder to filter out subtitle duplicates that it can get from the media player sometimes, mainly (only?) when seeking. This assumes the ReadOrder value of each line is unique… but in your file it isn’t. In fact, every chapter in your file resets ReadOrder to zero. I don’t know how this could happen, but it has. So ultimately, there are three possibilities:

1. This is in fact invalid as we thought, the file is broken, we don’t need to fix anything, and you need to complain to the fansubber.
2. This is in fact invalid as we thought, the file is broken, you should still complain to the fansubber, but we find a way to make it work in libass anyway.
3. This is in fact valid, and we need to fix libass and potentially all media players that use it.

@cyberl33t Your issue seems to be completely different from @CreamyCookie’s. Could you file it as a new issue on this tracker and tell us some more about it? The same questions/requests apply to you that I listed a few comments ago.

**Comment by wm4** [comment]
There was a bug with ``--sub-clear-on-seek`` in libass. You could try again with libass master.

**Comment by CreamyCookie** [comment]
@astiob Thanks! I can try, but you'd probably be faster doing it. If you still want me to try, should I try once with `master` and once with de4ea4bbd1c5101bf0b572a4facd58875845f495? Can I use the [mpv-build](https://github.com/mpv-player/mpv-build) script for that?

Happy Holidays! :)

**Comment by wm4** [comment]
Yes, just use ``./build`` instead of ``./rebuild``, because the latter updates (i.e. wipes out) all checkouts.

**Comment by CreamyCookie** [comment]
I can't get it to work. When I run `./build`, I get this:

```
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
libass/Makefile.am:26: error: Libtool library used but 'LIBTOOL' is undefined
libass/Makefile.am:26:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libass/Makefile.am:26:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libass/Makefile.am:26:   If 'LT_INIT' is in 'configure.ac', make sure
libass/Makefile.am:26:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
```

I have no idea what dependencies it needs.

Another sections mentions this:
```
Instructions for Debian and Ubuntu
==================================

**Warning**: DO NOT USE THESE INSTRUCTIONS UNLESS YOU KNOW WHAT YOU ARE DOING.
    These scripts are fragile (probably rather Debian's fault than ours). They
    will often fail with weird errors that are hard to solve. They only exist
    for users who want to hurt themselves. Use the generic instructions, unless
    you really insist on having a Debian package as result.
```

I don't want to hurt myself.

**Comment by wm4** [comment]
>I have no idea what dependencies it needs.

I think you simply need libtool. But not too sure.

>Another sections mentions this:

This warning is only for the case when you want to use the Debian scripts for creating .deb packages.

**Comment by CreamyCookie** [comment]
@wm4 Thanks, I also had to install libfribidi-dev. Sadly the bug is still there. Both when using smplayer with the new mpv build and also when just executing `./mpv-build/mpv/build/mpv --sub-clear-on-seek FILE.mkv`

This is the result of `./mpv`:

```
mpv 0.14.0-git-e1993d5 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sat Dec 26 10:44:21 CET 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: n2.8.4
```

**Comment by basinilya** [comment]
I have a similar problem with mplayer and libass 0.13.1. When seeking backwards, already shown subtitles won't be shown again. Traced to libass code with gdb:

       │185     static int test_and_set_read_order_bit(ASS_Track *track, int id)                                                                                                           │
       │186     {                                                                                                                                                                          │
       │187         if (resize_read_order_bitmap(track, id) < 0)                                                                                                                           │
       │188             return -1;                                                                                                                                                         │
       │189         int index = id / 32;                                                                                                                                                   │
       │190         int bit = 1 << (id % 32);                                                                                                                                              │
       │191         if (track->parser_priv->read_order_bitmap[index] & bit)                                                                                                                │
      >│192             return 1;                                                                                                                                                          │
       │193         track->parser_priv->read_order_bitmap[index] |= bit;                                                                                                                   │
       │194         return 0;                                                                                                                                                              │
       │195     }                                                                                                                                                                          │

I can't see any place where read_order_bitmap is reset

**Comment by wm4** [comment]
It's not normally supposed to be reset, and I'm fairly sure the mplayer code doesn't expect that either.

**Comment by basinilya** [comment]
I think in the past libass didn't check for duplicate events, that's why mplayer calls `ass_flush_events()`

**Comment by wm4** [comment]
>I think in the past libass didn't check for duplicate events,

It did.

> that's why mplayer calls ass_flush_events()

This function is broken in 0.13.1.

**Comment by astiob** [comment]
0.13.2 has just been released and contains a fix for `ass_flush_events()`. If you were using 0.13.1, please try again with 0.13.2.

**Comment by CreamyCookie** [comment]
@astiob Sadly, the issue still there for me.

**Comment by astiob** [comment]
@CreamyCookie Sorry to ask again, but can you make sure to test it with `--sub-clear-on-seek`, mpv v0.15.0 (or at least mpv-player/mpv@ad072b17ce7d4ae8f5e6605cf7237c5fd15d283d) and libass 0.13.2 (or at least cfa1a61e39f218fe4dc288ddf44b85200ff35fdd)? I think your file should work with this setup.

**Comment by CreamyCookie** [comment]
@astiob I've tried libass 0.13.2, but now after updating mpv to v0.15.0 it works :smile:

Could `--sub-clear-on-seek` be enabled by default?

**Comment by astiob** [comment]
@wm4 What are the downsides `sub-seek` not seeking backwards? Can mpv perhaps always disable ReadOrder duplicate detection, not clear on seek and detect duplicates on its end by file position like it does for other subtitle formats?

**Comment by wm4** [comment]
Keeping the subtitle events in the ASS_Track has 2 uses in mpv:

- make subtitles show up immediately when seeking back
- make `sub-seek` and related functionality work

That seems indeed like a lot of trouble to keep this working, but I don't want to drop these features anyway.

> not clear on seek and detect duplicates on its end by file position like it does for other subtitle formats?

Would be slower for insane subtitles. The assumption is simply that non-ASS subtitles are not insane.

**Comment by astiob** [comment]
By insane subtitles, do you mean subtitles with very many events? Is it because the duplicate detection uses a data structure slower than the plain bitmap used by libass? And I guess a plain bitmap is unusable because file sizes (and hence file offsets) can be huge. It could still use some sort of hash map though. Of course, it would be slower than a plain bitmap, but surely it shouldn’t be too slow? I admit it’s extra effort and it’s not clear how widespread problematic files are (we should’ve gotten reports earlier if they were more widespread), but it would solve this issue once and for all. …Until a broken demuxer comes along, if I correctly understood the mpv commit messages I skimmed through. Sigh.

**Comment by wm4** [comment]
> By insane subtitles, do you mean subtitles with very many events?

Yes.

>  Is it because the duplicate detection uses a data structure slower than the plain bitmap used by libass? And I guess a plain bitmap is unusable because file sizes (and hence file offsets) can be huge.

Yes.

> It could still use some sort of hash map though. Of course, it would be slower than a plain bitmap, but surely it shouldn’t be too slow?

Possibly. It's a lot of effort though, because the hashmap would have to be written from scratch, just for duplicate checking.

At this point, I'm actually just thinking about somehow caching subtitle packets to handle seeking back. (The cache could be cleared if there are too many of them.) This could perhaps even be implemented in libass: a mode that preserves past subtitles, but only up to a threshold. Then even bubblesort would be fast enough. It would help other API users too (instead of just mpv).

On the bright side, newer mkvmerge subtitles write a perfect index for subtitle packets, which can be used to prefetch subtitle packets when seeking. At least mpv and lavfilters implement this. But it doesn't fix old files.

**Comment by TheOneric** [comment]
If I'm reading this correctly, there was:
 - bugs in how libass handled `ReadOrder` and flushing
 - bugs or questions about the (default) behaviour of media players
 - a broken file which used the same `ReadOrder` for distinct events

The libass bugs discussed have already been resolved, so if I didn't miss something this can be closed?
