### ISSUE TITLE
Feature Request: Import - Base system

### ISSUE THREAD

**Issue by latot** [libass/libass#208]
Hi all, well i wanna propose this option, the idea is can use other ass file as a base to use the data in the new sub, for example, in one sub.base i write the timing and styles of the subs, next in a second file sub.ass i write the subtitles and from this file call the first, or in a file write the styles in other the timing and other the text. ideally can use this with mkv. Are a lot of ways to think this.
I think all can know the advantaje of this....
its basically the same import concept of programing in ass, but more flexible (can split text from time - style or even the subs (every dialogue) can be able use some id system)

I know i'm very bad explaining this things so any question ask :D 

Thx. Cya.

**Comment by rcombs** [comment]
I'm not 100% sure I understand what you're suggesting, but I'm pretty sure it's out of scope for this library.

**Comment by wm4** [comment]
I'd also say so. Use some kind of preprocessor that generates a complete .ass file if you need this. I would say the main focus of libass is on rendering subtitles demuxed from mkv anyway.

**Comment by latot** [comment]
mm, a preprocessor its good way to think this, but in the case to can use this in a mkv file, where should it be?

**Comment by astiob** [comment]
But why do you want to do this within an MKV file? Surely you can just preprocess the files first and then mux the full resulting files into the MKV file.

**Comment by latot** [comment]
mm, writing behind the idea.

its an idea for when we have a lot of videos with subs, and we have a lot of languages, actually if we wanna fix/change one thing of this params, we need change all the files and if we don't have scripts we most do it manually, and other cases like actually for example in fansubs the ppl translate with a base .ass or making all from 0, and if for example we need fix the timing we need change all the files, and if was used for other ppl in some time it should be do, It feels more complicated than it has to be, and this is only with a few cases, with an import option we can only update one file and do this more simple in a lot of sense. Other reason is the future of mkv project, one of the ideas of the project for example is can use menus, that means can one mkv have a complete bd or dvd, there i think that option can be very usefull, including actually f

or ex. can call a extern base file, or when ppl split the mkv videos (mkv have that option, call extern videos).
This don't is only for mkv, should can help always while we have the base files (ex mp4 with ass)

Anyway, i think one of the ideas its can be more easy, therefore for a user as an worker place (ex fansubs. and similars)

@rcombs i do a little example to can understand easier this, the uploaded file, its only a interpretation of the import idea.

Sorry my very bad eng.
Cya.

[ass.zip](https://github.com/libass/libass/files/58821/ass.zip)

**Comment by grigorig** [comment]
Whatever, this is an issue with authoring tools, not libass. Maybe a feature that helps with your use case can be added to Aegisub?

**Comment by latot** [comment]
mm, i don't use aegisub, and i don't like the idea, tools like mkvmerge try to do this more simple and minimalist, avoiding focusing the tools, avoiding the "compilation" fase, and if we preproccess it before the video (the .ass will be the same), the function will be useless when some one will use the subs, it will have no sense deleteing the portability option because you will can't share it. lose to much potential.
