### ISSUE TITLE
Internal rasterizer overflows on outlines with huge coordinates

### ISSUE THREAD

**Issue by wm4** [libass/libass#210]
The file http://a.pomf.cat/fersvc.mkv will hang and misrender, and the log message `Glyph bounding box too large: 41942786x41942786px` is emitted.

I tried with libass git master on Windows and Linux, and I can reproduce it on Windows only. I tried both DirectWrite and Fontconfig. In all cases, the same fonts are selected. On Linux, it goes smoothly without printing errors. I have no explanation for this.

**Comment by astiob** [comment]
Same deal as #185, except now that there are actually some points in the glyph outlines (which get their coordinates set to `LONG_MIN` by `transform_3d_points`), the internal rasterizer overflows. The FreeType rasterizer is fine.

@MrSmile I realize this isn’t normal input and overflow isn’t always easy to avoid, but perhaps it can be fixed somehow? I see lots of places where you compute averages by summing several integers and then right-shifting the sum (by the way, does this do what you want for negative numbers?); that’s probably where the overflow occurs.

**Comment by astiob** [comment]
For clarity, let’s devote this issue to the rasterizer overflow, which the commit above tries to prevent. Broken `\fscx0` will be dealt with in #185.
