### ISSUE TITLE
OS X: libass.pc is missing `-framework` options for CoreText

### ISSUE THREAD

**Issue by eelco** [libass/libass#211]
When using a libass build with CoreText support to build another app (e.g. FFmpeg) it results in linker errors because the `-framework` options are missing are missing from `libass.pc`

**Comment by grigorig** [comment]
Does anyone of the Mac people know what's the correct way to handle this is?

**Comment by rcombs** [comment]
Should suffice to add the `-framework` args we currently add to `LIBS` to `Libs.private` in libass.pc. The current behavior here is a little awkward; I'm not sure why, but we apparently put non-framework dependencies in either `Libs` or `Libs.default` depending on whether we're linking shared or static?
