### ISSUE TITLE
Arabic not work right

### ISSUE THREAD

**Issue by kirito90** [libass/libass#224]
hi,

in vlc
![vlcsnap-4605-11-10-18h07m59s315](https://cloud.githubusercontent.com/assets/19803917/15867994/5fcedabc-2cee-11e6-8724-4aa9d0d097c1.png)

in MPC
![mystery-fansub detective conan-807 hd-7s20p 97fbbb96 mkv_snapshot_00 01_ 2016 06 07_20 24 09](https://cloud.githubusercontent.com/assets/19803917/15867995/5fd11368-2cee-11e6-8e0b-4da530ce2470.png)

script
http://rgho.st/78jxfmstX

**Comment by grigorig** [comment]
libass forces RTL base direction if encoding 178 is used. I don't really know why I added this. Maybe we should just drop it and always use LTR base direction, which is what vsfilter seems to do.
