### ISSUE TITLE
Square character on libass, correct character on vsfilter

### ISSUE THREAD

**Issue by sl1pkn07** [libass/libass#228]
on libass (mpv) (linux)
![mpv-shot0011](https://user-images.githubusercontent.com/462213/78239086-984d0400-74dd-11ea-864f-900200faa54b.png)

vsfilter (mpc) (windows)
![nagato](https://user-images.githubusercontent.com/462213/78239468-0396d600-74de-11ea-91de-8772bc9f8576.jpg)

zero messages about the font in libass

video snipplet
https://sl1pkn07.wtf/libass/square_character.mkv

full release : XDCC irc.rizon.net `/msg [AU]Ginko xdcc send #2359`

**Comment by wm4** [comment]
Happens on Linux too.

**Comment by aphirst** [comment]
I'm having issues connecting to the site, and nyaa is long gone. @sl1pkn07 Are you able to reload, or can someone confirm that the site does actually still work?

**Comment by sl1pkn07** [comment]
https://anidex.info/?page=torrent&id=27079

**Comment by TheOneric** [comment]
I don't actually know much about font internals, but I noticed that when using other combinations then 'rt' eg 'rrt",'rd',… everything is displayed as expected. I'm guessing it might be the same (or asimilar) issue as #136 .
The same placeholder glyph is being rendere in pluma when using the packed "Drawing with Markers" Font. So this is probably not a libass-specific issue, but either an issue with the font itself or (lesss likely) an issue with freetype.
Does somebody know how to check if the font is valid ?

Also this should be the relevant lines:
```
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Summer Plans,Drawing with Markers,120,&H2F171C19,&H000019FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:05.02,0:00:09.48,Summer Plans,,0,0,0,,{\1c&H000000&\1a&H00&\t(0,500,\1c&H171C19&\1a&H30&)\blur0.6\move(640,127,640,138)\t(\fscx91.1\fscy91.1)}Exhibición de fuegos artificiales
```

**Comment by astiob** [comment]
Right, the font contains a contextual ligature for “art” that replaces the “r” with an undefined glyph. Thanks! Closing this in favour of #136.
