### ISSUE TITLE
"Loading font file ..." is MSGL_WARN, should probably be MSGL_INFO or less

### ISSUE THREAD

**Issue by avih** [libass/libass#231]
Here https://github.com/libass/libass/blob/master/libass/ass_fontselect.c#L178

As far as I can tell this is a legitimate setup where libass loads fonts from a non system dir, and if the fonts are there then it's highly likely that the user put them there exactly such that libass can load them, at which case I don't quite see why the message about loading them should be flagged as a warning.

This ends up with very verbose output of application which pass libass messages above certain level - such as mpv. With mpv, if the user wants to load fonts from a non default dir then the console is cluttered with libass messages since libass classifies them as warning - which mpv finds important enough to display to the user by default.

I think It should probably be either MSGL_INFO or even MSGL_V, since as far as I can tell this is a normal and expected course of action when loading those fonts.

I can also send a PR, just tell me which level you prefer.

**Comment by grigorig** [comment]
MSGL_INFO sounds fair to me. Please send a pull request.
