### ISSUE TITLE
license file has no copyright notice

### ISSUE THREAD

**Issue by waldyrious** [libass/libass#234]
The [license text](https://github.com/libass/libass/blob/master/COPYING) says "(...) provided that the above copyright notice and this permission notice appear in all copies" but there's no copyright notice above. The ISC sample text (as most licenses do) includes a copyright notice at the top -- see an example [here](http://choosealicense.com/licenses/isc/).

How about `Copyright (c) 2016, libass contributors`?

(Btw, adding the license title would be nice, too.)

**Comment by grigorig** [comment]
Every source code file should have a header, so this is a bit redundant. Still, thanks for the hint.

**Comment by waldyrious** [comment]
Shall I submit a PR then?
