### ISSUE TITLE
Low performance on ARM architecture

### ISSUE THREAD

**Issue by duyhotan2000** [libass/libass#235]
Hello,

I am running libass with MPV on an ARMv8 SoC board, Linux OS. I found that the performance of libass is very slow, so there are many dropped frames due to long drawing time. I discovered the source code and only see the x86 implementation of algorithms.

Now, is there any implementation for ARM?

Thank you!

**Comment by feliwir** [comment]
For ARM the algorithm that is written in C is used. There is no version in assembly used for ARM if you were asking about that

**Comment by grigorig** [comment]
Let's keep this open to track progress on ARM optimizations.

**Comment by kirito90** [comment]
well, I note this in Android Mobiles too

**Comment by CoXier** [comment]
@grigorig
Recently I build ffmpeg on Android (ARM) with `libass` whose version is `libass-0.14.0`.
I also found its performance is slow. 

There is code in `libass/libass/ass_fontselect.c`.

```c
    priv->default_provider =
                    font_constructors[i].constructor(library, priv, config);
```
This "constructor" is used to construct a `ASS_FontProvider` and it takes almost **17s+** on my old `Nexus 5`. It's too slow. 

> **Test devcie**:  Nexus 5 Android 6.0

**Comment by CoXier** [comment]
How does fontconfig use the cache? Can I build the cache by myself?

**Comment by astiob** [comment]
libass uses Fontconfig to find and choose fonts for rendering subtitles. It builds a cache of all fonts installed on the system so that when libass (or other consumer) looks for a font, it can just consult the cache rather than search through all font files every time. It builds the cache when it is first invoked and rebuilds it whenever it detects a change in the system font directories. The only other way to build the cache that I know of is by explicitly invoking the `fc-cache` utility that is built as part of Fontconfig.

**Comment by luluwangwang1989** [comment]
> Hello,
> 
> I am running libass with MPV on an ARMv8 SoC board, Linux OS. I found that the performance of libass is very slow, so there are many dropped frames due to long drawing time. I discovered the source code and only see the x86 implementation of algorithms.
> 
> Now, is there any implementation for ARM?
> 
> Thank you!

how you compile the libass on ARMV8 successfully?

**Comment by TheOneric** [comment]
#559 added assembly for aarch64, improving performance for 64-bit ARM. Afaik there are currently no plans for 32-bit ARM assembly, but patches are welcome *(if you do want to write new assembly, use [checkasm](https://github.com/libass/libass/pull/667) to ensure correctness)*.
