### ISSUE TITLE
Best way to communicate potentially sensitive bugs

### ISSUE THREAD

**Issue by brandonprry** [libass/libass#239]
Hi, I have been fuzzing libass and have a few potentially sensitive bugs. What's the best way to get them to you?

Thanks!

**Comment by rcombs** [comment]
For lack of a more official address, I guess you could send them to libass@rcombs.me; if you're uncomfortable disclosing details in cleartext, we can work out an address and PGP key to use.

**Comment by wm4** [comment]
Please send them to nfxjfg@googlemail.com too.

**Comment by grigorig** [comment]
Please also consider sending them to greg@chown.ath.cx

**Comment by astiob** [comment]
Please also send them to chortos@inbox.lv.

**Comment by brandonprry** [comment]
rcombs, should I send them to the others here as well or just you? No need for PGP, it's not that sensitive.

**Comment by brandonprry** [comment]
I've sent them to rcombs, I am sure he can distribute as needed.
