### ISSUE TITLE
mpv osd is broken in recent libass

### ISSUE THREAD

**Issue by l29ah** [libass/libass#245]
Recently https://i.imgur.com/p7csdmr.jpg became https://dump.bitcheese.net/files/atogime/screenshot-mpvmpv.png
Bisecting says:
2a45128601458dd6ec9df90d2825a1ba7a9cc176 is the first bad commit
commit 2a45128601458dd6ec9df90d2825a1ba7a9cc176
Author: Grigori Goronzy greg@chown.ath.cx
Date:   Tue Sep 1 01:17:53 2015 +0200

```
fontselect: remove static fallback font list

The default font provider needs to provide a GetFallbackFunc callback
instead.
```

:040000 040000 c9f34462cb3c6808aa84a1653477bf5a16e0a5df 7b54054b32dff021a567c6862eff6e17e08c3615 M  libass

**Comment by grigorig** [comment]
Can you details about your OS/platform?

Maybe also logs that show what libass does and what font provider it is using? You can configure mpv to dump verbose libass messages.

**Comment by l29ah** [comment]
On Sat, Oct 15, 2016 at 06:24:06AM -0700, Grigori Goronzy wrote:
> Can you details about your OS/platform?

Gentoo Linux.

> Maybe also logs that show what libass does and what font provider it is using? You can configure mpv to dump verbose libass messages.

0.12.3:

[osd/libass] Raster: FreeType 2.7.0
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.3.2 (COMPLEX)
[osd/libass] Initialized
[osd/libass] Setting up fonts...
[osd/libass] Adding memory font 'mpv-osd-symbols'
[osd/libass] Done.
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'DejaVuMathTeXGyre-Regular'
[osd/libass] Font info: family 'DejaVu Math TeX Gyre', style 'Regular', fullname 'DejaVuMathTeXGyre-Regular', slant 0, weight 80
[osd/libass] fontconfig_select: (sans-serif, 80, 0) -> /usr/share/fonts/dejavu/DejaVuMathTeXGyre.ttf, 0


2a45128601458dd6ec9df90d2825a1ba7a9cc176:
[osd/libass] Raster: FreeType 2.7.0
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.3.2 (COMPLEX)
[osd/libass] Initialized
[osd/libass] Setting up fonts...
[osd/libass] Done.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
No, it works fine now.
