### ISSUE TITLE
libass - reporting potential security vulnerabilities

### ISSUE THREAD

**Issue by inferno-chromium** [libass/libass#252]
@grigorig @wm4 

Our OSS-Fuzz fuzzing effort (https://testing.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html) has located security vulnerabilities in libass using the fuzz target we developed.
https://clusterfuzz-external.appspot.com/v2/testcases?job=libfuzzer_asan_libass&open=yes

These issue are now filed in security-protected monorail tracker and we'd like to find developers to take a look at them.

We will CC developers on these issues to give them access to stack traces and reproducer data. For that we'd need an e-mail with associated google account. We will also set up the process to auto-CC these people when we find more issues.

Check out https://github.com/google/oss-fuzz/tree/master/projects/libass and you can submit a pull request to add an email for easy access to those current testcases.
(@kcc, @mikea as fyi)

**Comment by kcc** [comment]
@eugenis FYI

**Comment by rcombs** [comment]
`rodger.combs@gmail.com`, if you please

**Comment by grigorig** [comment]
Sorry @eugenis, the effort to set up some kind of mailing list somehow went nowhere...

So please feel free to add ```greg@kinoho.net```.

**Comment by inferno-chromium** [comment]
Ok added the contacts in https://github.com/google/oss-fuzz/commit/74e80885ee95890c6f0bbd9db48bcfbe6a3f2811.

cced you both on the two open bugs - https://clusterfuzz-external.appspot.com/v2/testcases?job=libfuzzer_asan_libass&open=yes. 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=229
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=194

**Comment by astiob** [comment]
Is it too late to add my email? @wm4 might be interested too. (And @MrSmile maybe?) My email (and primary Google account) is chortos@inbox.lv.

**Comment by inferno-chromium** [comment]
Not late at all, we can add members anytime. Can you please submit a pull request with your google associated email ids in the auto-ccs list of project.yaml file.

**Comment by astiob** [comment]
Thanks. I am now able to access clusterfuzz-external.appspot.com and see the stack traces, but I’m still not allowed to see the issues on the oss-fuzz bug tracker. I’m not sure how automatic this process is; do I just need to wait a bit longer to gain access, or should I ask you to add the extra users (myself included) there manually?

**Comment by inferno-chromium** [comment]
Usually it takes an hour to propagate, but i just explicitly clicked the cron, you should be able to cc issue now. Just a fyi, all of the info is in clusterfuzz testcase report page, so accessing the issue won't give you any more info. It is just a good way to get notifications on if the issue is fixed.

**Comment by astiob** [comment]
Got it. Thanks!

**Comment by astiob** [comment]
Is there any preferred way of crediting OSS-Fuzz in commit messages fixing the issues? And should I rather add or not add links to the issues on the oss-fuzz tracker?

**Comment by inferno-chromium** [comment]
Just 'Credit to OSS-Fuzz' is enough, if you want to add issue links that is fine as well.
