### ISSUE TITLE
Will it support picture event one day ?

### ISSUE THREAD

**Issue by tinybug** [libass/libass#253]
I have read the ass specs, there is a picture event in [Events] section. I try this event in my ass file, but it can't burn the picture in my video.  I check out the libass/ass.c, it seems doesn't parse picture event, will it support picture event one day?

**Comment by wm4** [comment]
Extremely unlikely. Nothing supports this kind of event. There are also events for running commands etc., all of which will remain unsupported.

**Comment by tinybug** [comment]
I see. Thanks anyway!
