### ISSUE TITLE
"Glyph bounding box too large" threshold is too low

### ISSUE THREAD

**Issue by rcombs** [libass/libass#260]
I'm seeing "Glyph bounding box too large: 4042x2308px" on some large clips, where "too large" is based on the wacky constant of 8000000 pixels defined in caf7e86eef8df95434798dec9b675da68fbef1ff. That check is now in `outline_to_bitmap` in ass_render.c (and also in `outline_to_bitmap_ft`, with slightly different logic). I assume this check was meant to protect against bitmap sizes causing integer overflow, but that's checked in `alloc_bitmap_buffer` now, so I think we should be fine? Removing the check fixes this case for me.
This particular case is clearly a bitmap being rendered at a size far larger than it needs to be (my monitor is 2880x1800, so this is well past its extents), but a fullscreen bitmap at 4K will be over 8M pixels, so there'll be reasonably-legitimate cases this affects.

**Comment by wm4** [comment]
I think even vsfilter copied that check at one point, due to semi-broken files that caused excessively large bitmaps to be allocated.

Unless someone still has this file and can find it, I'd say we should just remove the check against 8000000, and see how it goes.
