### ISSUE TITLE
SSA/ASS embedded fonts don’t work unless ass_set_fonts is called after they’re parsed

### ISSUE THREAD

**Issue by astiob** [libass/libass#266]
Embedded fonts are set aside during parsing and imported into fontselect later in `process_fontdata`, called only from `ass_embedded_fonts_add_provider`, called only from `ass_fontselect_init`, called only from `ass_set_fonts`. So embedded fonts are unavailable until `ass_set_fonts` is called. But it’s usually called before embedded fonts are parsed, so embedded fonts don’t work!

This breaks embedded fonts in external subtitle files in [VLC](https://github.com/videolan/vlc/blob/master@%7B2017-02-13%7D/modules/codec/libass.c#L233-L253) and FFmpeg’s [vf_subtitles](https://github.com/FFmpeg/FFmpeg/blob/master@%7B2017-02-13%7D/libavfilter/vf_subtitles.c#L378-L445) (which use `ass_process_codec_private` to parse the whole file except `Dialogue` lines: [VLC](https://github.com/videolan/vlc/blob/master@%7B2017-02-13%7D/modules/demux/subtitle.c#L1104-L1194), [FFmpeg](https://github.com/FFmpeg/FFmpeg/blob/master@%7B2017-02-13%7D/libavformat/assdec.c)), [Kodi](https://github.com/xbmc/xbmc/blob/master@{2017-02-13}/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp), MPlayer, [mplayer2](https://github.com/astiob/mplayer2/blob/all@%7B2017-02-13%7D/mplayer.c#L4568-L4717) (which use `ass_read_memory` to read the whole file), FFmpeg’s [vf_ass](https://github.com/FFmpeg/FFmpeg/blob/master@%7B2017-02-13%7D/libavfilter/vf_subtitles.c#L235-L237) and our [`test`](https://github.com/libass/libass/blob/master@%7B2017-02-13%7D/test/test.c#L207-L208) utility (which use `ass_read_file` to read the whole file). (Note: MPlayer’s internal copy of libass, which is used if a system libass is not found or is too old, is a copy from 2013. I don’t know how it behaves.)

Embedded fonts work in [mpv](https://github.com/mpv-player/mpv/blob/master@%7B2017-02-13%7D/sub/sd_ass.c#L203-L214), because it calls `ass_set_fonts` after calling `ass_process_codec_private` to parse the whole file except `Dialogue` lines (as parsed by FFmpeg).

**Comment by rcombs** [comment]
TBH I didn't realize embedded fonts were actually a thing anyone used. But this seems like it should be easy enough to fix, so w/e.

**Comment by tcyrus** [comment]
Wanted to check the status on this since there hasn't been any updates posted in a while
