### ISSUE TITLE
Horizonal artifacts with semitransparent box

### ISSUE THREAD

**Issue by felagund** [libass/libass#268]
Some people including me (see here: http://stackoverflow.com/questions/25870169/how-to-set-background-to-subtitle-in-ffmpeg/25880038?noredirect=1#comment71674932_25880038 ) would like to be able to put subtitles into semitransparent boxes. Libass supports opaque bozes very well and semi-transparent bozes with one line subtitles are just fine as well. (I attach a screenshot demonstrating the issue, ass file is copypasted below since I could not uplaod it as an attachment).

I asked at the aegisub forums: http://forum.aegisub.org/viewtopic.php?t=85495 and they forwarded me here. Apparently, this is a legacy of the ASS specs. However, introducing support for a new value of Borderstyle (and its correct rendering) would not break backwards compatibility and would solve this issue. I understand that things like this could be solved through ASS v5.0 https://github.com/libass/libass/issues/267 but that does not seem happening.

I would of course be happy with any way that would enable me to use semitransparent boxes without that ugly artifact.

[Script Info]
; This script was created by subtitleeditor (trunk)
; http://home.gna.org/subtitleeditor/
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
ScriptType: V4.00+
Title: Default Aegisub file
WrapStyle: 0
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,58,&H0000FFFF,&H0000FFFF,&H80000000,&H00000000,0,0,0,0,100,100,0,0,3,2,0,2,20,20,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0000,0000,0000,,There is an ugly horizontal artifact\N between first and second line of this subtitle

![horizontal_artifact](https://cloud.githubusercontent.com/assets/1218098/23102970/0f61316c-f6b3-11e6-9264-c1e4d3351d44.jpg)

**Comment by wm4** [comment]
(Apart from that, you could try BorderStyle=4, which is strictly non-standard and libass only, and which puts a single rectangular background over the bounding box of an event.)

**Comment by felagund** [comment]
Oh, that actually works beautifully! Great that somebody thought of that!

I have only one issue with it - horizontally, there is also no margin between the text of the subtitle and the end of the box (and it seems to be smaller than vertical margin). See screenshot below. Is there a way to adjust it and if not, could it be increased/made configurable? If I use  BorderStyle=3, setting Outline above zero increases this, but it also makes the horizontal line more pronounced.

![mpv-shot0002](https://cloud.githubusercontent.com/assets/1218098/23103157/a4de83b8-f6b6-11e6-817e-c56c7253669c.jpg)

**Comment by amayra** [comment]
there no way to make ASS v5.0 or to add new specs so to change libass behavior they need to change VSFilter too 
ps : VSFilter is dead and devs is gone for good

**Comment by felagund** [comment]
I see.

Anyway, what about extending the horizontal margin of the box/making it configurable? @wm4 ?

**Comment by felagund** [comment]
Any news on this? It seems to me it should not be that hardto override. The colour of the box is taken from the colour of the shadow, so maybe the size of the shadow could determine the margin of the box?

**Comment by felagund** [comment]
Hm, this can be overcome, actually, if it is still a hack. but it is fairly easy to make a script that makes a another subtitle with the same duration, transparent text and semitransparent background, with slightly larger font size and slightly lower vertical margin (in case the alignment is 2, bottom center) one layer below the existing subtitle, which should have no borderstyle set to 0, 1 or 2 (0, that is not borders and no shadow  and no box looks best to me).

In practice, an example would be like this (it just needs to be put in the ass file - a functioning example attached):

Style: text,Arial,57,&H00000000,&H00000000,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,50,50,30,0
Style: transparent_background,Arial,63,&HFFFFFFFF,&H00000000,&H00000000,&H8000FFFF,0,0,0,0,100,100,0,0,4,0,0,2,50,50,27,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 1,0:00:00.00,0:01:32.26,text,,0,0,0,,text\Nsome more text
Dialogue: 0,0:00:00.00,0:01:32.26,transparent_background,,0,0,0,,text\Nsome more text

**Comment by felagund** [comment]
Hm, so it was there all along since version https://github.com/libass/libass/releases/tag/0.13.7 well, somebody could have told me that:-). But closing this since the desired functionality is there.
