### ISSUE TITLE
error: ‘FC_POSTSCRIPT_NAME’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by weitiedan** [libass/libass#269]
I compile in arm_linux,but can't succeed,script,why?

**Comment by grigorig** [comment]
Your fontconfig version is probably outdated. That said, I guess it means we need to update the configure check.

**Comment by astiob** [comment]
I thought I did update the configure check when I introduced the use of PostScript names…

Here: see 018cfe7b2cbbcd10e7860e7903564b5d5a0b1d16.

**Comment by weitiedan** [comment]
I checked the fontconfig version ,it is 2.12.1,but it got the same result ,so I want to know where the FC_POSTSCRIPT_NAME define,can anybody tell me?

**Comment by weitiedan** [comment]
supplement:ass_fontconfig.c: In function ‘scan_fonts’:
ass_fontconfig.c:152:33: error: ‘FC_POSTSCRIPT_NAME’ undeclared (first use in this function)
ass_fontconfig.c:152:33: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [ass_fontconfig.lo] Error 1
make[2]: Leaving directory `/data/tmp/ffmpeg-comoile/ffmpeg-3.2.4/libass-0.13.6/libass'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/tmp/ffmpeg-comoile/ffmpeg-3.2.4/libass-0.13.6'
make: *** [all] Error 2
Making install in libass
make[1]: Entering directory `/data/tmp/ffmpeg-comoile/ffmpeg-3.2.4/libass-0.13.6/libass'
  CC       ass_fontconfig.lo
ass_fontconfig.c: In function ‘scan_fonts’:
ass_fontconfig.c:152:33: error: ‘FC_POSTSCRIPT_NAME’ undeclared (first use in this function)
ass_fontconfig.c:152:33: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [ass_fontconfig.lo] Error 1
make[1]: Leaving directory `/data/tmp/ffmpeg-comoile/ffmpeg-3.2.4/libass-0.13.6/libass'
make: *** [install-recursive] Error 1

**Comment by weitiedan** [comment]
I fixed it ,it's my configure bug,thanks
