### ISSUE TITLE
Improvements to DirectWrite implementation, use of c++?

### ISSUE THREAD

**Issue by Paxxi** [libass/libass#273]
We wanted to use the DirectWrite implementation in Kodi but found that it lacked support for loading custom fonts. We have a working implementation of this at https://github.com/Paxxi/libass/ .

The reason I'm opening this issue is that DirectWrite is quite painful to work with in C and not all of it is accessible that way. Would an implementation using C++ be acceptable for this bit of the project?

Don't worry about the messy code, if it's deemed acceptable I will clean it up before making a PR.

**Comment by feliwir** [comment]
When I started the DirectWrite implementation i got the impression that the majority of the team dislike the idea of C++ in libass. But opinions might have changed

**Comment by astiob** [comment]
Hi, thanks for your interest. Could you tell us a bit more about the features your branch adds? Currently, libass already supports playing MKV files with embedded font files on all platforms including Windows with DirectWrite, as long as the media player uses the appropriate libass APIs for adding the embedded fonts.

As for C++, this was considered when the DirectWrite backend was first introduced, and in fact, the first version of it was written in C++, but the majority opinion was that introducing C++ into our code base was a hassle (source code maintenance aside, it would introduce an extra dependency on a C++ compiler and require maintenance of C++ support in the build system) and that COM and hence DirectWrite was easy enough to work with in C as in C++. So we converted the original C++ version of the backend to C and introduced the `dwrite_c.h` file (based on `dwrite.h` provided by MinGW-w64 if I recall correctly) because Microsoft don’t provide its own C-compatible header for DirectWrite. Is there anything in particular that is too hard or impossible to do in C?

**Comment by wm4** [comment]
I converted the dwrite backend from C++ to C myself, so I reject this idea. I don't even know why you'd want this - C++ is such a ridiculous language, it surely weights over the COM craziness.

**Comment by Paxxi** [comment]
Kodi extracts fonts to disk and gives the path to libass. The version in master didn't work correctly with this, it could only enumerate system fonts and not a user provided path. 

But that makes it clear about c++ we'll continue to carry the patch in a fork then. 

Thanks for the quick responses

**Comment by wm4** [comment]
You should use ass_add_font instead.

> and keeping it up to date.

No, it's part of the system ABI. Complain to Microsoft about the C incompatibility.

**Comment by astiob** [comment]
> Kodi extracts fonts to disk and gives the path to libass. The version in master didn't work correctly with this, it could only enumerate system fonts and not a user provided path.

Are you saying `ass_set_fonts_dir` doesn’t work with DirectWrite? I’d consider that a bug, and it would be good to get it fixed.

Other than that, you really should be using `ass_add_font` for embedded fonts.

> As mentioned Microsoft doesn't provide a C compatible header for it which means maintaining a separate header and keeping it up to date.

We do need to maintain a copy of it, yes, but we already do and it takes absolutely no continuing effort. If the APIs we currently have in `dwrite_c.h` are not enough for this task, we/you need to add the missing ones to the header. I’m sure some of us will be happy to help you with this if necessary. However, the APIs already in the header should continue working forever, as Microsoft keeps backwards compatibility. The C header is equivalent to Microsoft’s C++ header; it’s just that Microsoft’s header contains some C++ syntax that is invalid C.

**Comment by jtanx** [comment]
> As mentioned Microsoft doesn't provide a C compatible header for it which means maintaining a separate header and keeping it up to date.

Wow, I'm surprised they didn't just write and publish the idl instead of writing the C++ specific header.

**Comment by wm4** [comment]
I'm fairly sure Microsoft's and MinGW's headers are generated from IDL and include C compatibility stuff. It just doesn't compile in C. For MinGW we could have fixed this by sending patches to them, but not with Microsoft's. Maybe someone could look whether MinGW's and Microsoft's current headers are still broken, assuming I correctly determined both of them being broken back then.

**Comment by jtanx** [comment]
Microsoft's header is pure C++ only - there's no `__cplusplus` guards and no alternate implementations for C.

I had a quick look at what I had in my SDK, and I don't see any `dwrite.idl` - so if MS is using an IDL to generate the header, I don't think they're providing it, nor are they using `midl` to generate the header, which provides both C and C++ compatibility, like almost everything else COM.

On the internet, I can find some references to `dwrite.idl`, but they appear to be written by some third party, and not by Microsoft.

**Comment by Paxxi** [comment]
@astiob yes that's the issue we ran into and the patch solves. It may also require a utf8 patch to freetype to handle unicode filenames correctly, this can be found at https://github.com/xbmc/freetype in the 2.7 branch. Haven't gotten around to trying to upstream it yet. 

Pointing the fingers at MS no matter how correct doesn't really do anything useful except give off a sense of hostility. 

I expressed myself clumsily, MS won't break the current header but if/when they add DirectWrite2  or 3 as they tend to do in their com versioning it may require work. 

I much prefer C++ over C which is the reason for opening this issue to gage the interest or feasibility. Attacking C++ once again only signals hostility, a simple no was good enough for me. 

If I have time free in the future I may try to write a C version of the patch, otherwise if someone is quicker then feel free to use the current version as a starting point / template, it's tested and used in Kodi 17.1.

**Comment by Paxxi** [comment]
Forgot. I only manage building and porting libraries to Windows, not really the usage of them. I will take it up with the team to use ass_add_font instead, thanks for the hint.

**Comment by grigorig** [comment]
I we use full-featured C++ (e.g. `new`), libass will have a run-time dependency on libstdc++, which can be a source of problems. I personally don't have a strong opinion on C vs. C++, but for a program that is otherwise C only, it seems reasonable to avoid C++ completely.  At the end of the day, what do we win by converting the DirectWrite backend to C++ now? As far as I can see, nothing.

**Comment by wm4** [comment]
> Pointing the fingers at MS no matter how correct doesn't really do anything useful except give off a sense of hostility.

Well, Windows has been traditionally been a pretty hostile environment for open source software originating from Unix in general. This used to have business related reasons, but even these days Windows makes things unnecessarily hard. (See: having to add UTF-8 support for every single C/open source project that accesses the filesystem on Windows.) So I don't think it's much of a surprise if some developers are not exactly enthusiastic about this platform.

> freetype to handle unicode filenames correctly, this can be found at https://github.com/xbmc/freetype in the 2.7 branch.

That link is 404.

**Comment by Paxxi** [comment]
Sorry, should be https://github.com/xbmc/freetype2/tree/utf8_fix

Agreed that it's an annoying situation but it is what it is currently. 

Anyway, this has gone quite sideways, I've gotten the answer to my question and will consider trying to write it in C if time allows.
