### ISSUE TITLE
Fonts which are not the first in a ttc file can't be selected by libass

### ISSUE THREAD

**Issue by mxalbert1996** [libass/libass#275]
If you specify a font which is not the first one in a ttc file, libass will actually select the first font in that ttc file. Tested in ffmpeg and mpv.

Software version: Windows 10 1703, libass git master. Font provider used is DirectWrite.

**Comment by mxalbert1996** [comment]
If you need, I made [a ttc file](https://mega.nz/#!NcVVnbQR!SOtk_oO-uazvOtNubGP6PsNziHPQcO54wNDI1G_inGA) with otf2otc from [AFDKO](https://www.adobe.com/jp/devnet/opentype/afdko.html) combining `Source Sans Pro` and `Noto Sans` (I added `Test` to their names). Install that file, specify `Noto Sans Test` and libass will actually use `Source Sans Pro Test`.

**Comment by grigorig** [comment]
The DirectWrite backend supports font collections. So I'm not sure where that's coming from. But first, let's clear up one thing: are you installing the font system-wide or are you using the font collection as a embedded font, i.e. inside an MKV? Or, the third choice, are you putting the font into a directory that you point libass to?

**Comment by mxalbert1996** [comment]
@grigorig I'm installing the font system-wide.

**Comment by grigorig** [comment]
Can you verify that the font collections that ship with Windows also fail to work? For instance, you should have the "MS Gothic" font collection which contains the faces "MS Gothic", "MS PGothic" and "MS UI Gothic". These should all work.

**Comment by mxalbert1996** [comment]
Tested msgothic.ttc and msmincho.ttc. They have this problem too.

**Comment by grigorig** [comment]
If you are able to do it, please test the referenced patch.

**Comment by mxalbert1996** [comment]
Tested. Thanks for the fix!
