### ISSUE TITLE
Building statically-linked DLL with MinGW-w64

### ISSUE THREAD

**Issue by yhnchang** [libass/libass#277]
**Summary**
Unable to build a statically-linked DLL with MinGW-w64

**Description**
I am trying to build libass into a statically-linked DLL with MinGW-w64. When I configure and make with

`./configure --disable-static --enable-shared`

it generates the dynamically-linked DLL (dependent to libfontconf-1.dll and others) as expected. However, when I attempt to force static linking by setting

`LDFLAGS=-static`

instead of generating a statically-linked shared library (.dll with no dependency), it generates a static library (.a). No error or warning was displayed during the process.

**Steps to Reproduce**
`./configure --disable-static --enable-shared LDFLAGS=-static`
`make`

**Expected Result**
Produce a statically-linked shared library (.DLL) that is not dependent to DLLs from fontconfig, harfbuzz, etc.

**Actual Result**
Produced a statically library (.a)

**Software Version**
- MinGW-w64
- libass 0.13.7
- gcc 6.3.0
- ld 2.28
- libfreetype 2.8-1
- libharfbuzz 1.4.6-2
- libfontconfig 2.12.1-2
- libpng 1.6.29-1

**Comment by pingplug** [comment]
The ld man page writes(-Bstatic/-static):
"This option can be used with -shared.  Doing so means that a shared library is being created but that all of the library's external references must be resolved by pulling in entries from static libraries."

**Comment by jtanx** [comment]
You probably need `-Wl,-static` instead of just `-static`, but then you somehow also need `-Wl,-dynamic` in the right place so that you can link to win32 dlls as needed

**Comment by yhnchang** [comment]
**Update:**
After weeks of trial and error, it turns out that since libass uses autotools to build the libraries, the correct way is to add `-Wc,-static` to LDFLAGS so the `-static` option will be passed down from libtool to gcc in link mode to force static-linking of any dependencies. To avoid gcc check failure during configure, this must be done in `libass/Makefile.am` before configuring.

I'm still having trouble statically linking to harfbuzz and graphite2, but I think it's a MINGW issue so I'll go ahead and close this issue for now. I'll post another update if I ever find a complete solution.

**Comment by wm4** [comment]
Static linking isn't unusual, especially on Windows. But mingw/msys makes this a huge pain. The best approach is probably building your own mingw toolchain, that contains only what you need, and as static dependencies. lachs0r's mpv cmake build script does that for example.
