### ISSUE TITLE
install it in win10

### ISSUE THREAD

**Issue by Phaidonas** [libass/libass#291]
hello, do you know how to install the library for use in win10?I want to use it with libvlc.

**Comment by astiob** [comment]
libass can be built for Windows in MSYS or Cygwin or using the MSVC project at https://github.com/libass/libass-msvc. We don’t provide official prebuilt binaries, but a libass binary alone is useless; if you’re using prebuilt libraries of something that uses libass, ask the builders of that thing to build libass as well.
