### ISSUE TITLE
some problem with subs

### ISSUE THREAD

**Issue by weebo221** [libass/libass#308]
So I started using mpv player and I noticed that something is wrong.
my subs looks normal in MPC-HC https://prnt.sc/jn8v4o
but subs on the bottom are broken in mpv (same problem is with vlc) https://prnt.sc/jn8w1r
Is it possible to fix it?

**Comment by rcombs** [comment]
Post a minimal sample of the script that produces the issue, including all required fonts.

**Comment by weebo221** [comment]
https://www13.zippyshare.com/v/zHo2GWHJ/file.html fond and file with not working lines

**Comment by astiob** [comment]
@MrSmile’s commit 49eb2d2ecdc12d2dcd3af8ca00067cb4161679ff [broke it](https://github.com/libass/libass/commit/49eb2d2ecdc12d2dcd3af8ca00067cb4161679ff#diff-0348e387624211dd40e575fe75ab8596R1087). His commit 856663b2e50017f5ccd5ef284587d8444b0cee38 from #285 fixes it probably by accident, and his commit 926fae558d001ab8bc6d3837c5a6a220754a385b also from #285 fixes this for good.

**Comment by astiob** [comment]
Duplicated by #309, which has a better title and description. Let’s move any further discussion there.
