### ISSUE TITLE
Rendered font weight is affected by MKV attachment order if they have the same style map

### ISSUE THREAD

**Issue by GrygrFlzr** [libass/libass#318]
When variants of the same family are available (e.g. both regular and bold) and the regular has the same OS/2 style map as its bold variant (e.g. both specified regular), the attachment order affects the rendered output. The fullnames are distinct, however, and the OS/2 Weight Class and PostScript weight seem to be assigned correctly. These properties were checked with FontForge.

For example, if the bold font is ordered before the regular font, all weights of that font will be rendered in bold. Since this relies on the attachment order of a muxed mkv, it does not appear in programs like Aegisub, which use the fonts installed on the computer.

xy-vsfilter does not exhibit this behavior and selects the specified font weight regardless of attachment order, which is the main reason for this report. I am not 100% certain that having the same style map between two weights is the cause of the issue, but that is currently my best guess after comparing different fonts.

Sample mkv file with bold-first font order is available [here](https://puu.sh/BQMMb/01858bbdc6.mkv) (914KB)
Sample mkv file with bold-last font order is available [here](https://puu.sh/BQMMD/9742a89ab1.mkv) (914KB)

---
Fonts [from this GitHub repo](https://github.com/supermarin/YosemiteSanFranciscoFont) were used.
The video was generated using ffmpeg: `.\ffmpeg -t 10 -f lavfi -i color=c=black:s=1280x720 -c:v libx264 -tune stillimage -pix_fmt yuv420p output.mp4`
The following subtitles were used:
`{\an2\pos(640,360)\fs70\fnSFNS Display\b1}(Bolded)\NThe quick brown fox jumps over the lazy dog`
`{\an8\pos(640,360)\fs70\fnSFNS Display\b0}The quick brown fox jumps over the lazy dog\N(Regular)`
The mkv file was generated using MKVToolnixGUI. Fonts were attached in the following order for the bold-first file:
1. System San Francisco Display Bold (aka `.HELVETICANEUEDESKINTERFACE-BOLD.TTF`)
2. System San Francisco Display Regular (aka `.HELVETICANEUEDESKINTERFACE-REGULAR.TTF`)

And vice versa for the bold-last file.
I have not yet found another font to display the issue with, unfortunately, and I'm aware the repo itself warns against using it as a non-system font.

---
Expected render (xy-vsfilter, and libass with bold-last font order)
![image](https://user-images.githubusercontent.com/1460917/47508987-22059600-d843-11e8-8534-c2f01a062dd9.png)
Current render (libass with bold-first font order)
![image](https://user-images.githubusercontent.com/1460917/47508650-7eb48100-d842-11e8-8ea4-976f25b30f9c.png)

**Comment by GrygrFlzr** [comment]
I *think* #43 is either related or the same issue, but I do not have the Carnival Phantasm release on-hand to check with.

**Comment by TheOneric** [comment]
The links to your mkv samples are dead. I guess `SFNS Display` was used as the fontname ?
I tried to recreate the MKVs with this subs:
```
﻿[Script Info]
; Script generated by Aegisub 3.3.1
; http://www.aegisub.org/
YCbCr Matrix: TV.709
PlayResX: 1280
PlayResY: 720

[Aegisub Project Garbage]
Video File: output.mp4
Video AR Mode: 4
Video AR Value: 1.777778

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,SFNS Display,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,, {\an2\pos(640,360)\fs70\fnSFNS Display\b1}(Bolded)\NThe quick brown fox jumps over the lazy dog
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,, {\an8\pos(640,360)\fs70\fnSFNS Display\b0}The quick brown fox jumps over the lazy dog\N(Regular)
```

The result was that for bold-first all lines used the bold font and with regular-first all lines used the regular font but with what I guess to be **faux-bold** for \b1.
```
[ass] fontselect: (SFNS Display, 400, 0) -> .HelveticaNeueDeskInterface-Regular, 0, .HelveticaNeueDeskInterface-Regular
[ass] fontselect: (SFNS Display, 700, 0) -> .HelveticaNeueDeskInterface-Regular, 0, .HelveticaNeueDeskInterface-Regular
```
If you compare the screenshots you posted one can also see, that the "bold" in regular-first /xy-vsfilter is actually less bold than the bold font in bold-first. In my case this was even more visible.

Do VSFilter and libass really produce the same (faux-bold) output for you in the regular-first case, or does VSFilter use the real bold font ?

**Comment by GrygrFlzr** [comment]
It seems that in the 18 months that have passed, the latest mpv already has libass updates this fix the problem, so I'll close the issue.

For those curious to observe the issue on older builds, I've reuploaded the test cases onto a more permanent link:
- Bold first: https://drive.google.com/open?id=1vatq95YSodu_yZCaZ21-TSKZiFstoPu6
- Regular first: https://drive.google.com/open?id=1yzNwIy9vpAFXlBd01xpPJIq0Kziao6Xx
