### ISSUE TITLE
Stroker issue demonstrated by "Abegnale" font

### ISSUE THREAD

**Issue by rcombs** [libass/libass#326]
Font: https://www.dafont.com/abegnale.font
VSFilter vs libass: http://screenshotcomparison.com/comparison/127461
libass with different borders set: http://screenshotcomparison.com/comparison/127462

![image](https://user-images.githubusercontent.com/819638/50992666-c663b400-14e5-11e9-982c-d87a6b5f8c2c.png)

Looks like we're stroking a few points, but not most of the glyph; not sure what's going on here. Probably one for @MrSmile to look at?

**Comment by knopp** [comment]
I'm not sure this is completely fixed. I'm getting the following with freetype/harfbuzz and thai subtitles:

<img width="691" alt="Screen Shot 2019-05-17 at 22 50 31" src="https://user-images.githubusercontent.com/96958/57955563-8d55a900-78f6-11e9-896a-81591791abca.png">

Subtitle in question:
[Pulp-Fiction.1994.th.utf8.ass.zip](https://github.com/libass/libass/files/3193062/Pulp-Fiction.1994.th.utf8.ass.zip)

Rendered with Arial, but happens with every font.

**Comment by astiob** [comment]
@knopp Could you recheck with a recent libass build? I can’t reproduce this, but since Arial doesn’t actually contain Thai and is substituted for another font, I can’t be sure I’m seeing the same font as you were.

For reference, the exact phrase from the screenshot occurs at 0:22:40 into the subtitle file.

**Comment by MrSmile** [comment]
Anyway, that's clearly not a stroker issue, it's something shaper-related. Should be moved into a separate issue if the problem still exists.
