### ISSUE TITLE
cc: libass API implementation for xy-VSFilter (xySubfilter) 

### ISSUE THREAD

**Issue by jesec** [libass/libass#332]
https://github.com/Cyberbeing/xy-VSFilter/pull/16

Solves https://github.com/libass/libass/issues/106.

It is quite stable at the moment. I have not noticed any issue yet.

I opened this issue to have some discussions about the idea itself and request code review from the API provider. It will be greatly appreciated if you can make some comments or review this implementation.

Thank you. 

Some of my points about this (#328):
> > I am working to bring libass to xy-VSFilter.
> 
> 
> To be honest, I’m not a fan of this idea. But if this gains traction, best of luck to you!
> What’s wrong with using/improving AssFilterMod? Bringing libass into xy-VSFilter seems _weird_ for starters, but more practically I think this will reduce competition, as much as xy-VSFilter may be “dead”, and be a significant blow on compatibility with existing scripts that I’ve mentioned above. (Especially Arabic or Hebrew scripts. Seriously, Arabic and Hebrew users are gonna hate this. I’d love to fix that in libass though. But I’ve wanted to do it for _years_ and unfortunately it will most likely take more _years_ before it will finally be done. And even beside that, we still have some noticeable incompatibilities. I will hopefully keep fixing them in libass though, even if slowly.)

AssFilterMod is just too feature incomplete. It does not support many subtitle formats. It also lacks "Open external subtitle files", multiple pin handling, pin selection, etc.

Most importantly, some very prominent video players such as MPC-HC, Kodi DSPlayer which are not being updated anymore but still used by **many** people **hardcoded** UUID of xy-VSFilter, XySubfilter into a table. There are some crappy behaviors like forcibly remove all subtitle renderers not in the table from the graph. When I try AssFilterMod, I basically **HAVE** to make it impersonate XySubfilter in order to get it loaded in MPC-BE, Kodi DSPlayer and some other player.

It is also important to note that APIs of xy-VSFilter are widely used and embedded into many players. Some players require those to hook functions like see available subs, subtitle selection into their own UI. Or open external subtitle file (player instructs subtitle renderer to open a specific file).

And, [Cyberbeing/xy-VSFilter#15 (comment)](https://github.com/Cyberbeing/xy-VSFilter/pull/15#issuecomment-462105921):
XySubfilter(or VSFilter in general)'s support for other subtitle formats (srt, pgs) and specification for those formats is very matured today IMO. So I would like to stay with XySubfilter for those formats.

Reusing xy-VSFilter's matured functions like input pin handing, subtitle selection, etc. greatly reduces efforts and make it much easier for users to switch over to libass (or I say upgrade).

> With regard to speed, isn’t VSFilter still faster than libass due to DirectShow and madVR prebuffering rendered frames in advance? But I guess this speedup would benefit libass-in-VSFilter as well.

Not the case anymore.
You guys DID great works here. Thank you.

**Comment by Restia666Ashdoll** [comment]
@jesec What happened to this project ?
