### ISSUE TITLE
transforms with clips do not work

### ISSUE THREAD

**Issue by neonew91** [libass/libass#336]
I try to use \iclip feature in ASS with ffmpeg to display the subtitles one by one.
`{\pos(717,91)\iclip(717,91,1000,191)\t(0,1000,\iclip(1000,91,1000,191))}Hello World!`
However, it doesn't work. The version of ffmpeg is 4.1.1.
Does ffmpeg support clip feature in ass?

**Comment by astiob** [comment]
It should work. Does the same ASS script work in other software?

**Comment by neonew91** [comment]
> It should work. Does the same ASS script work in other software?

Yes，it works. I made a mistake to use text alignment in Default style.
thx!
