### ISSUE TITLE
VC++ does not allow local array declared with `const int` length

### ISSUE THREAD

**Issue by hozuki** [libass/libass#338]
I'm compiling libass using Visual C++. VC++ does not allow this kind of array declaration:

```c
const int array_len = 5;
int array[array_len];
```

Therefore it throws out compilation error at several locations:

- `ass_outline.c`: [1](https://github.com/libass/libass/blob/fa49852cd7fbab79653e62e1e52cedeb33a536ea/libass/assoutline.c#L521) [2](https://github.com/libass/libass/blob/fa49852cd7fbab79653e62e1e52cedeb33a536ea/libass/ass_outline.c#L557)
- `ass_render.c`: [1](https://github.com/libass/libass/blob/fa49852cd7fbab79653e62e1e52cedeb33a536ea/libass/ass_render.c#L1238)

The version I'm using is VC++ 14.1 (2017).

I haven't read the full source code in the repo yet. Those examples are in the files that needs to compile. BTW version 0.13.7 does not raise compilation errors, as those lines were added after its release.

IMHO this issue can be resolved by using integer literal (better with comments), or `#define` then `#undef`. Both solutions have disadvantage(s) but the choice is up to the devs here.

**Comment by CoffeeFlux** [comment]
This is a known issue and resolved in multiple outstanding PRs. Unfortunately, until one of those gets merged, you'll have to patch downstream.

**Comment by hozuki** [comment]
Oh thanks. I found it in #321. I didn't check PRs. 😞

**Comment by CoffeeFlux** [comment]
It's also covered with #285, which is where it's more likely to be merged. Probably should've had an issue opened from the start though, so it works out!
