### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by vtorri** [libass/libass#341]
hello

last release was in 2017. Do you plan to make a new release soon ?

thank you

**Comment by CoffeeFlux** [comment]
I expect one won't happen until some of the major open prs are merged, which still need a final review.

**Comment by kloczek** [comment]
I think that it would be good to flush all current changes and make minor release like 0.14.1 :)

**Comment by vtorri** [comment]
there is not a lot of activity on master this year, so i fear it will not happen soon

**Comment by shabahengam** [comment]
Is there any plan for the next release? at least a minor release?

**Comment by astiob** [comment]
Yes. I’ve marked some issues/PRs with milestone 1.15.0 as a first approximation of what I’d like to see merged or explicitly postponed before the next release. Some of them were blockers, but IIRC all true blockers have already been merged; so if that takes too much time, we should make a release as-is.

(Other maintainers: feel free to reassign the milestone as you see fit.)

**Comment by anthraxx** [comment]
@astiob @rcombs @MrSmile can we please get a release out? :cat: Or at the very least, maybe indeed create a 1.14.1 that has a backport for the security fixes known, one which comes to mind is #431 
It would be great to be able to roll out a officially supported version that has named mitigation present.

**Comment by astiob** [comment]
I’d like to make a release this week or next week at the latest.

The current plan is to **require HarfBuzz for the build to succeed.** A bare-bones HarfBuzz is enough (hb-ft won’t be required, nor any other optional features). If there are any package maintaners in this thread, please speak up now if this is not acceptable. We can delay this change for one release if it’s too much trouble at the moment.

**Comment by sebastinas** [comment]
That won't be a problem for Debian. We already build it there with HarfBuzz for quiet some time.

**Comment by hyder365** [comment]
> I’d like to make a release this week or next week at the latest.

Any update?

**Comment by astiob** [comment]
Release 0.15.0 has been published!
