### ISSUE TITLE
feature request: add support for reverse italics

### ISSUE THREAD

**Issue by daT4v1s** [libass/libass#346]
reverse italics to indicate
- irony, sarcasm, or negation,

in contrast to normal italics which usually indicate _emphasis_

currently workaround is tedious, using a combination of 
- `{\fax0.185}` & `{\fax}` (calibrate to `{\i1}` )
- `{\fsp-2.0}` one character before start, `{\fsp}` @ start
- `{\fsp-2.0}` one character before end, `{\fsp}` @ end

**Comment by rcombs** [comment]
I'd suggest creating an Aegisub script to handle this kind of thing; we generally don't add new tags like this without buy-in from other implementations, and I don't force that happening since this is already doable with fairly simple tags.
