### ISSUE TITLE
Feature request: Text Blend Mode (using a \blend tag, maybe?)

### ISSUE THREAD

**Issue by SparkYaro** [libass/libass#347]
_(I'm talking about Aegisub here because it's the program I'm using which
 contains libass)_

I'm sorry if this feature was already implemented, but after several years working with Aegisub I haven't found a working "blend mode" for my subtitles when I needed it.
I think it could be very handy in the next releases, with the `\blend` tag.
Example of an Aegisub line: `{\blend Difference} Text on a flower`
Showing a picture for reference!
![Blend modes](https://user-images.githubusercontent.com/42842135/60128724-9f4b2700-9793-11e9-8a52-ab2ed81a33d7.png)

**Comment by wm4** [comment]
i believe that's not possible fore technical reasons. The only blending it can do is alpha blending, not xor for which you seem to be asking.

**Comment by TheOneric** [comment]
As mentioned above, this isn't possible to do at render-time, as libass doesn't know about the videocolours.

Such an effect can be achieved at authoring-time by having two versions of the text and utilising `\clip`/`\iclip` tags. *(although this is probably only practical to do in simple cases as the one above and not eg when smooth colour gradients are present in the videoimage)*
