### ISSUE TITLE
FFmpeg keeps waiting when add ass file.

### ISSUE THREAD

**Issue by lynkas** [libass/libass#350]
`
[h264 @ 0x557418531780] [debug] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 1

[Parsed_ass_0 @ 0x5574191e9a40] [debug] Setting 'filename' to value '1.ass'

[Parsed_ass_0 @ 0x5574191e9a40] [verbose] Raster: FreeType 2.6.1

[Parsed_ass_0 @ 0x5574191e9a40] [info] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.0.1 (COMPLEX)

[Parsed_ass_0 @ 0x5574191e9a40] [verbose] Initialized
`
And the program paused here. I have tried reboot, fc-cache -fv, reinstall and update ffmpeg. The ass file from neither aegisub nor ffmpeg(generated from mkv file) worked.
It is ubuntu 16.04.

**Comment by astiob** [comment]
Can you post the ASS file?If you know how to use a debugger such as gdb, can you run ffmpeg in the debugger, interrupt it when it seems to have hanged, and capture the stack trace?

**Comment by lynkas** [comment]
> Can you post the ASS file?If you know how to use a debugger such as gdb, can you run ffmpeg in the debugger, interrupt it when it seems to have hanged, and capture the stack trace?

Thanks and the problem seems solved. I manually replaced ffmpeg binary in /usr/bin to version 4.1.4 static.
Something happened before this issue was I tried to update font cache (fc-cache -fv) and it was interrupted by myself cuz extremely slow without any output. 

Although the case was solved in the new version, the old one was still not working after font cache rebuilt. The ass file was normal, such as converted from srt by ffmpeg. Here is one example:
`[Script Info]
; Script generated by FFmpeg/Lavc58.35.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.47,0:00:03.01,Default,,0,0,0,,{\b1} {\b0}{\b1}{\i1}- ♪ Crashing through{\i0}{\b0}\N{\b1} {\b0}{\b1}{\i1}The crowded halls ♪{\i0}{\b0}
Dialogue: 0,0:00:03.07,0:00:04.74,Default,,0,0,0,,{\b1} {\b0}{\b1}{\i1}♪ Dodging girls like{\i0}{\b0}\N{\b1} {\b0}{\b1}{\i1}Ping-pong balls ♪{\i0}{\b0}
Dialogue: 0,0:00:04.81,0:00:06.35,Default,,0,0,0,,{\b1} {\b0}{\b1}{\i1}♪ Just to reach{\i0}{\b0}\N{\b1} {\b0}{\b1}{\i1}The bathroom on time ♪{\i0}{\b0}
Dialogue: 0,0:00:06.41,0:00:07.88,Default,,0,0,0,,{\b1} {\b0}{\b1}{\i1}♪ Leaping over{\i0}{\b0}\N{\b1} {\b0}{\b1}{\i1}Laundry piles ♪{\i0}{\b0}`

This file did not work on previous version. Now the old one was removed and I might cannot simply downgrade the installation (The thing even worse is i'm using ffmpeg now and will keep using for a long while). I will give a try as your guidance while free and give feedback to you. Thanks for the help.
