### ISSUE TITLE
harfbuzz 2.3.1 text rendering regression

### ISSUE THREAD

**Issue by CoffeeFlux** [libass/libass#352]
This was originally observed a while back in an mpv nightly build. Sorry for not opening an issue until now, but I only recently found out and hopefully this will make it easier to track.

It seems that with harfbuzz 2.3.1, text rendering now differs significantly from VSFilter. Adobe Ilustrator actually agrees with the newer output, so it's quite possible that this is now "correct" behavior from harfbuzz but incorrect for our purposes, as it's a significant deviation from VSFilter. I'm unsure of what exactly about the font causes this or exact which commit introduced the change, but @line0 is bisecting and can hopefully post more information when available.

VSFilter, mpv stable output: https://cdn.discordapp.com/attachments/425357202963038208/619713185322369024/unknown.png
mpv nightly output: https://cdn.discordapp.com/attachments/425357202963038208/619713212387950623/unknown.png
Test files: https://cdn.discordapp.com/attachments/425357202963038208/619713289936437249/bugtest.ass https://cdn.discordapp.com/attachments/425357202963038208/619713285427691536/MerahbBush.ttf

**Comment by astiob** [comment]
Looks like a different font size to me, rather than different shaping. Could this perhaps be caused by our own #327 rather than a change in HarfBuzz?

**Comment by CoffeeFlux** [comment]
This was originally reported to me on 2019/09/06, which predates that commit being merged, and I believe it was originally noticed even before that. I only got wind of it because I was updating the dependencies in Aegisub and someone thought to mention it...

**Comment by astiob** [comment]
Any news on the bisection?

**Comment by CoffeeFlux** [comment]
Not sure l0 ever finished it. I won't be able to do it myself for the next couple of weeks due to travel, but I do think this is important enough to block a new stable :\

**Comment by rcombs** [comment]
Duplicated in #361, where we discovered this is actually due to a freetype change. Let's move over to that one.
