### ISSUE TITLE
Karaoke effects \k and \kf are lagging/desynced

### ISSUE THREAD

**Issue by AxelTerizaki** [libass/libass#357]
I posted this originally on mpv-player/mpv#7121 but they told me I should post it here as well, since it seems to be an upstream issue with libass.

As the title says, \kf and \k effects are slightly desynced, making karaoke less enjoyable :)

I'll copy-paste the issue, since it contains example files, and captures. 

This happens with mpv 0.30, but not with mpv 0.29, which I suppose do not use the same libass (but I have no idea which version they do use, maybe someone from mpv can tell us here.)

### Reproduction steps

Load the sample files listed below and see for yourself how the karaoke subs are desynced.

### Expected behavior

Captured using mpv 0.29 : 

https://cdn.discordapp.com/attachments/324208228680466434/640862388169736219/2019-11-04_11-36-40.mp4

### Actual behavior

Captured using mpv 0.30

https://cdn.discordapp.com/attachments/324208228680466434/640858951549714432/2019-11-04_11-22-27.mp4

As you can see the subtitles effect \k / \kf aren't synced properly anymore, as if there was some kind of lag.

### Log file

Here is a mpv log (not sure if this is relevant here for libass, but I'm keeping it just in case) : 

https://pastebin.com/AmzdQrbr

### Sample files

- Video : https://kara.moe/downloads/medias/ENG%20-%20Dokidoki!%20PreCure%20-%20OP%20-%20Glitter%20Force%20Doki%20Doki%20Theme%20Song.mp4
- Subfile : https://kara.moe/downloads/lyrics/ENG%20-%20Dokidoki!%20PreCure%20-%20OP%20-%20Glitter%20Force%20Doki%20Doki%20Theme%20Song.ass

Thanks in advance for your help!

**Comment by wm4** [comment]
Here's a better description of the bug: https://github.com/mpv-player/mpv/issues/7121#issuecomment-549511652

**Comment by Akemi** [comment]
bisected this problem.
last working commit: https://github.com/libass/libass/commit/0f0068b0ae5b0bad8472d4a2af6d10e97f982bfc
first broken commit: https://github.com/libass/libass/commit/d3286d8a5e3a0186457b8596c2809866fa59d052

**Comment by Akemi** [comment]
also #343 fixes this issue.

**Comment by AxelTerizaki** [comment]
Just a heads up since I had a case of someone running mpv 0.32 on macOS and reporting no issue at all on \kf tags, while users on Windows still experience the problem on mpv 0.32. Dunno if these two versions are linked against different libass versions though.
