### ISSUE TITLE
font selection for emoji and special symbols will crash on macOS

### ISSUE THREAD

**Issue by LIznzn** [libass/libass#358]
This problem may be caused by CoreText.framework which is libass's default font selection backends on macOS. 

For example, “❤” (U+2764) in chinese ass subtitle can cause crash.

**Log file**
Crash.log https://0x0.st/zgfy.log
mpv.log https://0x0.st/zgfx.log

**Sample files**
sample.ass https://0x0.st/zgfv.ass

**Reference**
https://github.com/mpv-player/mpv/issues/7123
https://github.com/iina/iina/pull/2638 
https://github.com/iina/iina/issues/1101

**Comment by Akemi** [comment]
i just tested the ass file and the current libass master and i can't reproduce that crash.

**Comment by ePirat** [comment]
I can reproduce the issue on 10.15.1, so it seems to be related to macOS 10.15.

**Comment by ePirat** [comment]
I've debugged this issue and it turns out that it happens when `get_font_file` in `ass_coretext.c` is called with a special System font:

```
<CTFontDescriptor: 0x10f254380>{attributes = {
    NSFontNameAttribute = ".AppleSymbolsFB";
}>}
```

Calling `CTFontDescriptorCopyAttribute(fontd, kCTFontURLAttribute);` with such a font returns `NULL`, libass does not check for this and blindly calls `CFURLCopyFileSystemPath`, in this case with `NULL` which crashes.

**Comment by Akemi** [comment]
i know it's a bit pedantic but it begs the question, if there's no font found it will simply not show the char at all, though previously (10.14) it could find a proper font and show it. do we need a better fallback mechanism?

**Comment by astiob** [comment]
Doesn’t that mean there is in fact no font it can use? How does this .AppleSymbolsFB font work? Has Apple removed other emoji fonts from 10.15? (Are you even sure libass no longer displays it, since you said you’re on 10.14? Maybe it’s actually falling back to a suitable font now.)

**Comment by Akemi** [comment]
when i talked to @ePirat yesterday he showed me a screenshot of the fix and the heart was only shown as a rectangle. different vid same sub file and event.
10.15 with fix: https://0x0.st/zg6R.png
10.14 without fix: https://0x0.st/zg67.jpg

one has to debug what is actually picked on 10.14 to give a definite answer. fact is, on 10.14 it picks  a font that works but doesn't on 10.15. i find it very unlikely that no font on 10.15 would work. vlc (with srt) falls back to a working font on 10.15 according to @ePirat, so there definitely is a way to properly show it.

**Comment by wm4** [comment]
I assume "vlc with srt" refers to their internal text renderer, without libass?

**Comment by Akemi** [comment]
i assume so, probably what's in `vlc/modules/text_renderer`.

**Comment by ePirat** [comment]
Yes, it seems that the fallback handling done in libass is different from what we do in VLC, so it should definitely be possible to handle fallback in a better way. I might be able to have time to look into what libass is doing different here compared to VLC on the weekend.

**Comment by rcombs** [comment]
On 10.14 I end up with ZapfDingbatsITC instead .AppleSymbolsFB as the fallback for that character. @ePirat, on 10.15, could you break in `get_fallback` and `po fb` after the `CTFontCreateForString` call, then `po CTFontCopyFontDescriptor(fb)`, then `po CTFontCopyAttribute(fb, kCTFontURLAttribute)`, then `po CTFontDescriptorCopyAttribute(CTFontCopyFontDescriptor(fb), kCTFontURLAttribute)`?
