### ISSUE TITLE
Occasionally, subtitle not bottom aligned, but with a extra vertical offset (up) instead

### ISSUE THREAD

**Issue by daT4v1s** [libass/libass#363]
application: mpv , font-hinting turned on (full)
OS : linux

it might not yet be suitable for me to share the subtitle file in full yet,

but for complex subtitles, (thousands of events),
some with complex formatting, and line-breaks
and some long enough for auto-line breaks, 

suddenly one of the subtitles forget positioning and popups into center
for no apparent reason, and slightly/subtle tweaking the formatting,
it also goes away , (perhaps fragile?), 
the changes don't seem(?) to ought to directly/visibly affect the spacing

possibilities
- maybe similar to when subtitle with a timing collision causes one to displace another
it does not seem to be perfectly centered aligned, maybe a bit lower

it does not only happen for one font

some of the subtitle use multiple layers (time collisions), and various styles, bold, underline toggle, font color (text, outline and shadow), 

this happened for more than one subtitle, but for a few select <5% of the lines

whether or not to do fuzzing

any clue to what might be the cause of this?

**edit:**
much of them seem to be 0.01 second timing collisions, 
anyway to gracefully smooth them out
semi-automatically?

not urgent for you to __,
otherwise have to manually, 
also coding this might be a PITA...   :/

**Comment by MadokaAyukawa** [comment]
The TPP in Aegisub fixes overlaps which are caused by the timer of the subtitles.

**Comment by wm4** [comment]
``--sub-fix-timing=yes`` probably achieves the same (but depends on the subtitle format).
