### ISSUE TITLE
Font size isn't set when there is no font

### ISSUE THREAD

**Issue by rcombs** [libass/libass#365]
See here: https://github.com/libass/libass/blob/5f6de4cc9f572e41c96a308fab86a3a3e769acbe/libass/ass_parse.c#L407-L408
We only actually handle `\fs` when a font is actually loaded. This is almost always the case, but there are some edge cases where it might not be (including a windows bug Period's going to file shortly). This means that if there's no font loaded from the style, `{\fn[name]\fs[size]}` does what you'd expect, but `{\fs[size]\fn[name]}` gives the new font at the old size.

I'm not sure if there's any particular reason for this? The content of the `change_font_size` function is trivial: https://github.com/libass/libass/blob/5f6de4cc9f572e41c96a308fab86a3a3e769acbe/libass/ass_parse.c#L94-L97
I'm not sure why it's still its own function at all? Seems like it could easily just be done directly, like with most other tags.
This is the only other caller, which seems to do nothing at all (it's setting `render_priv->state.font_size` to itself):
https://github.com/libass/libass/blob/5f6de4cc9f572e41c96a308fab86a3a3e769acbe/libass/ass_parse.c#L133-L134

I'll make a simple PR to fix this shortly; just wanted the issue documented first.

**Comment by JustaPeriod** [comment]
The windows bug rcombs mentions is actually an aegisub bug referenced in https://github.com/TypesettingTools/Aegisub/issues/59 and lead to the discovery of this issue.

**Comment by astiob** [comment]
OK, this seems to be an artefact left by the refactoring in commit f905a38536ad32f7a68ab86db736495fc06810b2:

* Before that commit, glyph outline generation was done in the parsing loop and `change_font_size`, called from the parser, updated relevant FreeType faces immediately. _Presumably_ to guard against trying to update faces that failed to be created, calls to `change_font_size` were conditioned on `render_priv->state.font`.

* After that commit, the main loop was split in two, and the FreeType face update was removed from the parsing loop and therefore from `change_font_size` and moved directly into the new second loop in `ass_render.c`. I can’t tell why the code clamping the size to “reasonable” limits (side note: I’m not sure they agree with VSFilter/GDI) was moved as well (as `ensure_font_size`)—it seems it could equally well have been left in `change_font_size`—but this left `change_font_size` with the trivial code we see today.
