### ISSUE TITLE
 How to achieve this effect? Is ass OK?

### ISSUE THREAD

**Issue by chenyangxx** [libass/libass#368]
[https://b23.tv/av83517821](https://b23.tv/av83517821)   How to achieve this effect? Is ass OK?

**Comment by astiob** [comment]
It’s not something you’d enjoy writing by hand, but it seems entirely possible (with a script in Aegisub or so to help you automate the ASS generation). The treble symbol is just two layers (foreground and shadow) with rotation and movement, while for the compressing text you probably need to have two layers per syllable, one white, at normal height, with the current syllable hidden (fully transparent), and the other blue, with animated `\fscy`, and with everything _other_ than the current syllable hidden.

**Comment by chenyangxx** [comment]
> It’s not something you’d enjoy writing by hand, but it seems entirely possible (with a script in Aegisub or so to help you automate the ASS generation). The treble symbol is just two layers (foreground and shadow) with rotation and movement, while for the compressing text you probably need to have two layers per syllable, one white, at normal height, with the current syllable hidden (fully transparent), and the other blue, with animated `\fscy`, and with everything _other_ than the current syllable hidden.
> 
> That said, this is not the best place to discuss how to create visual effects in ASS. You might find fansubbing groups’ IRC channels etc. more useful. IIRC there was a group-agnostic channel on Rizon, but I may be misremembering (or it might be dead).

I mean: Does libass support rendering ass files that directly introduce pictures such as png or jpg?

**Comment by astiob** [comment]
No, libass (nor VSFilter) doesn’t support raster graphics such as PNG or JPEG. But what I saw in your video doesn’t need them: you can use plain text with suitable fonts (𝄞, ❤︎︎, ⚽︎︎) or ASS vector graphics.

In cases when raster graphics is really needed in ASS (mainly when colour is not constant, e. g. in gradients or full-colour images), what people do is split the image into pixel rows or columns or even individual pixels and render each of them separately.

**Comment by wm4** [comment]
I think this can be closed. No bug/feature request, all questions answered, all discussion finished,
