### ISSUE TITLE
Effects documentation

### ISSUE THREAD

**Issue by ctataryn** [libass/libass#377]
In reading through a few subtitles files I found one where the subtitles had `fx` used in the Effects field. According to the [ASS-spec](http://moodub.free.fr/video/ass-specs.doc), I don't see `fx` listed as a valid Effect.

> Dialogue: 0,0:00:00.79,0:00:03.03,Default,,0,0,0,**fx**,{\k90\fad(300,200)}{\k21}How{\k24}come {\k69}it

Can anyone shed light on this? Is it used as a place holder and is essentially ignored in this case?

**Comment by astiob** [comment]
You got that right. It’s not a valid Effect, so it’s ignored on playback; but I think (although I may be mistaken) some Aegisub scripts look at this field to determine which Dialogue lines to process.
