### ISSUE TITLE
fontName not  effective on iOS

### ISSUE THREAD

**Issue by chenyangxx** [libass/libass#380]
I have to package fonts into projects to be effective, but fonts downloaded from the Internet to sandbox are not

**Comment by TheOneric** [comment]
Fonts can either be loaded directly from memory (e.g. attached to mkv or embedded into the ASS-file itself), from a designated font folder libass was told about with `ass_set_fonts_dir` or queried from the system fonts. For the latter we do support CoreText among others, and according to [this page](https://developer.apple.com/documentation/coretext) CoreText is available on  iOS 3.2+ and iPadOS 3.2+.
If there is an issue with a particular font not loading or so, please attach this font and give a clear and detailed description of how you tried to use it. If that's the case this issue can be reopened.
