### ISSUE TITLE
add SubtitlesOctopus and vidcoder

### ISSUE THREAD

**Issue by realfinder** [libass/libass#383]
both https://github.com/weizhenye/ASS and https://github.com/Dador/JavascriptSubtitlesOctopus to https://github.com/libass/libass#other-assssa-implementations

and https://vidcoder.net/ to https://github.com/libass/libass#related-links

**Comment by astiob** [comment]
Do you still want VidCoder to be added? It seems to be an alternate GUI for HandBrake, which is present in the list.
