### ISSUE TITLE
Setting \1a&HFF& without \shad0 or \4a&HFF& results in fill still being visible

### ISSUE THREAD

**Issue by sheik124** [libass/libass#387]
White text outline, black fill, black 3 pixel shadow in the style in question.

Trying to do a fill effect with a \1a&HFF& override and then a \t(1610,1694,\1a&H00&) animation. I kept seeing black fill inside the text, even with \shad0.1, which is definitely small enough not to entirely fill the text.

I tried adding \shad0 and then the fill disappeared. Adding \4a&HFF& also works.

xysubfilter and vssubfilter both render it properly without it, with the small 3 pixel shadow only existing around the outline, including inside the fill area.

**Comment by sheik124** [comment]
Looks like it might be the way it renders shadows???

I tried another layer to see if I could maybe recreate the desired effect by manually compositing it myself.

\1a&HFF&\3a&HFF&\4c&H000000&\4a&H00& gives me no shadow whatsoever in XySubFilter and VS. Because there's technically nothing to draw a shadow for. libass gives a big black mask that includes the fill area and the entire outline area. The other two actually draw shadows around whatever is visible.

**Comment by rcombs** [comment]
Is this fixed in https://github.com/libass/libass/pull/371?

**Comment by sheik124** [comment]
> Is this fixed in #371?

#322 and #371 appear to be similar issues, if not identical. Sorry if I goofed by creating a new one.

> \1a&HFF&\3a&HFF&\4c&H000000&\4a&H00& gives me no shadow whatsoever in XySubFilter and VS. Because there's technically nothing to draw a shadow for. libass gives a big black mask that includes the fill area and the entire outline area. The other two actually draw shadows around whatever is visible.

That's the big take away for me lol. That is *not* a shadow. That's a mask. Not sure how it works from a technical standpoint, but from a practical standpoint, I would assume you expect shadows to form only for whatever is visible. It's impossible for libass to actually render an outline, with no fill, with only the outline casting a shadow, and in a single line.

I just thought of another kludgy work around (for now) after ditching shadows from the entire file I was working on temporarily: not to actually use shadows at all. Just render a second copy of the line with the intended 4c as its 3c color, pos offset by whatever amount of pixels I wanted the shadow to be, and underneath it. \1a&HFF&\4a&HFF& would still have to be set for both. I just tried it and libass *now* looks the way XySub/VSSub normally do with only \1a&HFF& and only a single line.

This doesn't solve all issues, I guess, because I can think of a few cases where even this will not work. XySub doesn't usually draw shadows on the same pixel as fill, whether it's outline, or primary/secondary fill. So even with this workaround, you end up running into the original problem again whenever any of your alpha values aren't &H00& - you can see the shadow through something that you should never be able to, because it shouldn't be there.

**Comment by astiob** [comment]
VSFilter (including XySubFilter) absolutely does draw the shadow in pixels under the fill for all alphas except \1a&HFF. FF is an exception (which libass is currently missing).

**Comment by sheik124** [comment]
> 
> VSFilter (including XySubFilter) absolutely does draw the shadow in pixels under the fill for all alphas except \1a&HFF. FF is an exception (which libass is currently missing).

Sorry, that's what I meant!

Setting e.g. {\3a&HFF&} in either of them does show shadow fill underneath the transparent border.

**Comment by rcombs** [comment]
Fixed in 12cf524b831289cf67ba3432264fa01a69c3bbb5.
