### ISSUE TITLE
libass with ffmpeg font folder path

### ISSUE THREAD

**Issue by anoosi** [libass/libass#389]
hi
i compile ffmpeg with libass + harfbuzz
when I do the encoding video with ass file
libass only takes fonts from the default windows fonts location automatically 
i just want a way to have libass take fonts from a path I am setting without the libass taking fonts from the default path for windows fonts..

any idea

**Comment by astiob** [comment]
Use the `fontsdir` option as described in [FFmpeg filters documentation](https://ffmpeg.org/ffmpeg-filters.html#subtitles-1).
