### ISSUE TITLE
Documentation: Libass' Extensions and Differences from VSFilter

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#401]
Imho there should be some documentation on libass' ASS-extensions and (non-bug) deviations from VSFilter.

Both would help sub authors to write portable subs by pointing out what to look out for — or help authors to make use of extensions, if the incompatibilities seem minor enough and the desired result is otherwise impossible in VSFilter (like `\{{}` to get a literal `{` without completely messing up VSFilter rendering).
API users would mainly benefit from documentation on extensions they can use, but knowing what VSFilter deviations might be changed in the future will also help users to not accidentally depend on libass-specific behaviour they should better not rely upon, since it might be changed.

Below are drafts for both:

**Extensions**:
https://github.com/libass/libass/wiki/Libass'-ASS-Extensions
Since I'm reasonably confident in this being correct (but not necessarily complete), I went ahead and put it in the libass wiki. To be sure, I put an "unreviewed" disclaimer at the top; ~~if everything seems correct, please remove that note.~~ *(done)*
`[1: Footnote about ligatures at the end]`

**VSFilter-libass differences**
https://github.com/TheOneric/libass-regression-tests-tmp/wiki/%5BWIP%5D-Libass-VSFilter-differences
This is just my best-effort guess on what deviations are deliberate or not, based on comments on GitHub and GoogleCode(!) — these might be outdated or I might be misreading them. Therefore I *did not* put this in libass' wiki, but in a different repo for now.
When this has been corrected and discussed where necessary, it can be copied over to the proper wiki.

<br />

Once both docs have been reviewed it might also be worth linking to them from README.

---

**[1]:** Regarding the open question of ligatures: I think I'd be good to at least partially resolve this soon, by eg promising that in the future files with a `Ligatures: yes/no` header will have ligatures enabled/disabled (but explicitly not guaranteeing a default value, or already implementing the header). This way authors that (don't) want ligatures can already set the header *now* – even if it doesn't yet work, it clearly indicates the intended display.
The longer this is left hanging without a way for authors to indicate this, the more files will break, if the default should change.

**Comment by realfinder** [comment]
I think this one https://github.com/libass/libass/issues/148 should be added too, it's not just quality problem https://github.com/libass/libass/issues/148#issuecomment-780239346

also if that fixed then maybe it will also fix https://github.com/libass/libass/issues/226 and https://code.google.com/archive/p/libass/issues/111 and https://github.com/libass/libass/issues/71 and maybe others as said here https://github.com/libass/libass/issues/148#issuecomment-105652950

**Comment by astiob** [comment]
Thanks for reminding of this on IRC.

After a look through the “Extensions” page only, it looks great; thanks! I can suggest a few more details:

* A single opening brace can be displayed without any hacks in VSFilter and modern libass _if and only if_ it is not followed by a closing brace in the same event.

* VSFilter does apply kerning to text written in complex scripts (and any surrounding text up to the usual run boundaries). I don’t know if it does ligatures as well. See #237.

**Comment by TheOneric** [comment]
Thanks for taking a look! I applied your suggestions to the Extensions page.

**Comment by TheOneric** [comment]
Since the original version of the libass-VSFilter page from two years ago, it has ben revised several times and is now likely correct enough to be useful, so I now moved it to the main wiki. See [here](https://github.com/libass/libass/wiki/Differences-between-Libass-and-VSFilters).
