### ISSUE TITLE
Anamorphic blur

### ISSUE THREAD

**Issue by astiob** [libass/libass#410]
In anamorphic video in a classical VSFilter setup (`render_priv->font_scale_x != 1`), blur is applied before the image is stretched horizontally. To faithfully reproduce this, we’d need to stretch our own blur horizontally by `font_scale_x`, making the x-radius and the y-radius different.

@MrSmile I may have asked you before, but how hard would this be?

Of course, this also applies to \be, but the solution I offered in #407 can handle that. Let’s stick to discussing Gaussian blur here.

**Comment by MrSmile** [comment]
Should be mostly straightforward as 2D Gaussian blur is essentially a pair of 1D blurs.
