### ISSUE TITLE
Division by zero with \fsc{x,y}0 

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#413]
In [ass_render.c@calc_transform_matrix](https://github.com/libass/libass/blob/master/libass/ass_render.c#L1273) there will be division by zero if either \đscx or \fscy is zero.
See #412 for a sample with \fscy0 . Compile with `-fsanitize=undefined -fsanitize=float-divide-by-zero` to get logs.

**Comment by astiob** [comment]
Yep. Also #185.

**Comment by TheOneric** [comment]
Oh, I missed that it was already reported.

**Comment by astiob** [comment]
I’ll rename the other one.
