### ISSUE TITLE
Make copyright notices less chaotic

### ISSUE THREAD

**Issue by astiob** [libass/libass#417]
Our copyright notice headers are all over the place. They mention random subsets of individuals who have actually worked on a file, and often outdated year numbers.

It is my understanding that a copyright notice has no legal power and is purely informative. All authors have their rights protected by law, in equal manner regardless of the presence and content of copyright notices. Therefore, we may legally change the current copyright notices as we see fit, without asking the named people for permission or anything.

I therefore suggest two solutions:
1. Change all files (except perhaps those that really have been touched only by one person) to say “Copyright [earliest year any of the file’s contents existed]–2020 libass contributors” and make a commit every year to update the year numbers. This is what I commonly see in other projects.
2. Remove the “Copyright [year] [name]” lines altogether. This is my personal preference.

**Comment by TheOneric** [comment]
> It is my understanding that a copyright notice has no legal power and is purely informative.  All authors have their rights protected by law, in equal manner regardless […]

I'm not a lawyer, but it is also my understanding, that this holds up in most countries today. However, …

> Therefore, we may legally change the current copyright notices as we see fit, without asking the named people for permission or anything.

I don't think this is correct. The libass copyright holders made their work available under the ISC license (or agreed to a license change later), and the ISC license states that *(emphasis mine)*

---

 Permission to use, copy, modify, and/or distribute this software for any
 purpose with or without fee is hereby granted, **provided that the above**
 **copyright notice** and this permission notice **appear in all copies.**

---

Therefore it seems to me, that they cannot be just removed, as this is one of the few rights the copyright-holders did **not** waive. So to change the notice to **only** a more general form or to remove it entirely all authors with an copyright notice would need to agree first. But I'm not an expert on this, so I might have gotten this wrong.  
Though the explicit mentioning of an “above copyright notice” suggests, there should be at least some form of copyright notice.

<br />

On a side note, I noticed that the ISC text used in `COPYING` is the newer version with `and/or`, while the text in `libass/ass.c` and possibly other files doesn't use `and/or`, but the older/OpenBSD-style `and`. What the legal implications of this are, if any, I have absolutely no idea.

**Comment by astiob** [comment]
Ah, you’re right! I forgot about that clause in the licence.

OK, so then we probably want to do option 1 (switch the notice from individual names to a generic phrasing) and get agreement from… well, shit. Theoretically we need to get agreement from every person who’s ever touched the code, don’t we? Just as for a full-blown relicensing.

pls send law help

**Comment by rcombs** [comment]
Yeah, that'd essentially constitute a relicensing, as would removing the notices altogether. We can add new ones, though.

**Comment by TheOneric** [comment]
We now prefer a generic `libass contributors` for new files. Existing notices remain and can only be touched by the mentioned author.
