### ISSUE TITLE
Expose "authorship mode" with dumber font fallback

### ISSUE THREAD

**Issue by rcombs** [libass/libass#425]
When working in Aegisub, it's possible to enter a font name that will appear to work on your machine, but won't if the font is muxed. Example:
- The copy of MS PGothic that ships on macOS is non-PostScript, has fullnames `MS PGothic` and `ＭＳ Ｐゴシック`, and PostScript name `MS-PGothic`
- When searching for `MS-PGothic`, we won't match the font because the fullnames don't match and it's non-PostScript
- We then call `default_provider->funcs.get_fallback`, passing in `MS-PGothic`
- On macOS, CoreText helpfully returns `MS PGothic`
- We then search for `MS PGothic` and end up with the font we'd been looking for to begin with

This is hazardous, since it's possible to enter a font name, think everything is perfectly fine, mux it, and then be informed too late that it doesn't work on systems that don't have it installed (or that do, but are on a different platform).

To address this, I'm proposing that we let the calling application put a renderer in "authorship mode", in which we either explode and draw tofu if matching the requested font name fails, or pass Arial to `default_provider->funcs.get_fallback`. The latter would be simpler to implement, but the former would be more robust. This flag could also be used to trigger alerts (either in the rendered output or in a log) when other problematic cases are detected, such as known vsfilter deviations.

**Comment by TheOneric** [comment]
> To address this, I'm proposing that we let the calling application put a renderer in "authorship mode", in which we either explode and draw tofu if matching the requested font name fails,
> This flag could also be used to trigger alerts (either in the rendered output or in a log) when other problematic cases are detected, such as known vsfilter deviations.

“Authorship Mode” seems like it could be useful, though I have no idea how hard it would be to implement.
Is this different from the “Strict Mode” proposed in #78 ?

**Comment by rcombs** [comment]
Ahahahaha, I duped my own issue! Yeah, exact same thing; I'll merge into that.
