### ISSUE TITLE
Incorrect line height with lines containing only drawings

### ISSUE THREAD

**Issue by rcombs** [libass/libass#427]
```
[Script Info]
; Script generated by Aegisub 8959-rcombs-local-bae0e529a
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:24.000000:2700:1280:720:255:254:254:c
Video AR Value: 1.777778
Video Zoom Percent: 1.000000
Active Line: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,51,&H00FFFFFF,&H000000FF,&H00472A27,&HCC000000,-1,0,0,0,100,100,0,0,1,3.17333,1.88889,2,200,200,43,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7\pos(400,330)}A\N{\p1}m 0 0 l 10 0 10 10 0 10{\p0}\N{\p0}C\N{\p1}m 0 0 l 10 0 10 10 0 10{\p0}
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7\pos(440,330)}A\NB\N{\p0}C\ND
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7\pos(500,330)}A\N\N{\p1}m 0 0 l 10 0 10 10 0 10{\p0}\N\N{\p0}B\N\N{\p1}m 0 0 l 10 0 10 10 0 10{\p0}
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7\pos(540,330)}A\N\NB\N\N{\p0}C\N\ND
```
libass:
![image](https://user-images.githubusercontent.com/819638/93550802-dde97600-f931-11ea-8eb3-2d74c5384b14.png)
vsfilter:
![unknown-14](https://user-images.githubusercontent.com/819638/93550807-e3df5700-f931-11ea-80b7-322b32c1ed51.png)

It looks like libass is using the font's normal line-height for `\N`, whereas vsfilter doesn't give it any height at all.

**Comment by TheOneric** [comment]
With libass 0.14, the output is closer to VSFilter (but not identical!). I guess the difference in master with drawings specifically is likely due to regression #418 .

libass 0.14:
![grafik](https://user-images.githubusercontent.com/1668471/93594932-0cf5fb00-f9b7-11ea-8130-266b80f44333.png)

**Comment by astiob** [comment]
This _is_ #418.

**Comment by TheOneric** [comment]
With astiob's PR #429 , libass now seems to match VSFilter perfectly in this instance *(- ignoring that the font is Arimo instead of Arial)*:
![grafik](https://user-images.githubusercontent.com/1668471/93607165-40da1c00-f9c9-11ea-9bd4-418d0d8ba0b9.png)

Same goes for the sample from the mpv issued referenced in #418 (there still are a few drawing seemingly spread out, but I recall those also being like this in xy-VSFilter)
