### ISSUE TITLE
VSFilter shenanigans: Combining glyphs and implicit positioning

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#444]
[Originally found](https://github.com/libass/libass/pull/395#issuecomment-716932940) by astiob.

If an event's text consists only of an combining grave accent (U+0300, UTF8-hex: cc80) or other combining glyphs, funny things happen in (xy-)VSFilter.
This was tested with `combining grave accent U+0300`, `combining cedilla U+0327` and `combining long stroke overlay U+0336`.
It still needs a final looka at VSFilter's source code, but for now here's my current understanding based on practical tests:

If the combining glyph ist the only text (not counting override blocks) in an event, and it doesn't have a (x?)border:
 - No matter the alignment and the alignments default shifting direction (for implicit positioning due to collisions) the \`-event will be positioned above/inside/below the first colliding event of same alignment. 
  Compared to an combining character inside the first event, the standalone cg-event is shifted a bit to the left.
 *(Possibly it just stays in the default position for it's alignment. I did not test what happens if the first same-an-event is pushed out of default position by events of another alignment)*
 - If there are multiple borderless cg-events, they'll be rendered on top of each other

If the combining glyph can combine with a preceding glyph, is followed by another glyph or if `\bord≠0` none of those shenanigans happen (except for the left shift). Especially consecutive cg-events don't collapse into one even if their non-zero border-values are identical.
Shadow does not change the behaviour.

**Things to look at:**
 - Shift first same-an-event out of default position by event of different \\an
 - VSF's source code to find out *why* this happens

I also tried to test if Guliverkli- and Guliverkli2-VSF already had these shenanigans, but I couldn't get subtitle-rendering to work at all.

**Sample:**
*(for testing shuffle alignements, border-vals and event-order a bit around)*
```
[Script Info]
ScaledBorderAndShadow: yes
PlayResX: 1280
PlayResY: 720


[V4+ Styles]
Style: Default,Arial,96,&H000000FF,&H80FFFF00,&H00000000,&H0000FF00,0,0,0,0,100,100,0,0,1,0,0,2,0,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2}A
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2}̀
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2}F̀
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2\bord0}̀
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2\bord5}̀
Dialogue: 0,0:00:00.00,0:00:10.00,Default,,0,0,0,,{\an2}C

```

Misplaced event:
![grafik](https://user-images.githubusercontent.com/1668471/97517723-071c0e00-1996-11eb-9a22-79f3b7a8bb81.png)

Additional glyphs (F and \` are in the same event, \` and D too *(in that order)* )
![grafik](https://user-images.githubusercontent.com/1668471/97517737-0daa8580-1996-11eb-908b-9357b99cec56.png)
![grafik](https://user-images.githubusercontent.com/1668471/97517758-18fdb100-1996-11eb-835e-2a2b168e01fd.png)

Consecutive `\bord5` events, do not collapse:
(F and \` are same event, A and the \` above are **not** the same event)
![grafik](https://user-images.githubusercontent.com/1668471/97517750-13a06680-1996-11eb-8756-d962cb4c21cd.png)

Other combinig glyphs:
![grafik](https://user-images.githubusercontent.com/1668471/97615392-899ae100-1a1b-11eb-8a2a-b733afd488ea.png)
![grafik](https://user-images.githubusercontent.com/1668471/97615435-97506680-1a1b-11eb-96e6-b4cf979af8ed.png)
![grafik](https://user-images.githubusercontent.com/1668471/97615487-aafbcd00-1a1b-11eb-9d87-b7752eecfb58.png)

With BorderStyle=3 the left shift is visible:
![grafik](https://user-images.githubusercontent.com/1668471/97615634-ded6f280-1a1b-11eb-9728-0f1d22af5c21.png)

**Comment by astiob** [comment]
Oof, so the accent was the culprit.

I imagine VSFilter is seeing it as an event with a zero width, as combining accents have zero advances (because they’re combining). It should still be getting the normal ascender and descender values though, and therefore the normal height. But perhaps the collision avoidance algorithm does funny things when events have zero width.

**Comment by TheOneric** [comment]
Updated previous comment after testing with more combining glyphs.
Unlike I wrote earlier, CG-Events are **not** rendered above the previous non-cg-event of same alignment, but at the default alignment-position / first same-alignment-alignment. I probably confused an accent that was part of another event with a standalone cg-event in my late night testing. Similarly cg-events seemingly not respecting margins was just because the combinig grave accent doesn't count towards the event's height.

Taking a look at xy-VSF code: https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4@%7B2020-05-17%7D/src/subtitles/RTS.cpp#L1627
and Microsoft's`CRect`-documentation:
https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/crect-class?view=msvc-140#operator_amp
https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/crect-class?view=msvc-140#isrectempty

We see that VSF treats event's as non-colliding if their overlapping **area** is zero. So events of zero width or height are always *non-overlapping* and thus never shifted.
The left-shift of the combining glyph is probably a side-effect of rendering acg without a previous glyph to combine with.

**Comment by astiob** [comment]
I think what you’re calling a left-shift is just the normal rendering of a combining accent: it’s rendered on top of the glyph that precedes it on the left, which in this case is absent.

**Comment by astiob** [comment]
So what I gather is that in the picture I originally showed with the Devanagari, the accent event was actually anchored in the same place as the Devanagari, and it only looked to me as if it was significantly above the Devanagari because the Devanagari was set in a visually smaller font.

It seems that the problem is that VSFilter uses the glyphs’ total horizontal advance as the event width for collision purposes, while libass uses the glyphs’ total bounding box:
https://github.com/libass/libass/blob/0.15.0/libass/ass_render.c#L2806-L2810

**Comment by astiob** [comment]
Wait, actually, no. We also use horizontal advances. This `bbox` in the code I quoted above is computed from advances, not glyphs’ individual bboxes. _Never mind that._

So it’s just the zero area thing.

Anyway, great work on the sleuthing!
