### ISSUE TITLE
ASM config may be borked on some 32bit x86 ABIs

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#451]
As we found out in #450 , FreeBSD is patching the NASM-configuration⁵ to work for their 32-bit ABI.
Regarding Linux-distros, Debian consiciously disabled NASM for i386-architectures¹ (but it **is** enabled for x32²³), while iiuc Gentoo⁴ has NASM enabled for i386 and amd64 but not x32.

Unfortunately, this is the end of useful information I have about this, as I don't know about other BSD's and OpenIndiana⁶ has NASM explicitly disabled *(presumably because when libass was added to OI's repo, the Solaris-config-bug⁷ wasn't yet fixed)* and Haiku currently also has NASM disabled *(#450 fixes at least x86_64-Haiku)*.

¹:https://salsa.debian.org/multimedia-team/libass/-/commit/d9eae1f0aefacf9b8c838cb5108dcc100f336e0b
²:https://buildd.debian.org/status/fetch.php?pkg=libass&arch=x32&ver=1%3A0.15.0-1&stamp=1603818152&raw=0
³:https://salsa.debian.org/multimedia-team/libass/-/commit/92a5c15e7d5feae3087b3f04346469af0ae18c9d
⁴:https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libass/libass-0.14.0.ebuild
⁵:https://svnweb.freebsd.org/ports/head/multimedia/libass/files/patch-configure.ac?view=markup
⁶:https://github.com/OpenIndiana/oi-userland/blob/26aaf0b/components/library/libass/Makefile
⁷:https://github.com/libass/libass/commit/62dba758ea64d9819d0021f1d6c9cbb9369d63b1
⁸:https://github.com/haikuports/haikuports/blob/45de8e68fb19e3a767c5b24b3a8ec09b881ab6e4/media-libs/libass/libass-0.14.0.recipe#L74

**Comment by rcombs** [comment]
Hmmm, looking at the relevant code in ffmpeg, we've got this:
```
    if enabled x86_32; then
        # Clang doesn't support maintaining alignment without assuming the
        # same alignment in every function. If 16 byte alignment would be
        # enabled, one would also have to either add attribute_align_arg on
        # every single entry point into the libraries or enable -mstackrealign
        # (doing stack realignment in every single function).
        case $target_os in
        mingw32|win32|*bsd*)
            disable aligned_stack
            ;;
        *)
            check_cflags -mllvm -stack-alignment=16
            check_cflags -mstack-alignment=16
            ;;
        esac
    else
```
So it seems to be specific to 32-bit BSD.

**Comment by TheOneric** [comment]
Since dragonfly was explictily added in e78e8358b2a476a5106828eced7f356d11f5c708 I guess ffmpeg doesn't disable aligned stack for DragonFlyBSD and while DragonFlyBSD *does* [patch ffmpeg's config](https://github.com/DragonFlyBSD/DPorts/blob/44d8d47f477ae0328233c82befe0c3e5564bea1f/multimedia/ffmpeg/files/patch-configure), it doesn't it doesn't seem to affect the aligned stack part.
Curiously though, DragonFlyBSD **does** apply the [same patch](https://github.com/DragonFlyBSD/DPorts/blob/c8d87d4b1e3d55f7ca693aadb743114c404064d5/multimedia/libass/files/patch-configure.ac) to libass' config as FreeBSD.

NASM seems to have been disabled on i386-Debian builds, because it [does not produce PIC-code](https://salsa.debian.org/multimedia-team/libass/-/commit/d9eae1f0aefacf9b8c838cb5108dcc100f336e0b). Is there a reason we disable PIC on 32bit-builds?

*(NetBSD unconditionally disables asm, and i386 Debian/kFreeBSD has ASM disabled like all of Debian's i386-libass-builds.)*

**Comment by astiob** [comment]
Does https://github.com/TheOneric/libass/commit/3dd85536d73328a677f04a49448ea31c45f5181d actually resolve all doubts mentioned in this issue? I see it claims to close this, but it seems to be only BSD stuff, but Debian is also mentioned here and I don’t remember if we ever figured it out.

**Comment by TheOneric** [comment]
> Debian is also mentioned here and I don’t remember if we ever figured it out.

Enabling PIC can be preferable for security reasons, but on some architectures comes at a noticeable cost in performance. Because of this¹  Debian policy (eg [here](https://www.debian.org/doc/debian-policy/ch-files.html#libraries)) strongly prefers PIC, but for affected architectures, in special cases (like an too large performance impact) individual packets can be exempt from this.
I haven't tested NASM on i386 myself, but since it is enabled by Gentoo, I suspect NASM does work on i386-Linux.

---

1: And because non-PIC *dynamic libararies* may in general cause additional trouble; but this does not happen in our NASM-case.
