### ISSUE TITLE
SECURITY: Integer Overflow to OOB in ass_add_font()

### ISSUE THREAD

**Issue by raminfp** [libass/libass#455]
Hi,

We see define type `long size = ftell(fp);` [compare.c#L248](https://github.com/libass/libass/blob/master/compare/compare.c#L248), and pass `ass_add_font(lib, file, buf, size);`.

we see in the function `void ass_add_font(ASS_Library *priv, const char *name, const char *data, int size)` type `size` is `int`. potential "interger overflow".

And in the line [libass/ass_library.c#124](https://github.com/libass/libass/blob/master/libass/ass_library.c#L124), possible out of bound bug.

Thanks,

**Comment by astiob** [comment]
The code you linked to:

https://github.com/libass/libass/blob/7a853255bb5083c9c6ab31a29f215875dc8d8251/compare/compare.c#L248-L252

contains a length check on the very next line. Is there an issue that this check fails to avoid?

**Comment by TheOneric** [comment]
iirc we assume a signed `int` can at least hold  2³¹-1  , so the existing check should be sufficient, although something like `>= INT_MAX` may be better for clarity.

Please correct me if I'm wrong, but even if we assume `int` to be smaller than that, it appears to me the error would be an undefined `long` to `int` cast in `compare`¹ and not an OOB in `ass_add_fonts` as there only the result of the cast to `int` is used.

*(¹: To explain why this distinction is somewhat relevant: `compare` is not part of the lib itself, but used in our test suite for development of the lib. So potential security errors here won't affect regular users.)*

**Comment by raminfp** [comment]
@TheOneric Thanks, 
> although something like >= INT_MAX may be better for clarity.

You are right. I did not pay attention.

`(1l << 30) = 1,073,741,824` < `int = 2,147,483,647`.
