### ISSUE TITLE
v0.15.0 on macOS fails font fallback to fonts without Microsoft names

### ISSUE THREAD

**Issue by ViktoriiaKh** [libass/libass#457]
v0.14.0 renders Arabic subtitles properly.

![Screenshot 2020-11-23 at 14 06 06](https://user-images.githubusercontent.com/19269642/99960292-2b9cb780-2d95-11eb-91a7-77922520c0b4.png)

v0.15.0 doesn't.

![Screenshot 2020-11-23 at 14 04 21](https://user-images.githubusercontent.com/19269642/99960339-3fe0b480-2d95-11eb-9e6b-98fca79655a9.png)

**Comment by TheOneric** [comment]
Can you provide a sample reproducing the issue? Ideally this would be a small cut of the ASS-file, eg just the Dialogue line shown in your screenshots but also all Header lines and relevant Style lines. If your not sure how to do this you can use eg MKVToolnix. Alternatively the full ASS-file should also work.
Also, as this likely is a font-related issue it would be good to attach the relevant font.

Furthermore it would be good to know on which system (Mac, Linux, …)  and inside which application (eg VLC, mpv, …) you are using libass and to have the log if you have one.

**Comment by astiob** [comment]
If you don’t provide the full MKV file, please list what fonts it has attached.

I suspect this is another case of a font not being attached to the MKV in the first place and the system-specific fallback behaving differently from our font selection.

**Comment by ViktoriiaKh** [comment]
macOS v10.15.7

I have built mpv v0.32.0 from sources with the latest libass v0.15.0.

I would like to watch an .mp4-file with external .srt-subtitles in Arabic.

The subtitles file is available here
https://0x0.st/iRMW.srt

mpv log
[mpv.log](https://github.com/libass/libass/files/5583773/mpv.log)

I have also built ffmpeg with libass v0.15.0 in order to burn subtitles into video. The same problem occurs when burning subtitles into video using the video filter subtitles.

I have also found this issue
https://github.com/iina/iina/issues/3222

**Comment by sjml** [comment]
Seeing this with just a bare .srt file. Happening in iina (the bug linked above), but no other changes were made to the system, so it's using the same fonts as the previous version when they were functional. 

File linked:
[spirited.away.ar.srt.zip](https://github.com/libass/libass/files/5625115/spirited.away.ar.srt.zip)

**Comment by astiob** [comment]
@rcombs What do you think?

The issue as I remember it is that our CoreText font provider’s `get_fallback` asks CoreText for font fallback, and CoreText returns fonts that have no Microsoft names. Then `get_fallback` queries the fallback font’s name from CoreText and returns it. Finally, `select_font` hands this name over to `match_fonts` and `find_font`. Since be0d1613f79a95073d18d96a60e1394abf9316a2, we run `get_font_info` on CoreText-provided fonts to list their names, which outputs only Microsoft names or at most a single FreeType-provided name. `find_font` then fails to find a match because the CoreText-output Apple name differs from the name found by `get_font_info` if any.

I see several options for fixing this:

1. Make `get_font_info` provide Apple names if there are no Microsoft names in the font.

    Cons: This may mess up nonfallback font matching. And even if a font does have a Microsoft name, I imagine CoreText might return a non-Microsoft one.

2. Make the CoreText `get_fallback` look up the name to return via `get_font_info` or equivalent, rather than query CoreText for it.

    Pros: This should take care of the case when CoreText returns a non-Microsoft name for a font that has one.

    Cons: This will not, in fact, help in the case when CoreText selects a font that entirely lacks any names that `get_font_info` can see. I don’t know whether this is possible though. But even if this is impossible, I don’t know if FreeType-provided names are reliably unique enough.

    Side note: we use `get_font_info`, and its Microsoft name filtering, only for CoreText-provided and memory fonts. Do Fontconfig-provided fonts not need this?

3. Make `get_fallback` return a font directly, instead of a font name.

    Pros: This would guarantee fallback always works.

    Cons: This could mess up bold, italic etc. As is, `get_fallback` does not even attempt to convey information about weight and slant to the native fallback choice mechanism, and we run `match_fonts` on the fallback name to lazy-load all fonts with that name and then `find_font` to find the best-fitting one among them. But we could probably add whatever traits we want to match to `get_fallback`. We’d need to implement this in all font providers (and this would be an API break for Aegisub/Kainote, but an easy one, and this API was never public in the first place). We might also end up with font providers preferring different fallback fonts than we do currently; but for fallback perhaps that’s not too important.

    On that note, the CoreText `get_fallback` could get better results by retaining a reference to the actual CoreText font used before fallback, in case it is a CoreText-provided font, and passing it into `CTFontCreateForString`, rather than create a new font reference by name (and potentially other properties if we add them to `get_fallback`) and effectively invoke CoreText’s font search & fallback twice in a row.

**Comment by rcombs** [comment]
Hmmmmmm, I'm inclined to prefer either (1) or (3) over (2), and I think (3) seems the most robust.

Re: consumers using private APIs to disable fallback, this seems like it would be better solved by #78 (which in the current API would probably be best implemented as an `ASS_Feature` flag).

**Comment by astiob** [comment]
> Re: consumers using private APIs to disable fallback

I can only guess, but I think the main point of Aegisub’s font provider is to support Windows XP. The lack of fallback seems like something tgoyne was simply unwilling or unable to implement and decided to bill as a feature instead :-) But I agree it’s useful in its own right and #78 is the way to go.
