### ISSUE TITLE
VSFilter-incompatible baseline behavior with \fay

### ISSUE THREAD

**Issue by rcombs** [libass/libass#465]
We've known about this for ages but here I've got a vsfilter-authored script that actually relies on their behavior (and in a reasonably sane way, even), so we've actually got something useful to test against.
[ron.full.ass.txt](https://github.com/libass/libass/files/5682648/ron.full.ass.txt)

VSFilter:
![image](https://user-images.githubusercontent.com/819638/101978415-68343400-3c1a-11eb-9a48-7e60a8851da0.png)
libass:
![image](https://user-images.githubusercontent.com/819638/101978413-594d8180-3c1a-11eb-8e68-525ffbe57785.png)

**Comment by astiob** [comment]
This somehow gets fixed by commit cea71ffe2d3a5855d8c98804e2aa8c4263dbadb0 from #445, but I don’t understand how.

**Comment by astiob** [comment]
Figured it out. Our old code was buggy (surprise, surprise!):

https://github.com/libass/libass/blob/0a3b14a76700b2c1db4d41611199d9aed336c191/libass/ass_render.c#L2113-L2116

uses the _next_ glyph’s scale factors to cancel out shear accumulated over multiple _preceding_ glyphs.

Change \fay and \fscy at the same time (as this sample does)—bam, this calculation is wrong. It’s also wrong if \fscx/y changes anywhere along the way.

Further impacting this sample, shear also accumulates rounding error, even after #445 in its current state. This allows our old correction code to compute a slightly different value even when \fscx/y doesn’t change.
