### ISSUE TITLE
Truncate \k-related tag values before multiplying by 10

### ISSUE THREAD

**Issue by rcombs** [libass/libass#467]
VSFilter parses these as integers rather than floats, and some Aegisub scripts produce non-integer output for these tags, so it's easy to produce scripts that end up relying on the vsfilter behavior without intending to. Should be an easy fix; just move the cast to before the multiplication.

We might also want to add a dedicated integer-parsing routine (could potentially be faster than our current float route); at a bare minimum we should have something that does the float->int conversion in an overflow-safe way.

**Comment by TheOneric** [comment]
Well, Guliverkli2-VSF parses `\k`-tags values as integer numbers¹, as you noticed. However, xy-VSFilter parses them as floating point numbers.²
It's the same with `\fs`, see https://github.com/libass/libass/issues/420#issuecomment-665310168

\[1\]: https://sourceforge.net/p/guliverkli2/code/HEAD/tree/src/subtitles/RTS.cpp#L1757
\[2\]: https://github.com/Cyberbeing/xy-VSFilter/commit/404301a33f40978526382e69777d9e6a864edd65

**Comment by rcombs** [comment]
Hmmm, yeah, sounds like we should be fine here then.
