### ISSUE TITLE
Yet another metrics incompatibility

### ISSUE THREAD

**Issue by rcombs** [libass/libass#474]
[CapieN.zip](https://github.com/libass/libass/files/5984407/CapieN.zip)
Attached font and sample .ass. This lays out as expected (with the main text fully within the clips) in vsfilter, but is drawn substantially larger in libass.
![image](https://user-images.githubusercontent.com/819638/107998915-bd3e4e80-6fab-11eb-8cc3-bab3175382d1.png)

**Comment by moi15moi** [comment]
Important to note, this issue only happen since the requested font start with a ``@``.
When it isn't, libass has the same result has VSFilter.
