### ISSUE TITLE
Different text size than in Xysubfilter

### ISSUE THREAD

**Issue by MatiasMovie** [libass/libass#484]
Subtitles:
[FPS_test_1080p23.976_L4.1.zip](https://github.com/libass/libass/files/6094520/FPS_test_1080p23.976_L4.1.zip)

XySubFilter and external subtitles:
![XySubFilter and external](https://user-images.githubusercontent.com/24187109/110190922-10c2f000-7e26-11eb-9895-c6f08987c986.png)

mpv and mkv:
![mpv](https://user-images.githubusercontent.com/24187109/110190824-92664e00-7e25-11eb-82b9-8812a8a559af.png)

**Comment by astiob** [comment]
Are you sure you’re using a current libass (0.15.0)? (and the same font file in both renderers?)

If you are using current libass and the issue persists, please supply the font.

**Comment by MatiasMovie** [comment]
> Are you sure you’re using a current libass (0.15.0)? (and the same font file in both renderers?) If you are using current libass and the issue persists, please supply the font.

I have no idea which version is in MPV
I have the latest version of MPV

**Comment by realfinder** [comment]
> 
> 
> > Are you sure you’re using a current libass (0.15.0)? (and the same font file in both renderers?) If you are using current libass and the issue persists, please supply the font.
> 
> I have no idea which version is in MPV
> I have the latest version of MPV
> 
> font name "Angie PL"
> I used the same subtitles
> Xysubfilter has a problem with this subtitles when they are in the MKV file ([bug with "space" in the end in style name](https://github.com/pinterf/xy-VSFilter/issues/16#issuecomment-792232586))
> MPV shows the subtitles in the same way regardless of whether they are inside or outside

assrender v0.35 should have 0.15.0 https://github.com/pinterf/assrender/releases if you can use avs

**Comment by astiob** [comment]
I have just tried the file from https://github.com/pinterf/xy-VSFilter/issues/16, and ***I am unable to reproduce your XySubFilter picture.***

This is what I get in xy-VSFilter 3.0.0.322 (from CCCP, jeeb@xy-VSFilter@blitzkrieg aka Cyberbeing/xy-VSFilter@229ab9be0d38435ff9ba8dfbc14edce14030dc53):

![random_sample_with_problematic_subtitles mkv_snapshot_00 14_ 2021 03 07_16 47 55](https://user-images.githubusercontent.com/515193/110244238-6c949280-7f66-11eb-8d6c-74a9127ee5bc.png)

This is what I get in XySubFilter 3.1.0.752 (the latest published release from Cyberbeing, https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.1.0.752):

![random_sample_with_problematic_subtitles mkv_snapshot_00 14_ 2021 03 07_17 05 49](https://user-images.githubusercontent.com/515193/110244521-bf227e80-7f67-11eb-82fa-a2d8610081fe.png)

This is what I get in XySubFilter 3.2.0.804 (the latest published release from pinterf, https://github.com/pinterf/xy-VSFilter/releases/tag/3.2.0.804):

![random_sample_with_problematic_subtitles mkv_snapshot_00 14_ 2021 03 07_17 08 12](https://user-images.githubusercontent.com/515193/110244551-eed18680-7f67-11eb-9afc-03dce578c731.png)

This is what I get from current libass in mpv:

![mpv-shot0001](https://user-images.githubusercontent.com/515193/110244572-ff81fc80-7f67-11eb-9fe6-7022eb253734.png)

Every single one of these is the same as your libass screenshot.

---

For reference, mpv does not fix libass at any particular version. It is possible to build mpv with many different libass versions. You must have gotten your mpv from someone or some place—that person (or the person in charge of that place) decides which libass version they include in the build.

**Comment by MatiasMovie** [comment]
OK, I reinstalled players and fonts and now the size is the same, I'm sorry for misleading
