### ISSUE TITLE
VSFilter does not apply \fsp to vector drawings

### ISSUE THREAD

**Issue by MatiasMovie** [libass/libass#487]
A minimally different karaoke position between XYsubfilter (pintref) and Libass

XYsubfilter v3.2.0.804 (mpc-be)
![mpc](https://user-images.githubusercontent.com/24187109/112151021-0738d680-8be1-11eb-9f7c-d5fa6d211b01.png)

libass (mpv)
![libass](https://user-images.githubusercontent.com/24187109/112151067-14ee5c00-8be1-11eb-98bf-aaf700045deb.png)

**Comment by TheOneric** [comment]
We need more info on this, most importantly:

**libass version**
Which libass version did you use? *(And additionally since you're using mpv: which mpv version? Including mpv's log may also help. see further below)*


**ASS Sample**
Please provide a sufficient sample to reproduce this.

At minimum this will be an excerpt of the ASS file; don't forget to also share the used Styles not only the Dialogue line. The excerpt should basically be a fully functional ASS file in itself.

If the issue is specific to a video file, please try to upload a short cut of it. Eg MKVToolNix allows you to make a smaller cut from a larger file.

**Include the font**
If an uncommon font is needed to see the wrong rendering, upload it as a file if you have permission to do so. If it is a free font available on the Web, you can instead give a link to it.

**Fontprovider**
Which fontprovider are you using? *(You can check this in mpv's log; use `mpv -v -v` and search for lines starting with `[sub/ass]` or `[osd/libass]`)*

**System**
Which system were you using to produce this libass- and xy-screenshot each? *(Eg Debian Buster, MacOS xy.z, OpenIndiana, MS Windows XY, …)*
If it wasn't on an 64-bit x86 *(Intel, AMD)* CPU, which CPU architecture?

**Comment by MatiasMovie** [comment]
mpv
`[cplayer] mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Feb 28 09:25:17 +08 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.66.100
[cplayer]    libavcodec      58.126.100
[cplayer]    libavformat     58.68.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.107.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: git-2021-02-28-85ab9deb
[cplayer]
[cplayer] Configuration: /home/shinchiro/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build64/install/mingw
[cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib
[global] config path: '' -> 'C:\Users\Admin\AppData\Roaming/mpv'
[global] user path: '~~home/' -> 'C:\Users\Admin\AppData\Roaming/mpv'
[global] user path: '~~old_home/' -> ''
[global] config path: 'encoding-profiles.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -/-> 'C:/mpv + shaders/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -/-> 'C:/mpv + shaders/mpv/encoding-profiles.conf'
[global] config path: 'mpv.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/mpv.conf'
[global] config path: 'config' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/config'
[global] config path: 'mpv.conf' -/-> 'C:/mpv + shaders/mpv.conf'
[global] config path: 'config' -/-> 'C:/mpv + shaders/config'
[global] config path: 'mpv.conf' -> 'C:/mpv + shaders/mpv/mpv.conf'
[global] config path: 'config' -/-> 'C:/mpv + shaders/mpv/config'
[cplayer] Reading config file C:/mpv + shaders/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'gpu-api' = 'vulkan' (flags = 4)
[cplayer] Setting option 'dscale' = 'ewa_lanczos' (flags = 4)
[cplayer] Setting option 'keep-open' = 'yes' (flags = 4)
[cplayer] Setting option 'border' = 'no' (flags = 4)
[cplayer] Setting option 'window-scale' = '2' (flags = 4)
[cplayer] Setting option 'fbo-format' = 'rgba16hf' (flags = 4)
[cplayer] Setting option 'sigmoid-upscaling' = 'no' (flags = 4)
[cplayer] Setting option 'glsl-shaders-append' = '~~/shaders/FSRCNNX_x2_16-0-4-1.glsl' (flags = 4)
[cplayer] Setting option 'glsl-shaders-append' = '~~/shaders/KrigBilateral.glsl' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/input.conf'
[global] config path: 'input.conf' -/-> 'C:/mpv + shaders/input.conf'
[global] config path: 'input.conf' -/-> 'C:/mpv + shaders/mpv/input.conf'
[osc] Loading lua script @osc.lua...
[ytdl_hook] Loading lua script @ytdl_hook.lua...
[osc] loading mp.defaults
[stats] Loading lua script @stats.lua...
[osc] loading @osc.lua
[ytdl_hook] loading mp.defaults
[console] Loading lua script @console.lua...
[stats] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[auto_profiles] Loading lua script @auto_profiles.lua...
[osc] reading options for osc
[console] loading mp.defaults
[ytdl_hook] reading options for ytdl_hook
[cplayer] mpv 0.33.0-88-gd1be8bb606 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Feb 28 09:25:17 +08 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.66.100
[cplayer]    libavcodec      58.126.100
[cplayer]    libavformat     58.68.100
[cplayer]    libswscale      5.8.100
[cplayer]    libavfilter     7.107.100
[cplayer]    libswresample   3.8.100
[cplayer] FFmpeg version: git-2021-02-28-85ab9deb
[cplayer]
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer]
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer]
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer]
[global] config path: 'script-opts/ytdl_hook.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/script-opts/ytdl_hook.conf'
[global] config path: 'script-opts/ytdl_hook.conf' -/-> 'C:/mpv + shaders/script-opts/ytdl_hook.conf'
[stats] loading @stats.lua
[auto_profiles] loading mp.defaults
[stats] reading options for stats
[global] config path: 'script-opts/osc.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/script-opts/osc.conf'
[console] loading @console.lua
[global] config path: 'script-opts/ytdl_hook.conf' -/-> 'C:/mpv + shaders/mpv/script-opts/ytdl_hook.conf'
[ytdl_hook] script-opts/ytdl_hook.conf not found.
[global] config path: 'script-opts/osc.conf' -/-> 'C:/mpv + shaders/script-opts/osc.conf'
[global] config path: 'script-opts/osc.conf' -/-> 'C:/mpv + shaders/mpv/script-opts/osc.conf'
[osc] script-opts/osc.conf not found.
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/lua-settings/ytdl_hook.conf'
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> 'C:/mpv + shaders/lua-settings/ytdl_hook.conf'
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> 'C:/mpv + shaders/mpv/lua-settings/ytdl_hook.conf'
[ytdl_hook] lua-settings/ytdl_hook.conf not found.
[auto_profiles] loading @auto_profiles.lua
[global] config path: 'script-opts/stats.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/script-opts/stats.conf'
[global] config path: 'lua-settings/osc.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> 'C:/mpv + shaders/lua-settings/osc.conf'
[ytdl_hook] Exiting...
[auto_profiles] Exiting...
[global] config path: 'script-opts/stats.conf' -/-> 'C:/mpv + shaders/script-opts/stats.conf'
[console] reading options for console
[global] config path: 'lua-settings/osc.conf' -/-> 'C:/mpv + shaders/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found.
[global] config path: 'script-opts/console.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/script-opts/console.conf'
[global] config path: 'script-opts/stats.conf' -/-> 'C:/mpv + shaders/mpv/script-opts/stats.conf'
[global] config path: 'script-opts/console.conf' -/-> 'C:/mpv + shaders/script-opts/console.conf'
[cplayer] Run command: define-section, flags=64, args=[name="showhide", contents="mouse_move script-binding osc/__keybinding1\nmouse_leave script-binding osc/__keybinding2\n", flags="force"]
[global] config path: 'script-opts/console.conf' -/-> 'C:/mpv + shaders/mpv/script-opts/console.conf'
[console] script-opts/console.conf not found.
[stats] script-opts/stats.conf not found.
[global] config path: 'lua-settings/console.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/lua-settings/console.conf'
[cplayer] Run command: define-section, flags=64, args=[name="showhide_wc", contents="mouse_move script-binding osc/__keybinding3\nmouse_leave script-binding osc/__keybinding4\n", flags="force"]
[global] config path: 'lua-settings/console.conf' -/-> 'C:/mpv + shaders/lua-settings/console.conf'
[global] config path: 'lua-settings/console.conf' -/-> 'C:/mpv + shaders/mpv/lua-settings/console.conf'
[console] lua-settings/console.conf not found.
[cplayer] Run command: enable-section, flags=64, args=[name="showhide", flags="allow-hide-cursor+allow-vo-dragging"]
[cplayer] Run command: enable-section, flags=64, args=[name="showhide_wc", flags="allow-hide-cursor+allow-vo-dragging"]
[global] config path: 'lua-settings/stats.conf' -/-> 'C:\Users\Admin\AppData\Roaming/mpv/lua-settings/stats.conf'
[global] config path: 'lua-settings/stats.conf' -/-> 'C:/mpv + shaders/lua-settings/stats.conf'
[console] Exiting...
[global] config path: 'lua-settings/stats.conf' -/-> 'C:/mpv + shaders/mpv/lua-settings/stats.conf'
[stats] lua-settings/stats.conf not found.
[cplayer] Run command: define-section, flags=64, args=[name="input", contents="mbtn_left script-binding osc/__keybinding5\nshift+mbtn_left script-binding osc/__keybinding6\nmbtn_right script-binding osc/__keybinding7\nmbtn_mid script-binding osc/__keybinding8\nwheel_up script-binding osc/__keybinding9\nwheel_down script-binding osc/__keybinding10\nmbtn_left_dbl ignore\nshift+mbtn_left_dbl ignore\nmbtn_right_dbl ignore\n", flags="force"]
[cplayer] Run command: enable-section, flags=64, args=[name="input", flags=""]
[cplayer] Run command: define-section, flags=64, args=[name="window-controls", contents="mbtn_left script-binding osc/__keybinding11\n", flags="force"]
[cplayer] Run command: enable-section, flags=64, args=[name="window-controls", flags=""]
[stats] Exiting...
[cplayer] Run command: disable-section, flags=64, args=[name="input"]
[cplayer] Run command: disable-section, flags=64, args=[name="window-controls"]
[cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[cplayer] Set property: shared-script-properties -> 1`

I don't know where check libass version

MKV file with subtitles and fonts
https://krakenfiles.com/view/391d88bd59/file.html

Windows 10 Pro x64
Intel i7 8700

**Comment by TheOneric** [comment]
Thanks, I can reproduce the libass-positioning from your screenshot on both current master (0a3b14a76700b2c1db4d41611199d9aed336c191) and `0.14.0`. It's at 15641 ms.

Sorry if it wasn't clear enough, but for the mpv log to be useful the `-v -v` option should be used *while playing the affected file*; your log doesn't contain any subtitle related lines. However, since I already reproduced it, you don't need to submit a new log.
To answer your question: atm with a static mpv build like yours, you'd need to ask the person, who built the binary about the libass version *(but I already confirmed it affects master, so it doesn't matter)*. It would probably a good idea for us to print the libass version, like we already do for the shapers, which would make this easier.

**Comment by astiob** [comment]
Turns out VSFilter applies \fsp only to text but not to vector drawings.

**Comment by astiob** [comment]
Our handling of \fsp is kinda messy, actually.

I can push a quick fix that just removes it from vector drawing layout, but it’ll stay broken in other ways:

* VSFilter renders \fsp text codepoint-by-codepoint.
* We add \fsp in layout cluster-by-cluster (as determined by the shaper).
* But when we render BorderStyle 3, we add \fsp glyph-by-glyph! (Also as determined by the shaper.) This is probably broken in more respects than just \fsp.
