### ISSUE TITLE
subtitles are blurred

### ISSUE THREAD

**Issue by JerryKit** [libass/libass#492]
When I use this command to add subtitles to the video, the pixels of the subtitles will become as blurry as the video. When the video quality is relatively low, the subtitles are also blurry. I found out that the mp4 video seems to be only Can burn subtitles in.
`ffmpeg -y -i subtitles_w.mp4 -vf "subtitles=new.ass" subtitles_w_y_t.mp4`
When I changed the video format to mvk, the subtitles became plug-in, so that the subtitles were clear. Is there any way to make the subtitles clear without modifying the video format?

**Comment by rcombs** [comment]
Not a libass issue, this is just how video works. If you want your output to be higher-resolution than your input, you're going to need to upscale.

**Comment by JerryKit** [comment]
>

> 这不是视频的问题，这只是视频的工作原理。如果您希望输出的分辨率高于输入的分辨率，则需要进行升级。



> 这不是视频的问题，这只是视频的工作原理。如果您希望输出的分辨率高于输入的分辨率，则需要进行升级。

may I update the library?

**Comment by astiob** [comment]
(Translation issues.)

Not update the library, but upscale the video to a higher resolution. MP4 does not support “soft” ASS subtitles: you are burning the subtitles into the video, which makes it as blurry as the video itself.

(Translating this reply via Google to Chinese and back into English seems to preserve the meaning. I hope it is right.)

**Comment by JerryKit** [comment]
> （翻译问题。）
> 
> 不更新库，而是将视频放大到更高的分辨率。MP4不支持“软” ASS字幕：您正在将字幕刻录到视频中，这使其与视频本身一样模糊。
> 
> （通过Google将此回复翻译成中文，再翻译成英文似乎可以保留其含义。我希望它是正确的。）

Hmm, I compared some mainstream subtitle processing software and found out the reason for the resolution. Thank you for your reply
