### ISSUE TITLE
Ease FriBidi linking on Windows

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#493]
As we discussed on IRC around a month ago, we might want to always define `FRIBIDI_LIB_STATIC` so no one needs to care if libass is linked against static or shared FriBidi *(only relevant for Windows builds)*.
Just to make sure we don't forget about it, here's an issue and a patch. The patch is completely untested and I have no intention to build anything on Windows.

If someone wants to do that, this patch would need to be tested on Windows with both static and dynamic FriBidi before it can be merged. Alternatively we could decide it's better to not hardcode workarounds like this and continue to leave this up to builders to specify which FriBidi is used *(just as it's required for all other libs/executables linking to FriBidi)*.

*The `#ifdef _WIN32` guard may not even be required, at least it seems to work on my machine *(but with a FriBidi predating https://github.com/fribidi/fribidi/commit/46ec6f04820d97159c1008539ed5fc846eefb671)**

```patch
From 5b22ee07dcadbec8fa3fd907a48ccf7deadffdb5 Mon Sep 17 00:00:00 2001
From: Oneric <oneric@oneric.stub>
Date: Thu, 1 Apr 2021 22:06:41 +0200
Subject: [PATCH] Workaround Windows build failures

Because FriBidi exports a variable its headers need to set dllimport
to work with dynamic builds. However, linking against static FriBidi
on Windows will fail when dllimport being set in the header. To allow
use of static FriBidi it is possible to surpress dllimport by defining
the 'FRIBIDI_LIB_STATIC' macro.
FriBidi tries to automatically set this macro in it's pc file, but the
used Cflags.private field is not a standard pkgconfig field and only
supported by one of the many pkgconfig implementations.

However, functions do not require dllimport to be set to work with both
dynamic and static builds. Since libass does only use FriBidi functions,
just always define 'FRIBIDI_LIB_STATIC' on Windows.
---
 libass/ass_compat.h | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/libass/ass_compat.h b/libass/ass_compat.h
index ae16bb7..c1930bb 100644
--- a/libass/ass_compat.h
+++ b/libass/ass_compat.h
@@ -26,6 +26,12 @@
 #define inline __inline
 #endif
 
+// Workaround build failures on Windows with static FriBidi.
+// Possible because we only use FriBidi functions, not variables.
+#if defined(_WIN32) && !defined(FRIBIDI_LIB_STATIC)
+#define FRIBIDI_LIB_STATIC
+#endif
+
 #ifndef HAVE_STRDUP
 char *ass_strdup_fallback(const char *s); // definition in ass_utils.c
 #define strdup ass_strdup_fallback
-- 
2.20.1
```

**Comment by TheOneric** [comment]
Re undefined `extern` variable, from ISO-C99, chapter 6.9:
```
An external definition is an external declaration that is also a definition of a function
(other than an inline definition) or an object. If an identifier declared with external
linkage is used in an expression (other than as part of the operand of a sizeof operator
whose result is an integer constant), somewhere in the entire program there shall be
exactly one external definition for the identifier; otherwise, there shall be no more than
one. 140)
[...]

[footnotes:]
140) Thus, if an identifier declared with external linkage is not used in an expression, there need be no
external definition for it.
```

**Comment by astiob** [comment]
> and apparently with `*.dll` and `*.dll.a` there are two ways to use shared libs on Windows?

The end result is always the same: building a binary with “dynamic linking” on Windows actually statically links in a corresponding import library, which at startup (or upon first use) fills a function pointer table. Microsoft names import libraries `*.lib`, while MinGW apparently prefers `*.dll.a`. But MinGW is also able to generate the import library on the fly (at link-time) from the corresponding `*.dll` if a pregenerated file doesn’t exist. Perhaps this is what was meant when this was mentioned on IRC.

**Comment by astiob** [comment]
> Yet another suggestion was to define `FRIBIDI_ENTRY` rather than `FRIBIDI_LIB_STATIC`

Here’s another, nuclear idea:

```c
#define __declspec
```

**Comment by astiob** [comment]
Committed as c5ee66d.
