### ISSUE TITLE
Specify the font size when ffmpeg renders the ass file

### ISSUE THREAD

**Issue by JerryKit** [libass/libass#495]
When I use the ffmpeg filter to render the ass file into the video, if the fontsize is specified as 16, it seems that the pixels of different fonts are different. Is this because of the font itself? Or does ass have a default ratio conversion for font files?

**Comment by rcombs** [comment]
Your description is unclear (yes, the "pixels are different"?) but if you mean e.g. the ascender-to-baseline height as measured in pixels, then yes, that varies between fonts depending on their metrics. This is expected.
