### ISSUE TITLE
ass_set_fonts_dir performance issues

### ISSUE THREAD

**Issue by alucryd** [libass/libass#510]
Hi all,

I’m running Kodi Matrix via CoreElec on a Khadas Vim 3, and I’ve got a pretty substantial anime collection, with all subtitles and embedded fonts extracted to avoid duplication and wasted space. This means I have a huge Fonts folder (with upwards of 4000 fonts) mounted at /storage/.kodi/media/Fonts over CIFS. For all intents and purposes it works fine, and kodi correctly displays the styled subs via libass. However, it takes around 2 minutes of intense CPU usage before every episode that uses ASS subtitles, apparently ass_set_fonts_dir recursively scans the directory which causes this huge delay.

Would it be possible to improve this, by using a cache or index?

Here's the associated issue over at kodi: https://github.com/xbmc/xbmc/issues/19728

**Comment by astiob** [comment]
You can set up Fontconfig to use (and cache) fonts from that directory and stop passing it to `ass_set_fonts_dir`. Does this sound like a suitable option?

**Comment by TheOneric** [comment]
`ass_set_fonts_dir` is currently merely a convenient wrapper around calling `ass_add_font` for each font file included in the passed directory *(or it subdirectories, or subsubdirectories, …)*. I don't think we plan to make this more complex, but there are better options available already:

What you could do instead if you want to avoid adding all fonts to your system fonts, is use `fontconfig` and pass a custom fontconfig-config to `ass_set_fonts`. This config should include your custom folder, and if you wish to use system-fonts also explicitly include system fonts. Then you'll profit from fontconfig's smarter handling and caching of fonts.

**Comment by alucryd** [comment]
@astiob @TheOneric That's what I wanted to do but unfortunately CoreELEC does not ship with fontconfig so their libass build doesn't have fontconfig support. I would have to build them myself, but I'm not sure I can even get build tools on there, maybe via entware.

**Comment by astiob** [comment]
Surely, then, a CoreELEC issue/thread is in order to ask them to add Fontconfig?
Even if this were to be somehow solved within libass, it would require new CoreELEC builds anyway.

Implementing caching in `ass_set_fonts_dir` essentially means reimplementing Fontconfig. Or requiring Fontconfig at build-time. So we don’t really want to move that way.

Fontconfig is the standard font provider on Linux and the only one in libass, and libass complains very loudly and requires an explicit override if attempted to build without a system font provider. So it seems odd that CoreELEC would insist on building libass without Fontconfig…

**Comment by astiob** [comment]
Does CoreELEC have no system fonts? Seems unlikely, but it would explain why they have no Fontconfig. But if you explain that it helps specifically this very libass use-case, perhaps they may reconsider and add it just for libass?

**Comment by astiob** [comment]
That said, in theory this same thing affects users on other platforms too, if for some reason they keep external collections of fonts. Even if built with both the native font provider and Fontconfig, libass doesn’t support using both at the same time. So _maybe_ we want to introduce a system-font-less instance of Fontconfig into `ass_set_fonts_dir`? and/or allow using multiple font providers at the same time at runtime.

**Comment by alucryd** [comment]
@astiob CoreELEC has no issue tracker, and no one is answered my question on the support forum, so here I am :/

I dug deeper, and it seems I was mistaken. CoreELEC's libass is built with fontconfig support, and it does have one system font, but none of the fontconfig binaries are installed, which makes it quite unusable as is :/ I will try to get the fontconfig binaries somehow, either via entware or by building them myself. Will report back when I do.

**Comment by astiob** [comment]
That’s good to hear!

You don’t actually need the executable binaries. What you need to do is find your `font.conf` file (check the locations [listed here](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html)) and add your custom font directory to that file.

**Comment by alucryd** [comment]
Well, the default kodi directory where I put my fonts was already listed in the fontconfig configuration. I moved them to `~/.local/share/fonts` and successfully rebuilt the cache (got the fontconfig binaries from entware). At first I though it didn't work because when I tried to launch an episode it took its sweet time again. However, it seems it was a one-time thing because now every episode loads instantaneously. Sweet victory!

I guess this can be closed, thanks a lot for your help!

**Comment by astiob** [comment]
> and successfully rebuilt the cache (got the fontconfig binaries from entware)

To be clear: the cache is automatically updated every time you launch the media player with Fontconfig-equipped libass. That’s why you don’t need to find the binaries and manually rebuild the cache.

> At first I though it didn't work because when I tried to launch an episode it took its sweet time again.

This sounds like it rebuilt the cache—so even though you did find binaries, they didn’t help :-) Might be a version difference, I don’t know.

**Comment by alucryd** [comment]
I see, thanks for the heads up!
