### ISSUE TITLE
Compiling problem on macos

### ISSUE THREAD

**Issue by eko5624** [libass/libass#519]
I download the git from https://github.com/libass/libass . But when compiling it , it occurred errors like this(The errors occurred when I run autogen.sh). I don't how to fix this , so I come here for help, thanks.

I'm not a coder , so I'm a newbie on compiling software .  If anyone can tell me how to compiling libass on macos , it will be great .

OS : Bigsur 11.4  MacBook Pro 2017
![1](https://user-images.githubusercontent.com/84926938/120928705-5a1e2680-c718-11eb-90da-501b33b59317.png)
![2](https://user-images.githubusercontent.com/84926938/120928711-64402500-c718-11eb-9094-da81537f54ac.png)
![3](https://user-images.githubusercontent.com/84926938/120928771-b5e8af80-c718-11eb-8a3f-4d079ce607fe.png)

**Comment by TheOneric** [comment]
Our `autogen.sh`-script (currently) expects to be run from within the project directory. If you want to use it you'll first need to `cd` into the repo, in your case `/Users/huangjiajia/Downloads/libass-0.15.1/`. Or alternatively you could just use `autoreconf -ivf /Users/huangjiajia/Downloads/libass-0.15.1/` from any place.
This will generate (or update if you're using a tarball) a `configure` script inside the repo.
Note that the place you call this `configure` script from, will be where the Makefile and  compiled object- and library-files end up, so you likely don't want to call this from your home directory directly. Popular choices are to run it from the repo root itself, a dedicated `build` subdirectory in the repo root, or a `build_libass` directory somewhere outside the repo.

**Comment by astiob** [comment]
Several additional tips:

* If you download an official release tarball from GitHub’s [Releases](https://github.com/libass/libass/releases), you will not need to run `autogen.sh` at all. You will still need to run `configure` and `make`.

    As mentioned above, you should move to a dedicated directory before you run _any_ of these commands. Most often, people use the directory where the source code is:

    ```bash
    cd Downloads/libass-0.15.1
    ./configure
    make
    ```

    or make a new directory just for this.

* You can just install libass via Homebrew: `brew install libass`

**Comment by eko5624** [comment]
> Our `autogen.sh`-script (currently) expects to be run from within the project directory. If you want to use it, you'll first need to `cd` into the repo root, in your case `cd /Users/huangjiajia/Downloads/libass-0.15.1/`. Or alternatively you could just use `autoreconf -ivf /Users/huangjiajia/Downloads/libass-0.15.1/` from any place.
> This will generate (or update if you're using a tarball) a `configure` script inside the repo.
> Note that the place you call this `configure` script from, will be where the Makefile and compiled object- and library-files end up, meaning you likely don't want to call `configure` from your home directory directly. Popular choices are to run it from the repo root itself, a dedicated `build` subdirectory inside the repo root, or a `build_libass` directory somewhere outside the repo.



> Several additional tips:
> 
> * If you download an official release tarball from GitHub’s [Releases](https://github.com/libass/libass/releases), you will not need to run `autogen.sh` at all. You will still need to run `configure` and `make`.
>   As mentioned above, you should move to a dedicated directory before you run _any_ of these commands. Most often, people use the directory where the source code is:
>   ```shell
>   cd Downloads/libass-0.15.1
>   ./configure
>   make
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   or make a new directory just for this.
> * You can just install libass via Homebrew: `brew install libass`

Thanks you guys for reply . I want to compile libass by myself beacause I have a problem with MPV like this https://github.com/mpv-player/mpv/issues/8874

They told me I should report the issue here . And I found this issue : https://github.com/libass/libass/issues/512  I think maybe they are the same issue .  But  the newest git libass have not fixed this .   I think this git https://github.com/libass/libass/tree/54020d43b25e7abe281f8386da1297e38d1d5ede  maybe fix it , so I want to compile 54020d43b25e7abe281f8386da1297e38d1d5ede

**Comment by Robot-DaneelOlivaw** [comment]
`brew install libass --HEAD` works for me.

**Comment by rcombs** [comment]
Doesn't appear that there's an actual issue here, so I'm closing out; if you do run into a runtime issue continuing to happen after 6fc9855, please open a separate GHI.
