### ISSUE TITLE
cache grows too large

### ISSUE THREAD

**Issue by wm4** [libass/libass#53]
This eats memory at the rate of 1 or 2 MB per second: `mpv /dev/zero --demuxer=rawvideo --osd-fractions --osd-level=3`

It didn't happen with the previous libass release.

**Comment by TheOneric** [comment]
I tried to reproduce the reported behaviour:
When running `mpv /dev/zero --demuxer=rawvideo --osd-fractions --osd-level=3` and:
- **not also showing the bottom control panel**, htop reported memory usage for the whole process to climb to 220MiB within the first twenty seconds. I left it running for 33min but memory usage did not increase any further.
- **constantly showing the bottom panel as well**: Mem usage quickly climbed to 280MiB within the first two minutes, after that the increase slowed down noticeably. I left it running for 30min and ended up with a total of 320MiB.

This seems to differ from the originally reported behaviour. Is this issue still up-to date ?

**Comment by MrSmile** [comment]
I've rewritten cache logic so memory consumption should be more stable. 220MB looks reasonable near default cache limit (128MB bitmap + 64MB combine) so there is no problem here. I suspect that bottom panel uses another instance of libass and 320MB is even less than two cache limits.
