### ISSUE TITLE
How to render embedded fonts in ASS Subtitles

### ISSUE THREAD

**Issue by CastagnaIT** [libass/libass#535]
I ask for help
i am working on Kodi,
two users have reported to Kodi forum problems with ass subtitles with embedded fonts,
the problem is that no images are rendered on screen

i do not know exactly what to do or what to check

These are the files:
[__assEmbeddedFontTest1.ass.txt](https://github.com/libass/libass/files/6932122/__assEmbeddedFontTest1.ass.txt)
[__assEmbeddedFontTest2.ass.txt](https://github.com/libass/libass/files/6932123/__assEmbeddedFontTest2.ass.txt)

i have tried load the files with VLC and they seem work correctly

**Comment by TheOneric** [comment]
VLC, mpv, mplayer, recent FFmpeg and our demo/test utilities all use `ass_set_extract_fonts`, thus it's working there. I'm guessing Kodi does not? For historic reasons `ass_set_extract_fonts` defaults to `false`. Beware that due to the same historic inception of the API, currently the fonts are associated with the **library**-handle not the **track**, which may be problematic if a single library handle is used for a large amount of tracks, see #98. *(Once/if this is solved, we may consider changing the default)*

**Comment by CastagnaIT** [comment]
is set in this way:
https://github.com/xbmc/xbmc/blob/19.1-Matrix/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp#L71-L73

but in the method ass_set_extract_fonts there is no info in what values should be set, 1 means True in this case?

**Comment by TheOneric** [comment]
Yes, it's a classic ISO-C89 "boolean", where `0` is `false` and everything else is `true`. You can also use C99-bool values.
See our test-program: https://github.com/libass/libass/blob/1140b6b885c89d37eef13dc1f31f144e9a76a4d7/test/test.c#L102 or https://code.videolan.org/videolan/vlc/-/blob/296e18b19c189a4e7409e7a34f897bb21dfdc1fa/modules/codec/libass.c#L209 .

Are you saying it is still not working eventhough you set `extract_fonts`? If so: Which libass version is in use, please provide logs and are you sure it has nothing to do with the call being dependent on some Kodi-option?

**Comment by CastagnaIT** [comment]
i think i have found the problem sorry for the noise...

there is a problem here:
https://github.com/xbmc/xbmc/blob/19.1-Matrix/xbmc/cores/VideoPlayer/DVDSubtitles/DVDFactorySubtitle.cpp#L33-L68
this code identify the type of subtilte file format
not works good

it read the first 256 lines only and
in the Test1 file not find the type
in the Test2 file for some reason match with this
`else if (sscanf(line, "%d:%d:%d%*c%d --> %d:%d:%d%*c%d", &i, &i, &i, &i, &i, &i, &i, &i) == 8)`
i think become crazy with font metadata

i keep open the Issue for some time, until I can run a test

**Comment by CastagnaIT** [comment]
ok i have tried these are the results

For the 1st case, is rendered very good with his embedded font

For the 2nd case, still no images
this is the log:
```

2021-08-05 11:10:19.541 T:4088     INFO <general>: CDVDSubtitlesLibass: Using libass version 1501000
2021-08-05 11:10:19.542 T:4088     INFO <general>: CDVDSubtitlesLibass: Creating ASS library structure
2021-08-05 11:10:19.542 T:4088     INFO <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2021-08-05 11:10:19.542 T:4088    DEBUG <general>: CDVDSubtitlesLibass: [ass] libass API version: 0x1501000
2021-08-05 11:10:19.542 T:4088    DEBUG <general>: CDVDSubtitlesLibass: [ass] libass source: ea21a3f69d61311f4fb752ec994a8d4fc1c28af0
2021-08-05 11:10:19.543 T:4088    DEBUG <general>: CDVDSubtitlesLibass: [ass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.8.0 (COMPLEX)
2021-08-05 11:10:19.543 T:4088     INFO <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2021-08-05 11:10:19.548 T:4088    DEBUG <general>: CDVDSubtitlesLibass: [ass] Using font provider directwrite
2021-08-05 11:10:19.549 T:4088    DEBUG <general>: Created subtitles parser: SSA Subtitle Parser
2021-08-05 11:10:19.550 T:4088     INFO <general>: CDVDSubtitlesLibass: Creating m_track from SSA buffer
2021-08-05 11:10:19.582 T:4088    DEBUG <general>: CDVDSubtitlesLibass: [ass] Added subtitle file: <memory> (29 styles, 2445 events)
```

**Comment by TheOneric** [comment]
Works as expected in mpv, please create a more verbose log; eg everything but `MSGL_DBG2` (= level `7`) from libass and add an additional log message to the code in Kodi that calls `ass_set_extract_fonts`.
Also acording to your log you are using [a patched libass](https://github.com/libass/libass/commit/ea21a3f69d61311f4fb752ec994a8d4fc1c28af0) which seems to contain many fontprovider related changes *(some perhaps backported from post-0.15.1, but glancing over it at least some are definitely not)*. Please test with upstream-master to make sure none of the patches  interfere.

mpv with libass-master:
```
[sub/ass] libass API version: 0x1501000
[sub/ass] libass source: commit: 0.15.1-41-g5733e1c28b92ebbf090bea8f25e252aa40e0b9c4
[sub/ass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.3.1 (COMPLEX)
[sub/ass] Setting up fonts...
[sub/ass] Using font provider fontconfig
[sub/ass] Done.
[sub/ass] fontselect: (Bahij Nassim, 700, 0) -> BahijNassim-Bold, 0, BahijNassim-Bold
[sub/ass] mangling colors like vsfilter: RGB -> bt.601 limited -> bt.709 bt.601 -> RGB
[sub/ass] fontselect: (DIN Next LT Arabic Light, 400, 0) -> DINNextLTArabic-Light, 0, DINNextLTArabic-Light
[sub/ass] fontselect: (bang whack pow, 400, 0) -> bangwhackpow, 0, bangwhackpow
[sub/ass] fontselect: (esfahan_ar, 400, 0) -> esfahan_ar, 0, esfahan_ar
[sub/ass] fontselect: (Aqlaam, 400, 0) -> Aqlaam-Regular, 0, Aqlaam-Regular
```

**Comment by CastagnaIT** [comment]
i am not sure i am able but i will try to build it

**Comment by CastagnaIT** [comment]
@Paxxi can you give me help/instructions to build libass dll for kodi (Win 64) by using current libass upstream master?
the current instrutions on xbmc github now works

**Comment by Paxxi** [comment]
I tested this, it does not seem to be an issue with libass but rather how Kodi detects subtitle formats. I made a PR to improve our detection and it works fine with testfile 2

**Comment by CastagnaIT** [comment]
Yeh I have already open a pr for this, but was not working, I will try again test later

**Comment by CastagnaIT** [comment]
you have right on regular kodi works
there is something interfere in the libass implementation PR where i am working
