### ISSUE TITLE
Add "margins" override tag

### ISSUE THREAD

**Issue by CastagnaIT** [libass/libass#540]
Assuming that we are using libass to adapt subtitles from other formats
it would be convenient to have a forced tag for margins
in order to set it for each line of subtitles and to be able to draw subtitles on specifics portions of the screen

this is because each subtitle might have different positions
the alternative would be to create an ASS_Style for each subtitle line (where set the margins)
then you would have thousands of styles and I would like to avoid it

i have implemented "margins" forced tag in this way:
https://github.com/CastagnaIT/libass/commit/1145a68f10f0efa89e954b9bcff3765880da4cd0

by doing some tests I have seen that it seems to work correctly also with overlapped subtitles

What I'm asking is, could you have this kind of forced Tag directly in to libass sources?

**Comment by astiob** [comment]
As it happens, this was also a duplicate of #375/#376.

Also, if you only want _positioning,_ there’s `\pos`, of course. Margins are useful for controlling line length.
