### ISSUE TITLE
libass incompatitable with freetype-2.11.0

### ISSUE THREAD

**Issue by Masaiki** [libass/libass#556]
when rendering subtitle with some font like TsangerJinKai01-27533 using libass, freetype (2.11.0) will crash with "metrics is nullptr" with the call stack "af_face_globals_get_metrics, af_loader_load_glyph, af_autofitter_load_glyph, FT_Load_Glyph, ass_glyph_metrics_construct"。 
tested with assrender, subtext (vapoursynth plugin) by @vxzms, and xysubfilter_with_libass (directshow filter) https://github.com/Masaiki/xy-VSFilter/issues/4 and libass version is 0.15.2 and master. Either is compiled with msvc on win10 64bit. Problem disappears with backing freetype to 2.10.4
test font file and ass file are [here](https://drive.google.com/file/d/1uv7lH7WeqmHtgWrMQZqKdl1BEx3q3Y05/view?usp=sharing)

**Comment by astiob** [comment]
I haven’t been able to reproduce this on either Windows or macOS with mpv or a custom program.

Could you run some more experiments to help debug this?

* What if you use FreeType master? (With libass master. Or if using libass 0.15.2 or older, then make sure your test doesn’t contain `\u1` or `\s1`, or it may trigger [another crash](https://github.com/mpv-player/mpv/issues/9227) that’s already fixed.)
* Is FreeType built with or without HarfBuzz? Try the other way ’round.
* What if you change the libass hinting setting via `ass_set_hinting`?

**Comment by Masaiki** [comment]
freetype master works well, so it should be a bug of freetype 2.11.0
close it or leave it to remind not to link freetype 2.11.0?

**Comment by TheOneric** [comment]
fwiw I wasn't able to reproduce this FreeType 2.11.0 with and without HarfBuzz with any Hinting mode on glibc-Linux, using our `profile`-utility and loading the font via Fontconfig.

From the current info, it appears most likely this is an already fixed Windows- and/or configuration-specific FreeType bug.
**If** you want to go the extra mile and make really sure, you could try to bisect this in FreeType to find out which commit fixed and/or introduced it.

**Comment by Masaiki** [comment]
tried to build it with mingw toolchain, also worked well.
