### ISSUE TITLE
Rendering: the font cannot show

### ISSUE THREAD

**Issue by hooke007** [libass/libass#575]
### Screenshots

mpv
![Snipaste_2021-12-01_19-44-18](https://user-images.githubusercontent.com/41094733/144228762-83fdbd3b-a47c-423a-aa1c-9cc97a1ad06e.jpg)
vsfilter

### Description of the issue

The Japanese words cannot be rendered correctly, just showed a point.
Check the specific font below, sub should start from 00:01:30.

### libass version

API version: 0x1502000 commit: f8c71aba5d14afcd6759507bad8a25037fb854b1

### ASS Sample

sub&font
[sample.zip](https://github.com/libass/libass/files/7633413/sample.zip)

### Special Fonts

I uploaded or linked to the required font

### System Information

win11
i7 10875H

### Log

![Snipaste_2021-12-01_19-29-49](https://user-images.githubusercontent.com/41094733/144227455-cad22c57-f9c6-41b4-8c57-3eab35b83399.jpg)

[mpv.log](https://github.com/libass/libass/files/7633453/mpv.log)

**Comment by astiob** [comment]
Thanks for the detailed report!

I believe this is the same issue as #531: the font has no Unicode names or cmaps but instead has Shift-JIS ones, which libass doesn’t support (yet).

**Comment by hooke007** [comment]
Thanks, I'll follow that issue and close it.
