### ISSUE TITLE
Can't find 'Cascadia Code' with PostScript name

### ISSUE THREAD

**Issue by chosungmann** [libass/libass#578]
We can't use the font named [Cascadia Code](https://github.com/microsoft/cascadia-code). Specifying the font as a full name or a PostScript name leads to the fallback font being selected all the time. So I did some digging and it turns out fonts in the form of so-called Multiple Masters always seems to give the problematic result. For the Multiple Masters, each named instance has its own PostScript name, so I think we have to consider it when comparing PostScript names.

I attached the subtitle and the fonts I used for testing: [test.zip](https://github.com/libass/libass/files/7717094/test.zip)

**Result from [the master branch](https://github.com/libass/libass/tree/7732119e53ef235942b9f4820f70a72c1d6045c2):**

```console
test.c: Available font providers (4): 'None', 'Autodetect', 'CoreText', 'Fontconfig'.
libass: libass API version: 0x1502000
libass: libass source: commit: 0.15.2-30-gc75017b4e7ad686009c0ac14b7d9b22db4811aa1
libass: Raster: FreeType 2.11.0
libass: Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 3.1.2 (COMPLEX)
libass: Initialized
libass: Using font provider coretext
libass: File size: 889
libass: [0x600002cac000] Style: Default,CascadiaCodeItalic-Bold,52,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0
libass: Track treated as legacy ffmpeg sub.
libass: Added subtitle file: 'subtitle.ass' (2 styles, 5 events)
libass: fontselect: Using default font family: (CascadiaCodeItalic-Bold, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
libass: fontselect: (CascadiaCodeItalic-Bold, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
```

**Result from [the master branch](https://github.com/libass/libass/tree/7732119e53ef235942b9f4820f70a72c1d6045c2) with #579**

```console
test.c: Available font providers (4): 'None', 'Autodetect', 'CoreText', 'Fontconfig'.
libass: libass API version: 0x1502000
libass: libass source: commit: 0.15.2-30-gc75017b4e7ad686009c0ac14b7d9b22db4811aa1
libass: Raster: FreeType 2.11.0
libass: Shaper: FriBidi 1.0.11 (SIMPLE) HarfBuzz-ng 3.1.2 (COMPLEX)
libass: Initialized
libass: Using font provider coretext
libass: File size: 889
libass: [0x600001474080] Style: Default,CascadiaCodeItalic-Bold,52,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0
libass: Track treated as legacy ffmpeg sub.
libass: Added subtitle file: 'subtitle.ass' (2 styles, 5 events)
libass: fontselect: (CascadiaCodeItalic-Bold, 400, 0) -> /Users/${UserID}/Library/Fonts/CascadiaCodeItalic.ttf, -1, CascadiaCodeItalic-Bold
2 images blended
```

**Comment by TheOneric** [comment]
As pointed out in #579, the attached “Cascadia Code” is actually an OT Variable Font not a “Multiple Master” font. Thus this issue duplicates #386.
Thanks for reporting and the patch though!
