### ISSUE TITLE
fontselect get the wrong weight in variable fonts on MacOS.

### ISSUE THREAD

**Issue by Tsukimeizi** [libass/libass#584]
I use mpv and set osd-font='SF Pro', fontselect can not get weight 700 correctly which should be "SFPro-Bold"

"SF Pro" is a variable font (SFPro.ttf), you can download from https://developer.apple.com/fonts/

[osd/libass] fontselect: (SF Pro, 400, 0) -> /Library/Fonts/SFPro.ttf, -1, SFPro-Regular
[osd/libass] fontselect: Using default font family: (sans, 400, 0) -> /Library/Fonts/SFPro.ttf, -1, SFPro-Regular
[osd/libass] fontselect: (sans, 400, 0) -> /Library/Fonts/SFPro.ttf, -1, SFPro-Regular
[osd/libass] fontselect: Using default font family: (sans, 700, 0) -> /Library/Fonts/SFPro.ttf, -1, SFPro-Regular
[osd/libass] fontselect: (sans, 700, 0) -> /Library/Fonts/SFPro.ttf, -1, SFPro-Regular

When I try osd-font='SF Pro Text', which is not a variable font, fontselect gets weight 700 correctly.

[osd/libass] fontselect: (SF Pro Text, 400, 0) -> /Library/Fonts/SF-Pro-Text-Regular.otf, -1, SFProText-Regular
[osd/libass] fontselect: Using default font family: (sans, 400, 0) -> /Library/Fonts/SF-Pro-Text-Regular.otf, -1, SFProText-Regular
[osd/libass] fontselect: (sans, 400, 0) -> /Library/Fonts/SF-Pro-Text-Regular.otf, -1, SFProText-Regular
[osd/libass] fontselect: Using default font family: (sans, 700, 0) -> /Library/Fonts/SF-Pro-Text-Bold.otf, -1, SFProText-Bold
[osd/libass] fontselect: (sans, 700, 0) -> /Library/Fonts/SF-Pro-Text-Bold.otf, -1, SFProText-Bold

**Comment by astiob** [comment]
Thanks for the report!

libass does not yet support variable fonts. The main issue ticket tracking this is https://github.com/libass/libass/issues/386.

For macOS system fonts specifically, there is a patch in https://github.com/libass/libass/pull/579 that makes them work somewhat, but it may break other things.

I’ll close this as a duplicate report, but do keep an eye on #386. If you think this is a different issue, feel free to reopen and add more details.
