### ISSUE TITLE
i386 build fails with “illegal text-relocation”

### ISSUE THREAD

**Issue by yongrongyabu** [libass/libass#586]
ld: illegal text-relocation to 'words_tile16' in x86/.libs/rasterizer.o from '_ass_fill_halfplane_tile16_sse2' in x86/.libs/rasterizer.o for architecture i386 clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TheOneric** [comment]
We need more info:
 - Which compiler and which linker were you using?
 - Which **exact** version of libass did you try to compile?
 - Which version of NASM did you use (`nasm --version`)?
 - Which platform were you compiling on and which platform were you compiling for?
 - Please provide the output of the configuration command you ran.
 - Please run `make V=1` after the configuration and provide also its output.

**Comment by MrSmile** [comment]
Looks like missing `PIC` define for `nasm`, try `ASFLAGS=-DPIC=1` option for configure.

**Comment by brad0** [comment]
Is this related to 6409945b1c9bb626cca5a5303a7cac16429c5a47?

**Comment by TheOneric** [comment]
> Is this related to 6409945b1c9bb626cca5a5303a7cac16429c5a47?

Possible. My guesses currently are:
 - a libass from before the mentioned commit was used
 - libass is up-to-date but the system’s compiler and linker are (somehow) configured to produce and  **require**  pic/pie by default even without flags, creating a mismatch with NASM doing so only when a flag is passed
 - there is some configuration bug on our side                        
 - there is a bug somewhere else (eg a linker or autoconf bug)


In the first case setting `ASFLAGS=-DPIC=1` during config will work. In the second case it would too, but passing `--with-pic` to `configure` is the more idiomatic solution. *(Related to the second case: on modern ix86 Debian, PIC/PIE is created by default and a *harmless warning* appears regarding not being fully PIC when building the static lib without `--with-pic`)*

Without more info, there’s no way to tell.

**Comment by TheOneric** [comment]
Since there's not enough info to go on and OP hasn't responded in a month, I'll close the issue. Can be reopened if the requested info is supplied.
