### ISSUE TITLE
Many API-users ignore ass_set_storage_size leading to incorrect rendering

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#591]
As we noticed recently on IRC while discussing commit https://github.com/libass/libass/commit/d60f2dce1dcafaed0e21406213e66072f3036752 (October 2020), which changed the behaviour when `ass_set_storage_size` was never called, many API-users ignore `ass_set_storage_size`.
We briefly thought, that before the above commit API-users who're rendering at storage resolution would still have gotten the correct behaviour by accident — but that was never the case for transforms.

This leads to incorrect results and is particular bad for Aegisub as it means sub authors will work with wrong results and moreover if the final result is only checked in a similarly bugged player (e.g. VLC) the error will not show itself even outside of Aegisub.

We should probably more prominently point out the need for `ass_set_storage_size` in our docs *(EDIT_ now done)* and send issues/patches to ensure at least the most prominent libass users do call `ass_set_storage_size`. We should also suggest to backport the fix to LTS/stable releases where applicable.

**mpv** and **gstreamer** are **not affected** due to calling `ass_set_storage_size`; below is an incomplete list of affected programs:

 - [x] **Aegisub**:
       There are also AviSynth- and cli-interfaces to its csri; I don't know if they always render at video resolution.
       At least the most prominent, active'ish forks should be fixed:
   - [x] [wangqr](https://github.com/wangqr/Aegisub)
   - [x] [TypesettingTools](https://github.com/TypesettingTools/Aegisub)
   - [x] [DC](https://github.com/Ristellise/AegisubDC), is derived from wangqr afaik ~~so a fix there should eventually end up in DC anyway, but pinging DC is probably a good idea~~
      Mysteriously the last AegisubDC binaries v9215 already show the correct rendering with its libass backend, eventhough the sourcecode in git (https://github.com/Ristellise/AegisubDC/commit/35db2ad6c0b64599249175ed6904010f200e0be2) does never call `ass_set_storage_size`. Also AegisubDC is now basically unmaintained.
      **Update:** As it turns out, the 9215B binary build apparently already includes the patch, eventhough it was neveer pushed to the public git repo, see: https://github.com/Ristellise/AegisubDC/issues/54
 - [x] **ffmpeg**: always renders at (what will become after filters?) video resolution, already has `original_size` parameter. Fix included in master after (not including) 5.0; got backported to 5.0.1 and several 4.x releases.
 - [x] **VLC**: was broken, matched the buggy behaviour in Aegisub and is a common player increasing the chances the bug got accidentally relied upon.
    Now fixed in master (4.x) and also backported to the 3.0.x branch for inclusion in the next stable release.
 
 - [ ] **Bino**: does not call `ass_set_storage_size`, also has other issues with subtitles
 - [x] **AviSynth**: does not call `ass_set_storage_size` afaict, no idea what it does otherwise. Fixed by: https://github.com/pinterf/assrender/commit/93f8f860484b2f75ddd56b1db7e72c73b9090cd6
 - [x] **VapourSynth**: https://github.com/AmusementClub/assrender/commit/26a0d286920e0dff9784b6f6c6d85248993dee13
 - [x] **Kodi/xbmc**: https://github.com/xbmc/xbmc/pull/21037
 - [x] **mplayer**: http://www.mplayerhq.hu , fix included in MPlayer 1.5 release
 
 Additionally I noticed that bubblesub does set sorage_size, but the values it chooses appears problematic, at least going by variable names and the limited section of code I looked at:
 - [x] **bubblesub**:  [potentially problematic use of sizes](https://github.com/bubblesub/ass_renderer/blob/626e4f09f83d52408b6df634da372c3fe782631a/ass_renderer/renderer.py#L59-L63)

Longer term we might want to provide a script to rescale subs or define an extension usable by sub-authors to override the video size passed via `ass_set_storage_size` but fixing the regressions has imho priority and getting programs to `ass_set_storage_size` will remain required for subs not using this extension anyway.

**Comment by TheOneric** [comment]
Bubblesub-issue: https://github.com/bubblesub/bubblesub/issues/85

**Comment by TheOneric** [comment]
VLC issue: https://code.videolan.org/videolan/vlc/-/issues/26634

**Comment by realfinder** [comment]
I assume by avisynth you mean [assrender plugin](http://avisynth.nl/index.php/AssRender)

and yes, it has the same bug as vlc

![image](https://user-images.githubusercontent.com/2512153/154818540-f0358f2e-6ee4-4b73-95f5-97d1e0737f08.png)

```
ColorBarsHD(width=1280, height=720, pixel_type="YV24")
assrender("test_1080p.ass")
```

so you we need someone open issue in https://github.com/pinterf/assrender/issues or pull request so @pinterf can fix it

**Comment by TheOneric** [comment]
@realfinder: Your code snippet suggests you used a (non-anamorphic) 1280×720 with the sample “1080p” script from the VLC issue. This is incorrect as it would lead to a different storage size even if AviSynth’s assrenderer would use `ass_set_storage_size`.  

> so we need someone open issue in https://github.com/pinterf/assrender/issues or pull request so @pinterf can fix it

Feel free to do so and link the issue/patch here. And if there are other active assrenderer implementations besides pinterf’s theyy'll need to be informed/patched too; I'm not familiar with the situation of AviSynth plugins. But please make sure to test with the actual videofiles accompanying the sample subs so that it has the correct storage and display size.

**Comment by realfinder** [comment]
ok oo I used bubblesub samples
```
ffms2("sample.mkv")
assrender("sample.ass")
```
![image](https://user-images.githubusercontent.com/2512153/154822345-06f5c84a-4bd0-453f-b876-06fa50b899e4.png)

> And if there are other active assrenderer implementations besides pinterf’s they'll need to be informed/patched too

there are but they are not active

**Comment by TheOneric** [comment]
Aegisub patches/issues:

 - **wangqr**: https://github.com/wangqr/Aegisub/pull/134
 - **TypesettingTools**: https://github.com/TypesettingTools/Aegisub/pull/147
 - **AegisubDC**: *(will open an issue after at least one of the patches got merged)*

**Comment by TheOneric** [comment]
bino issue: https://github.com/marlam/bino-mirror/issues/13
