### ISSUE TITLE
New tags for limited math support

### ISSUE THREAD

**Issue by NetaP495L** [libass/libass#592]
I'm making subtitles for math videos in which super/subscript, square root, big fractions and 2x2 matrix are common. Currently I use `{\pos}` to manually adjust the position if there's no specified super/subscript Unicode character; use a tick ✓ to substitute square root.

I propose to add `{\sub}`, `{\sup}` and `{\sqrt}` tag. For the sake of readability, and avoid introducing math shaping engine, nesting of those three tags (which is rare in subtitle) could be forbidden, e.g. a^x^2, a^(x_3), a_x_4, sqrt(x^4) and sqrt(sqrt(16)). If necessary I will just write one layer in plain text, for example `sqrt(x{\sup1}4{\sup0})`

![](https://s3.bmp.ovh/imgs/2022/02/529535cc9e608b70.png)

However the combination of `{\sup}` and `{\sub}` should be allowed, e.g. SO_4^2+ could be either expressed as `SO{\sub1}4{\sub0\sup1}2+{\sup0}` (literally the second) or `SO{\sup1}2+{\sup0\sub1}4{\sub0}` (literally the third). Moreover, when `{\sub}` and `{\sup}` are appended to the same character, the left border of `{\sub}` and `{\sup}` should be aligned (the left one).

Furthermore, with some `{\fsp}` hacks, big fractions and 2x2 matrix like these two

![](https://s3.bmp.ovh/imgs/2022/02/f681ae11b98df592.png)

could be descibed by `{\sub}` & `{\sup}` if they can append to a space.

**Comment by rcombs** [comment]
We're not adding new tags to the existing format, but this is reasonable to consider for a future format version, expected around early 2023.

Also, you might find it useful to know that Unicode does actually have a square-root character: √ (U+221A).

**Comment by TheOneric** [comment]
Moved suggestion to [ASS v.5.0 wiki article](https://github.com/libass/libass/wiki/ASS-v5.0#additional-suggestions), to make it easier to find it whenever ASSv5 will be worked on.
