### ISSUE TITLE
Help request GUI subtitle bar + vertical margin + ass_set_line_position

### ISSUE THREAD

**Issue by CastagnaIT** [libass/libass#598]
On Kodi we have the subtitle calibration bar (horizontal white line inside the square box in the screenshot)
when you move this bar up/down you can move the subtitle text position
and this is done by set the % value to `ass_set_line_position`

`position % = 100.0 - SubtitleBarPosPxFromTop * 100.0 / screenResHeight`

but by default we want to set also the vertical margin e.g. 75px (to the style),
OFC add this margin will make the text shifted from the subtitle bar, see space between bar and text on screenshot:
![immagine](https://user-images.githubusercontent.com/3257156/155331384-8a2a58de-10de-4e16-a5ac-eadc7d30560d.png)

where instead the goal is keep the bar in line with the text baseline,
this is my first attempt that i have tried so make some scaling to the vertical margin,
then calculate the difference to add into the position %
```c++
double subPosPx = SubtitleBarPosPxFromTop;
double verticalMargin = 75.00;
double scaledMargin = verticalMargin  / PlayResY * screenResHeight;
subPosPx -= verticalMargin - scaledMargin;
position % = 100.0 - subPosPx * 100.0 / screenResHeight;
```
this more or less works, the subtitle bar match the text, but it is not perfect for all screen resolution cases, sure there is something wrong in this calulation see:
![Animation](https://user-images.githubusercontent.com/3257156/155520026-ae8d7aed-62e0-4ad4-aa65-3a23b0f801e5.gif)

if you look at the bar when it is upper screen there is more space between bar and text, that means something wrong in my calculation,
some suggest to have a right calculation?

UPDATE:
for now i have used the (updated) workaround above to try match the GUI calibration bar to the text although it is not perfect,
it would be nice to have a more stable solution or a helper method

**Comment by TheOneric** [comment]
I'm assuming `` is sin scaled-video coordinates and `verticalMargin` is the margin straight from ASS in `PlayRes`-canvas coordinates. Your calculation is:
```
double subPosPx = SubtitleBarPosPxFromTop;
double verticalMargin = 75.00;
double scaledMargin = verticalMargin  / PlayResY * screenResHeight;
subPosPx -= verticalMargin - scaledMargin;
position % = 100.0 - subPosPx * 100.0 / screenResHeight;
```

The second last line seems odd. Why are you subtracting the difference of the canvas-coordinate margin and the video-coordinate margins? Why not *only* the video-coordinate margins?

Though, in an previous version you wrote:
>  this solution will works only with adapted subtitles (of other formats) and not with propetary ASS/SSA due to their custom margins but better than nothing

Where the non-working part presumably refers to ASS-typesetting being broken. If you only expect to use this with converted subs, then why even try to mix margins and the API-set vertical position instead of just setting margins to zero when using `ass_set_line_position`? This would make things simpler.

**Comment by CastagnaIT** [comment]
SubtitleBarPosPxFromTop is position referred to the current screen height resolution (no black bars so full height)
verticalMargin is the same value of what that is set to style->MarginV
screenResHeight is the current screen height in full, black bar not considered

> The second last line seems odd. Why are you subtracting the difference of the canvas-coordinate margin and the video-coordinate margins? Why not only the video-coordinate margins?

hehe I'd like to give you an answer but I don't know because I discovered it by accident, it "works" but is also for this i opened this Issue, and if try remove the subtracting the difference the value will be too large and the GUI bar not match the text

do not take in account of this my old comment (after removed):

> this solution will works only with adapted subtitles (of other formats) and not with propetary ASS/SSA due to their custom margins but better than nothing

for this i have solved by using it only when ASS style overrides are enabled, in this way works as expected

**Comment by CastagnaIT** [comment]
just a note i have tried follow the ass code for MarginV here:

https://github.com/libass/libass/blob/875ba300a91781253b24c6bb2c479c2b5e8e92df/libass/ass_render.c#L2753-L2766

maybe im wrong, it seems that in addition to scaling there are other factors but i dont know

**Comment by TheOneric** [comment]
By the looks of it, the line_pos displacement is in percent of the height that's available to the even during collision handling, i.e. without the Margin (and the displacement only applies to bottom subtitles). You could, try this:
```C
double subPosPx = SubtitleBarPosPxFromTop; // Target Height
double verticalMargin = 75.00; // Query from ASS track (both style and event!)
double scaledMargin = verticalMargin  / PlayResY * screenResHeight;
// x * (screenResHeight - scaledMargin) + scaledMargin = subPosPx
double x = (subPosPx - scaledMargin) / (screenResHeight - scaledMargin);
ass_set_line_position(priv, x);
```

But again: If you want to set them to a very specific height just zeroing the vertical margin via style overrides beforehand seems simpler.

**Comment by CastagnaIT** [comment]
tried proposed code but not works

tried aso revert this:
`double x = (subPosPx - scaledMargin) / (screenResHeight - scaledMargin);`
as:
`double x = (screenResHeight - scaledMargin) / (subPosPx - scaledMargin);`
because return a reversed value that move the text in the wrong direction

the `x` output a value extremely low 1% and when i move the subtitle bar position also lower than 1%
so the text mostly does not move as i move the bar

**Comment by TheOneric** [comment]
> return a reversed value that move the text in the wrong direction

Oups, forgot to adjust the coordinate. Use `double subPosPx = screenResHeight - SubtitleBarPosPxFromTop`

**Comment by CastagnaIT** [comment]
tested but now is even worse the % value output is kept the same while you move the bar so the text not move at all

**Comment by CastagnaIT** [comment]
i have investigated again by re-checking your proposed changes above
and i have now managed how to make it work well

i have done some changes due to need to implement also overscan
this is the results

```c++
// screenResHeight == screen height deducted from overscan differences
// Only applies to bottom subtitles
double subPosPx = SubtitleBarPosPxFromTop - Overscan.top;
double verticalMargin = 75.00; // Query from ASS track (both style and event!)
double scaledMargin = verticalMargin  / PlayResY * screenResHeight;
double frameHeightDiff = screenResHeight  - scaledMargin;
double x = (subPosPx - scaledMargin) / frameHeightDiff + scaledMargin / frameHeightDiff;
ass_set_line_position(priv, 100 - x * 100);
```

thanks for the help

**Comment by TheOneric** [comment]
Glad it worked out
