### ISSUE TITLE
[Feature request v5] Justify text

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#602]
It would be usefull if we could justify the text.

Here is what I want to do:
![image](https://user-images.githubusercontent.com/34408507/157722514-5ea0ea7e-957c-4e2b-91cc-90584a02ea50.png)

Here is what we can currently achive
With \an1, \an4, \an7
![image](https://user-images.githubusercontent.com/34408507/157722651-7e55154f-a9f4-44d4-b3b5-914d92a63033.png)

With \an3, \an6, \an9
![image](https://user-images.githubusercontent.com/34408507/157722826-f5ef426b-0bdb-47c6-9d43-c15039603b6c.png)

**Comment by TheOneric** [comment]
Moved suggestion to [ASS v.5.0 wiki article](https://github.com/libass/libass/wiki/ASS-v5.0#additional-suggestions), to make it easier to find it whenever ASSv5 will be worked on.
