### ISSUE TITLE
Negative Fontsize: assert fail in outline_stroke

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#610]
[Once](https://github.com/libass/libass/issues/397)  [again](https://github.com/libass/libass/issues/431) this assert fails on some inputs.

```
libass/ass_outline.c:1498: outline_stroke: Assertion `rad >= eps && rad <= OUTLINE_MAX' failed.
```
Tested on top of cbeea94fc70a6322ecce4c4ff30bef2a9028c18a, see attached archive for three sample files triggering the failure and info on the selected fonts: [assert-radeps-fail.zip](https://github.com/libass/libass/files/8477053/assert-radeps-fail.zip)

If asserts are disabled, a stack-overflow occurs in `process_quadratic` instead *(old versions of libass just produced slightly odd renderings and did not crash)*.

EDIT: The `fuzzer_w3:id:000159,sig:04,src:000968+000719,time:452375,execs:57769,op:splice,rep:16` sample already hits UB before failing the assert which might cause the issue for this particular case. The other two samples do not hit any UB afaict.
For this one sample, the preceeding UB is:
```
libass/ass_render.c:1108:42: runtime error: shift exponent 9999999 is too large for 32-bit type 'int'
```

**Comment by MrSmile** [comment]
Cases `id:000000` and `id:000248` are unsanitized (negative) `Fontsize` style field. I think we should do the same as [for other fields](https://github.com/libass/libass/blob/master/libass/ass.c#L557-L561). Case `id:000159` is indeed [an UB with excessive shift](https://github.com/libass/libass/blob/master/libass/ass_render.c#L665). I think we should forget about emulating VSFilter UB in this case and fix it by replacing with corresponding `ldexp()` call.

**Comment by TheOneric** [comment]
> Case id:000159 is indeed [an UB with excessive shift](https://github.com/libass/libass/blob/master/libass/ass_render.c#L665).

For reference, I do not observe an excessive shift at the linked location but at `libass/ass_render.c:1108` for the `id:000159` sample with `profile` or my fuzzing consumer — for other samples excessive and negative shifts do occur at `libass/ass_render.c:665` though, see #612.

**Comment by TheOneric** [comment]
> (negative) Fontsize style field. I think we should do the same as [for other fields](https://github.com/libass/libass/blob/master/libass/ass.c#L557-L561) [i.e. `FFMAX(val, 0)`].

Unlike for the linked other fields I didn't spot such a bounding anywhere in guliverkli2’s source code. I guess we'll need to do a pratical test to see how VSFilter (GDI?) behaves for negative font sizes.

**Comment by TheOneric** [comment]
VSFilter/GDI appear to use the absolute value of the font size when actually rendering but keeps it negative before *(relevant for `\fs+`, `\fs-`)*. Below a test-file and screenshots. xy-VSFilter as bundled in Aegisub r8250 and VSFilterMod as bundled in Aegisub r8942 agree on the rendering; couldn't get MPC-HC's ISR to work.

![aegi-r8250_xy-VSF](https://user-images.githubusercontent.com/1668471/163885296-7569a942-d295-4937-b3da-9d57ed3e6145.png)
![aegi-r8250_xyVSF__fs+-](https://user-images.githubusercontent.com/1668471/163885311-b86aec5b-127d-4b3e-af7d-362162340532.png)

```ini
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

Video File: ?dummy:25.000000:40000:1280:720:47:191:225:
Video AR Value: 1.777778

[Aegisub Project Garbage]
Video File: ?dummy:25.000000:40000:1280:720:47:191:225:
Video AR Value: 1.777778

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: sm48,DejaVu Sans,-48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: sm16,DejaVu Sans,-16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: sm4,DejaVu Sans,-4,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: sm1,DejaVu Sans,-1,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: Default,DejaVu Sans,100,&H0011FF11,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: s48,DejaVu Sans,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: s16,DejaVu Sans,16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: s4,DejaVu Sans,4,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: s1,DejaVu Sans,1,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,2,8,10,10,10,1
Style: bordstyle3,DejaVu Sans,42,&H00EEEEEE,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,3,0,0,8,10,10,10,1
Style: s22,DejaVu Sans,22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,9,10,10,10,1
Style: sm22,DejaVu Sans,-22,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,0,7,10,10,10,1


[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,sm48,,0,0,0,,{\an7}A
Dialogue: 0,0:00:00.00,0:00:05.00,sm48,,0,0,0,,{\an7}B
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7}{\fs-48}D
Dialogue: 0,0:00:00.00,0:00:05.00,sm48,,0,0,0,,{\an7}C
Dialogue: 0,0:00:00.00,0:00:05.00,sm16,,0,0,0,,{\an7}E
Dialogue: 0,0:00:00.00,0:00:05.00,sm16,,0,0,0,,{\an7}F
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7}{\fs-16}G
Dialogue: 0,0:00:00.00,0:00:05.00,sm16,,0,0,0,,{\an7}H
Dialogue: 0,0:00:00.00,0:00:05.00,sm4,,0,0,0,,{\an7}I
Dialogue: 0,0:00:00.00,0:00:05.00,sm4,,0,0,0,,{\an7}J
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7}{\fs-4}K
Dialogue: 0,0:00:00.00,0:00:05.00,sm4,,0,0,0,,{\an7}L
Dialogue: 0,0:00:00.00,0:00:05.00,sm1,,0,0,0,,{\an7}M
Dialogue: 0,0:00:00.00,0:00:05.00,sm1,,0,0,0,,{\an7}N
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an7}{\fs-1}O
Dialogue: 0,0:00:00.00,0:00:05.00,sm1,,0,0,0,,{\an7}P

Dialogue: 0,0:00:00.00,0:00:05.00,s48,,0,0,0,,{\an9}A
Dialogue: 0,0:00:00.00,0:00:05.00,s48,,0,0,0,,{\an9}B
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an9}{\fs48}D
Dialogue: 0,0:00:00.00,0:00:05.00,s48,,0,0,0,,{\an9}C
Dialogue: 0,0:00:00.00,0:00:05.00,s16,,0,0,0,,{\an9}E
Dialogue: 0,0:00:00.00,0:00:05.00,s16,,0,0,0,,{\an9}F
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an9}{\fs16}G
Dialogue: 0,0:00:00.00,0:00:05.00,s16,,0,0,0,,{\an9}H
Dialogue: 0,0:00:00.00,0:00:05.00,s4,,0,0,0,,{\an9}I
Dialogue: 0,0:00:00.00,0:00:05.00,s4,,0,0,0,,{\an9}J
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an9}{\fs4}K
Dialogue: 0,0:00:00.00,0:00:05.00,s4,,0,0,0,,{\an9}L
Dialogue: 0,0:00:00.00,0:00:05.00,s1,,0,0,0,,{\an9}M
Dialogue: 0,0:00:00.00,0:00:05.00,s1,,0,0,0,,{\an9}N
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an9}{\fs1}O
Dialogue: 0,0:00:00.00,0:00:05.00,s1,,0,0,0,,{\an9}P

Dialogue: 0,0:00:00.00,0:00:15.00,bordstyle3,,0,0,0,,{\an2}Borderstyle=3 Outline=0{test if classic/xy VSF or MPC-HC ISR?}

Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,Style Neg:
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs-36}W{ 57.2}
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs-22}W{ 26.4}
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs-11}W{  2.2}
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,W
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs+11}W{ -46.2}
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs+22}W{ -70.4}
Dialogue: 0,0:00:05.01,0:00:10.00,sm22,,0,0,0,,{\fs+36}W{ -101.2}

Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\an9}Style Pos:
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs-36}W{ -57.2}
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs-22}W{ -26.4}
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs-11}W{  -2.2}
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,W
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs+11}W{ -46.2}
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs+22}W{ -70.4}
Dialogue: 0,0:00:05.01,0:00:10.00,s22,,0,0,0,,{\fs+36}W{ 101.2}

```

**Comment by Nevcairiel** [comment]
In case you are curious, Windows is likely the one dealing with the negative font size, doing this:

size > 0 -> The font mapper transforms this value into device units and matches it against the cell height of the available fonts.
size < 0 -> The font mapper transforms this value into device units and matches its absolute value against the character height of the available fonts.

So negative font sizes use character height for font selection, while positive ones use cell height.

**Comment by astiob** [comment]
Ah, of course; this is [clearly documented for `LOGFONT`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfontw). Thanks!

(It’d be best to move further discussion to #618, though.)
