### ISSUE TITLE
Rendering: libass does not use the same font than VSFilter

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#613]
### Screenshots

It is useless in this case.

### Description of the issue

libass does not respect vsfilter font used.
Like you can see in the Additional info section, I give what I write in the \b tags and which font is been displayed.

I test it with AegisubDC 9214 and I use subtitle provider vsfiltermod_textsub and of course, libass.

Of course, this is only an example. VSFilter does maybe some other choice when x font weight is not installed.
In my example, all the possible font weight are available.

### libass version

AegisubDC 9214

### Is it a regression?

I don't know

### ASS Sample

See the MODDED_FONT.zip file

### Special Fonts

Here are the modded font I used and the .ass: [MODDED FONT.zip](https://github.com/libass/libass/files/8508672/MODDED.FONT.zip)
### System Information

OS: Windows 10
CPU: i5-7600

### Additional info

**VSFilter**

\bVALUE --> FONT_WEIGHT

b0 --> 400
b1 --> 700
b2-b99 --> 400
b100-b149 --> 100
b251-b258 --> 100
b150-b250 --> 200
b351-b358 --> 200
b259-b349 --> 300
b451-b461 --> 300
b350 --> 400
b359-b450 --> 400
b551-b561 --> 400
b462-b550 --> 500
b551-b661 --> 500
b562-b650 --> 600
b751-b758 --> 600
b662-b749 --> 700
b750 --> 800
b759-b850 --> 800
b951-b1050 --> 800
b851-b950 --> 900
b1051-infinite --> 900

**libass**

\bVALUE --> FONT_WEIGHT

b0 --> 400
b1 --> 700
b2 à b99 --> 400
b100-b149 --> 100
b150-b250 --> 200
b251-b349 --> 300
b350-b450 --> 400
b451-b550 --> 500
b551-b650 --> 600
b651-b749 --> 700
b750-b850 --> 800
b851-infinite --> 900

**Comment by astiob** [comment]
> and I use subtitle provider vsfiltermod_textsub

It shouldn’t matter in this instance, but for future reference, please use “CSRI/vsfilter_textsub”. VSFilterMod is a separate beast that deviates from VSFilter in multiple ways and is explicitly meant only for hardsubs, where renderer compatibility is not a concern.

---

@rcombs IIRC you looked at GDI’s font selection including specifically faux bold. Does this happen to ring any bells?

Without having done any tests of my own, the reported list looks like GDI does take the possibility of faux bold into account during font selection, whereas we don’t: we first select the closest weight match available and only then see if faux bold needs to be applied.

The exact numbers are funky, though.

**Comment by rcombs** [comment]
Yup, it all comes down to how the score penalty for weight is calculated:
- Take the absolute difference between the target weight and the candidate weight
- If the target weight is _greater_ than the candidate weight by >150 (i.e. the candidate is eligible for faux-bold), subtract 120
- Run this intermediate score through `(((((((x)<<3)+(x))<<3))+(x))>>8)` (`x` is a 32-bit signed integer) to get the final penalty value

So at e.g. b251, we have 2 candidate values: 100 and 200. 200 isn't eligible for faux-bold, but 100 is, so our intermediate scores are 31 and 51. 
At b259, 100/200/300 get intermediate values of 39, 59, and 41. This yields final penalty scores of 11, 16, and 11, a tie between 100 and 300. It looks like the tie should be broken by choosing the font that was loaded first.

I'm not sure what determines load order, but I'd imagine there's a decent chance it varies between machines. Might be stable when the font is loaded from a Matroska attachment, though… In any case, it should be very rare, so I'm inclined to say we should just match this scoring calculation and have ties go to the first result we find, which should be good enough for any realistic case.

**Comment by moi15moi** [comment]
Hi,

Here is another example.

I have installed all font weight except 700 (so, i have 100, 200, 300, 400, 500, 600, 800, 900).
I have this line: {\fnRaleway\b1}boo

vsfilter give me the 500 font
libass give me the 800 font.

**Comment by rcombs** [comment]
The calculation I described is what GDI (and thus VSFilter) does; libass currently just picks the closest one.

**Comment by moi15moi** [comment]
Here is an another example with italic.

First font:
Family name: Noto Sans
Weight: 500
Italic: False

Second font:
Family name: Noto Sans
Weight: 400
Italic: True

VSFilter pick up the Second font, but libass pick the first font.

**Comment by moi15moi** [comment]
Actually, there is not only 400 and 700.
There is 300, 400, 500, 600, 700.

VSFilter just ignored them these weight.

Why do you say that the 500 is faux bold? It seems like the 400, but the rendering seems just a little broken.

**Comment by astiob** [comment]
> Actually, there is not only 400 and 700.
> There is 300, 400, 500, 600, 700.

Not as “Akshar” though, as you know from the fact you can’t select them via `\b600` etc. Each of them is only accessible via its own full name.

I’m not yet sure how exactly GDI picks up the 700-weight variant as the bold face of “Akshar”, but this behaviour matches our existing understanding of GDI’s handling of variable fonts as documented in https://github.com/libass/libass/issues/386.

> Why do you say that the 500 is faux bold? It seems like the 400, but the rendering seems just a little broken.

It is admittedly a bit of a guess as the visible differences are small, but I believe the broken rendering is precisely a glitch of the faux-bolding process. If you look very closely at the picture, you’ll see that the 500 in that column is in fact slightly bolder than the 100/200/300/400 and yet the same as the 600 and 611 in the same column, which according to conventional knowledge should be faux-bolded. (The 600/611 exhibit the same glitches, too.)
