### ISSUE TITLE
What does "guess what" mean in the documentation?

### ISSUE THREAD

**Issue by Masterjun3** [libass/libass#616]
https://github.com/libass/libass/blob/0e0f9da2edc8eead93f9bf0ac4ef0336ad646ea7/libass/ass_render.c#L1840

This isn't really helpful.

**Comment by TheOneric** [comment]
The parameter has the same meaning as all other `ASS_Renderer *` function parameters. It's a pointer to a struct keeping track of the rendering state, rendering caches, font providers and so on and the content is private to libass itself.
I'd agree that just putting “guess what” wouldn't be good in documentation of public API, but the quoted bit is documentation for a static function never exposed to API-users or even other files in libass. Imho it’s fine to leave it as is here.

**Comment by Masterjun3** [comment]
Well, you know, guess what?

**Comment by astiob** [comment]
If there should be a desire to get rid of this “guess what” (which did make me laugh), we may as well just drop the parameter descriptions from this function’s doc string. Neither of them is telling anything that isn’t already obvious.

**Comment by Masterjun3** [comment]
For reference, I ran into the "guess what" when trying to look into one of the issues on the tracker, and following along with the code.
Obviously, this is useless for someone who would need the documentation in the first place.

![image](https://user-images.githubusercontent.com/22375320/195798050-9ed53969-4b67-42ad-a1ea-329231a3a18e.png)

I agree that it would be better to remove documentation if this is the level of quality this codebase is satisfied with.
Seeing stuff like this, I'm kind of worried about the rest of the code.
