### ISSUE TITLE
Rendering: \fay behavior with inline \frz adjustments

### ISSUE THREAD

**Issue by nedragrevev** [libass/libass#624]
### Screenshots

What it looks like now on AegisubDC 9215 (libass) / mpv Windows build (by shinchiro) 20220227-git-b1fb4b7 (and the latest 20220522-git-9022b1b):
![AegisubDC 9215_libass-5f0e845](https://user-images.githubusercontent.com/62979151/170431556-be9db817-a8f0-4286-b307-741190ce990d.png)

What it should look like (AegisubDC 9214 / mpv Windows build 20220213-git-bc9805c):
![AegisubDC_9214_libass-unkown](https://user-images.githubusercontent.com/62979151/170431766-6b18a1ed-56f5-421b-b562-e40e24101f3a.png)

### Description of the issue

\fay behavior with inline \frz adjustments messes with/resets character positions. See screenshots and script.

The issue occurs at every \frz adjustment. Where there are no \frz adjustments, it renders correctly, but any inline \frz adjustment resets the character position as if no \fay was applied at the start.

### libass version

mpv Windows Build (by shinchiro) 20220227-git-b1fb4b7

### Is it a regression?

Yes. 20220213-git-bc9805c (mpv Windows build by shinchiro) was fine.

### ASS Sample

[Script Info]
; Script generated by Aegisub 9215, Daydream Cafe Edition [Shinon]
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Video File: ?dummy:23.976000:20000:1920:1080:47:163:254:
Video AR Value: 1.777778
Video Zoom Percent: 0.500000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Signs,Lato,81,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 3,0:00:00.00,0:05:00.00,Signs,,0,0,0,,{\an7\fnCentury Gothic\fs43\c&H333232&\frz23.69\fay0.225\blur1\pos(34.98,254.01)}G{*\frz23.64\fax0.003}r{*\frz23.591\fax0.005}a{*\frz23.541\fax0.008}n{*\frz23.492\fax0.011}d {*\frz23.392\fax0.016}o{*\frz23.343\fax0.019}p{*\frz23.293\fax0.022}e{*\frz23.243\fax0.024}n{*\frz23.194\fax0.027}i{*\frz23.144\fax0.03}n{*\frz23.095\fax0.032}g {*\frz22.995\fax0.038}o{*\frz22.946\fax0.04}n {*\frz22.847\fax0.046}M{*\frz22.797\fax0.048}a{*\frz22.747\fax0.051}r{*\frz22.698\fax0.054}c{*\frz22.648\fax0.057}h {*\frz22.549\fax0.062}1{*\frz22.499\fax0.065}s{*\frz22.45\fax0.067}t{\frz22.4\fax0.07}!{*\frz23.045\fax0.035}\N{\frz23.69\fax0}L{*\frz23.63}o{*\frz23.571}o{*\frz23.511}k{*\frz23.452}i{*\frz23.392}n{*\frz23.332}g {*\frz23.213}f{*\frz23.154}o{*\frz23.094}r {*\frz22.975}o{*\frz22.915}p{*\frz22.856}e{*\frz22.796}n{*\frz22.736}i{*\frz22.677}n{*\frz22.617}g {*\frz22.498}s{*\frz22.438}t{*\frz22.379}a{*\frz22.319}f{*\frz22.26}f{\frz22.2}!{*\frz22.945}\N{\frz23.69}Y{*\frz23.637\fax0.002}o{*\frz23.583\fax0.004}u {*\frz23.476\fax0.009}a{*\frz23.423\fax0.011}r{*\frz23.37\fax0.013}e {*\frz23.263\fax0.017}w{*\frz23.209\fax0.019}e{*\frz23.156\fax0.021}l{*\frz23.103\fax0.024}c{*\frz23.049\fax0.026}o{*\frz22.996\fax0.028}m{*\frz22.943\fax0.03}e {*\frz22.836\fax0.034}t{*\frz22.782\fax0.036}o {*\frz22.676\fax0.041}c{*\frz22.622\fax0.043}o{*\frz22.569\fax0.045}m{*\frz22.515\fax0.047}e {*\frz22.409\fax0.051}w{*\frz22.355\fax0.054}i{*\frz22.302\fax0.056}t{*\frz22.248\fax0.058}h {*\frz22.142\fax0.062}a {*\frz22.035\fax0.066}f{*\frz21.981\fax0.069}r{*\frz21.928\fax0.071}i{*\frz21.875\fax0.073}e{*\frz21.821\fax0.075}n{*\frz21.768\fax0.077}d {*\frz21.661\fax0.081}a{*\frz21.608\fax0.084}n{*\frz21.554\fax0.086}d {*\frz21.447\fax0.09}a{*\frz21.394\fax0.092}p{*\frz21.341\fax0.094}p{*\frz21.287\fax0.096}l{*\frz21.234\fax0.099}y {*\frz21.127\fax0.103}t{*\frz21.074\fax0.105}o{*\frz21.02\fax0.107}g{*\frz20.967\fax0.109}e{*\frz20.914\fax0.111}t{*\frz20.86\fax0.114}h{*\frz20.807\fax0.116}e{*\frz20.753\fax0.118}r{\frz20.7\fax0.12}!{*\frz21.697\fax0.103}\N{*\frz22.693\fax0.087}\N{\frz23.69\b1\fax0.07}O{*\frz23.649}p{*\frz23.607}e{*\frz23.566}n{*\frz23.524}i{*\frz23.483}n{*\frz23.441}g{\frz23.4}s{*\frz23.497}:{*\frz23.593}\N{\b0\frz23.69}1{*\frz23.664}. {*\frz23.611}W{*\frz23.585}a{*\frz23.558}i{*\frz23.532}t{*\frz23.505}s{*\frz23.479}t{*\frz23.453}a{*\frz23.426}f{\frz23.4}f{*\frz23.545}\N{\frz23.69}2{*\frz23.644}. {*\frz23.552}K{*\frz23.506}i{*\frz23.46}t{*\frz23.414}c{*\frz23.368}h{*\frz23.322}e{*\frz23.276}n {*\frz23.184}s{*\frz23.138}t{*\frz23.092}a{*\frz23.046}f{\frz23}f{*\frz23.23}\N{*\frz23.46}\N{\frz23.69\b1}Pay:\N{\frz23.69\b0}• {*\frz23.639}S{*\frz23.613}t{*\frz23.587}u{*\frz23.562}d{*\frz23.536}e{*\frz23.51}n{*\frz23.485}t{*\frz23.459}s{*\frz23.433}* {*\frz23.382}f{*\frz23.357}r{*\frz23.331}o{*\frz23.305}m {*\frz23.254}¥{*\frz23.228}8{*\frz23.203}5{*\frz23.177}0{*\frz23.151}/{*\frz23.126}h{\frz23.1}r{*\frz23.395\fscx99\fsp-0.25}\N{\frz23.69\fsp-0.5\fscx98}• {*\frz23.639}W{*\frz23.613}e{*\frz23.588}e{*\frz23.562}k{*\frz23.537}e{*\frz23.511}n{*\frz23.486}d{*\frz23.46}s{*\frz23.434}/{*\frz23.409}H{*\frz23.383}o{*\frz23.358}l{*\frz23.332}i{*\frz23.307}d{*\frz23.281}a{*\frz23.256}y{*\frz23.23}s{*\frz23.204}: {*\frz23.153}+{*\frz23.128}¥{*\frz23.102}5{*\frz23.077}0{*\frz23.051}/{*\frz23.026}h{\frz23}r{*\frz23.345\alpha&H80&}\N{\alpha&HFF&\frz23.69}-{*\frz23.684}-{*\frz23.678}-{*\frz23.671}-{\frz23.665\alpha&H00&}* {*\frz23.653}S{*\frz23.647}t{*\frz23.641}u{*\frz23.636}d{*\frz23.63}e{*\frz23.624}n{*\frz23.618}t{*\frz23.612}s {*\frz23.6}w{*\frz23.594}o{*\frz23.588}r{*\frz23.582}k {*\frz23.571}u{*\frz23.565}n{*\frz23.559}t{*\frz23.553}i{*\frz23.547}l {*\frz23.535}1{*\frz23.529}0 {*\frz23.518}p{*\frz23.512}.{*\frz23.506}m{\frz23.5}.{*\frz23.595}\N{\frz23.69}\N{\b1}Perks:\N{\b0}• Uniforms provided\N• Free meals\N\NPlease call in advance {\frz23.69}a{*\frz23.646\fax0.071}n{*\frz23.602\fax0.072}d {*\frz23.515\fax0.074}b{*\frz23.471}r{*\frz23.427\fax0.075}i{*\frz23.383\fax0.076}n{*\frz23.339\fax0.077}g {*\frz23.252\fax0.079}y{*\frz23.208\fax0.08}o{*\frz23.164\fax0.081}u{*\frz23.12}r {*\frz23.033\fax0.083}r{*\frz22.989\fax0.084}é{*\frz22.945\fax0.085}s{*\frz22.901\fax0.086}u{*\frz22.857\fax0.087}m{*\frz22.814\fax0.088}é {*\frz22.726\fax0.089}w{*\frz22.682\fax0.09}i{*\frz22.638\fax0.091}t{*\frz22.594\fax0.092}h {*\frz22.507\fax0.094}a {*\frz22.419\fax0.096}p{*\frz22.375}h{*\frz22.331\fax0.097}o{*\frz22.288\fax0.098}t{*\frz22.244\fax0.099}o{\frz22.2\fax0.1}.

### Special Fonts

The issue doesn't depend on a specific font

### Additional info

I should probably mention that VSFilter doesn't render this correctly either (and I'm not sure if it ever did?). But I'm reporting this since it wasn't too long ago that it was working as expected.

There are other options with this sort of typesetting, but there were a few pages like this that needed tracking in this particular episode, so splitting this into many lines would have required a lot of unnecessary lines, and converting all this text to one huge vector would have resulted in a 40MB+ file.

I'm sorry I don't have any libass build info. I can't work out how to determine this except for ffmpeg library builds, and some libav** & libsw** version numbers.

**Comment by rcombs** [comment]
This file was apparently produced targeting libass-specific behavior, which we don't support. Newer versions of libass match vsfilter behavior on `\fay`, as per our well-documented compatibility target. This is not a libass bug. Please report this to the subtitle author.

**Comment by nedragrevev** [comment]
@rcombs Sorry, I wasn't sure which flag to use and just went with a rendering issue when the bug form came up.

I understand the desire to be compatible with VSFilter, but does this behavior not seem odd? I mean, does this mean that libass will render as VSFilter does even if that renderer is wrong?

Oh, and I am the subtitle author.

**Comment by astiob** [comment]
> I understand the desire to be compatible with VSFilter, but does this behavior not seem odd? I mean, does this mean that libass will render as VSFilter does even if that renderer is wrong?

Yes, and yes. If libass and VSFilter render things differently, you can’t author a subtitle file at all. Even if VSFilter’s behaviour is strange (as it is here, no doubt—which is why libass took so long to implement this), we have to emulate it to

* correctly render old files that target VSFilter,
* allow new files to have a stable cross-platform target.

To the end user, it doesn’t matter how sensible the underlying format is; it just matters whether they can view the subtitles. Subtitle authors, likewise, have proven to not care how sensible things they’re doing are as long as the output just looks right in VSFilter. So we’re stuck with both weird behaviour _and_ files that actually rely on that weird behaviour, which we have to render.

**Comment by nedragrevev** [comment]
Thanks for the more detailed response @astiob

A little bit more experimentation shows that this occurs for all other inline arguments such as: `\fscx`, `\fry`, `\fax`, `\b`, `\shad` `\fn` etc.

This essentially renders `\fay` useless. However, I appreciate the more detailed response.

**Comment by astiob** [comment]
For reference, #465 demonstrates one sample that makes intentional use of this `\fay` behaviour (karaoke where each syllable skews and dissolves in turn while the rest of the line stays in place), though admittedly, this particular sample is fairly simple, and applying whole-line shear (via `ASS_FEATURE_WHOLE_TEXT_LAYOUT`) makes it look annoying (the line starts jumping rhythmically) but not completely unworkable.

**Comment by nedragrevev** [comment]
Ah, I saw that issue but I didn't look into it carefully as the screenshots seemed to suggest a simple shear without any inline transforms. Good to know it is related as I was actually thinking of asking if there are any scripts out there that rely on this behavior, especially given the time taken to replicate this aspect of VSFilter's `\fay` behavior.

That said, karaoke effects and typesetting are two different things, and I would struggle to see any proficient typesetter that would rely on this behavior. Though I rarely used `\fay`, and there are always workarounds. With the ts in my screenshots, it just ended up being much quicker and easier, and it worked fine late last year with mpv. Easy enough to adjust without adding an inordinate amount of lines, so all good now.

If ASS v5.0 ever gets worked on, then maybe the expected behavior of whole line shear can be implemented.

**Comment by astiob** [comment]
Found another real-world sample—and this time with typesetting, not karaoke—in https://code.google.com/archive/p/libass/issues/80 comment 8. Someone put a bunch of `\h` for positioning and then changed `\fay` for the rest of the line, which contained visible text. Which, like, could be adapted by adding `{\fay0}` at the start of the line, but the thing is—it just works, and the author didn’t care why.

By the way, (precisely due to this sample,) libass was already emulating VSFilter for `\fay`, just half-heartedly: it reset the baseline only when `\fay` itself changed, not other tags (and even that was bugged, but never mind that).

> If ASS v5.0 ever gets worked on, then maybe the expected behavior of whole line shear can be implemented.

Plausible.

But do note that, in my opinion, even libass’s new `ASS_FEATURE_WHOLE_TEXT_LAYOUT` behaviour (which doesn’t reset the baseline on any tag changes) isn’t fully sensible. Shear is applied from the top left corner of each glyph box and (conceptually) before `\fsc*`, so if you change the font size, the font face or the scaling in the middle of the line, even this “whole-line” shear suddenly starts making considerably less sense. The truly sensible thing for `\fay` would be to skew the baseline itself as a whole; or better yet, skew the entire event (not every line in isolation), which would make it more useful for automated 3D transforms.

**Comment by nedragrevev** [comment]
That real-world example would have been more complicated if the lines of text needed to be curved, whereas changing the vertical line spacing would be as easy as splitting the event as required. But I do I see why libass needs to support these older scripts, and obviously, they are out there.

The thought about when shear is applied, in terms of before or after other tags did cross my mind. Given that it's after, that would cause all sorts of different skew angles with inline `\fsc*` tags, which as you've mentioned, isn't much better than the issue I raised.
