### ISSUE TITLE
How position text inside video so near black bars

### ISSUE THREAD

**Issue by CastagnaIT** [libass/libass#627]
I would like to know if there is a way to place the text inside the video, so near the black bars
maybe stupid question but i tried a couple of tests with margins and i failed

like this example:
![immagine](https://user-images.githubusercontent.com/3257156/176606094-b6f17396-e538-4046-8c1a-a9198eac4344.png)

when i align on top text placed near black bar, when align bottom the same
(this for adapted subtitles like srt, not ass/ssa)

**Comment by astiob** [comment]
What are you seeing instead?

You should get this if you just set the Style `Margin`s to zero. If you are converting SRT to ASS yourself, just do that. If you are using mpv to play SRT, set `--sub-margin-y=0` and ensure you have `--sub-use-margins=no` (otherwise text will be put in the black bars surrounding the video).

**Comment by CastagnaIT** [comment]
> What are you seeing instead?

thanks,
i no longer remember what i did wrong
i just tried today with suggests things and now works!
but why the font size is displayed differently? any idea? see below

regular bottom alignment Kodi:
![immagine](https://user-images.githubusercontent.com/3257156/177732346-15c8b563-bd21-41e8-875c-e342619e8a94.png)

with new changes:
- style margins to 0
- ass_set_margins t/b args with the size of black bar space
- ass_set_use_margins set to false
- ass_set_pixel_aspect kept always as before `dar / sar`
- ass_set_line_position set to 0
![immagine](https://user-images.githubusercontent.com/3257156/177732405-e7cc8c4e-26bf-469b-8d30-b417a2a6400e.png)

**Comment by TheOneric** [comment]
> - ass_set_margins t/b args with the size of black bar space
> - ass_set_use_margins set to false

Do I understand correctly, that you previously did not exclude the margins from the rendering frame? If not, this might cause the difference. Do you get the same size with all settings from your second screenshot, but with `ass_set_use_margins(renderer, 1)`?

**Comment by CastagnaIT** [comment]
if i use `ass_set_use_margins` to 1 with "new changes", result the text placed in black bar instead over the black bar, and same small text size
![immagine](https://user-images.githubusercontent.com/3257156/177931510-c1b92ea8-7140-4d89-b759-7e0b0472d70d.png)

if i use `ass_set_use_margins` to 1 with "regular bottom alignment" of kodi,
on cropped videos the text result "small" as the image above ^^
but if i play a non-cropped video the text size change with normal size (as first screenshot),
this is inconsistent and cause the PT ratio of the text size displayed wrongly

i dont know, looks like that the font size set in `FontSize` of style is no longer respected

**Comment by TheOneric** [comment]
It does not change the `FontSize` property, but withholding information from libass (or giving libass false information) about the video display size leads to false results.

If the render frame is not identical to the video display area, always tell libass about it with `ass_set_margins`. And conversly, if the areas are identical, don't configure bogus margins.

If your frame contains margins, but you are not telling libass what's margin and what part of the video frame, we'll assume there are no margins and calculate the scaling from storage size or `PlayRes{X,Y}` against the whole frame size. Of course, this will yield a different result then correctly scaling up to the video frame only.
This affects all scaling as you saw here and is especially important for typesets which always need to be scaled *and* placed as if “video display area == render frame”
