### ISSUE TITLE
Failing to find glyph 0x1F90D in Noto Emoji font, but only when attached

### ISSUE THREAD

**Issue by rcombs** [libass/libass#634]
Compact script:
```
[Script Info]
; Script generated by Aegisub 9215, Daydream Cafe Edition [Shinon]
; http://www.aegisub.org/
Title: Call of the Night 02
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,LTFinnegan Medium,75,&H00FFFFFF,&H000019FF,&H00000000,&HB4000000,0,0,0,0,100,100,0,0,1,3.3,1.5,2,135,135,53,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 5,0:02:15.99,0:02:20.56,Default,,0,0,0,,Seriously, you can't just give me a \N"Drink my blood now{\fnNoto Emoji\b1}🤍{\r}" look like that.
```

Font: [NotoEmoji-Bold.ttf.zip](https://github.com/libass/libass/files/9127089/NotoEmoji-Bold.ttf.zip)

I tested the MKV file (which has this font attached) on libass 7bc0c45dd58de6afa1800f8e8a94285e7535d68d.

With CoreText enabled, I get this:
```
[sub/ass] fontselect: (Noto Emoji, 400, 0) -> NotoEmoji-Bold, 0, NotoEmoji-Bold
[sub/ass] fontselect: (Noto Emoji, 700, 0) -> NotoEmoji-Bold, 0, NotoEmoji-Bold
[sub/ass] Glyph 0x1F90D not found, selecting one more font for (Noto Emoji, 700, 0)
[sub/ass] fontselect: (Noto Emoji, 700, 0) -> /System/Library/Fonts/LastResort.otf, -1, LastResort
```
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/819638/179385921-04663a35-886c-45f0-a5eb-a4e1571eef17.png">

And without, I get this:
```
[sub/ass] fontselect: (Noto Emoji, 400, 0) -> NotoEmoji-Bold, 0, NotoEmoji-Bold
[sub/ass] fontselect: (Noto Emoji, 700, 0) -> NotoEmoji-Bold, 0, NotoEmoji-Bold
[sub/ass] Glyph 0x1F90D not found, selecting one more font for (Noto Emoji, 700, 0)
[sub/ass] fontselect: failed to find any fallback with glyph 0x1F90D for font: (Noto Emoji, 700, 0)
```

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/819638/179385909-26797832-0e40-4b29-8f15-4c800a332ee6.png">

The weird thing is… the font _does_ have that glyph? Meanwhile, in Aegisub, or in mpv when playing a file that _doesn't_ have the font attached:
```
fontselect: (Noto Emoji, 400, 0) -> /Users/rcombs/Library/Fonts/NotoEmoji-Bold.ttf, -1, NotoEmoji-Bold
fontselect: (Noto Emoji, 700, 0) -> /Users/rcombs/Library/Fonts/NotoEmoji-Bold.ttf, -1, NotoEmoji-Bold
Glyph 0x1F90D not found, selecting one more font for (Noto Emoji, 700, 0)
fontselect: (Noto Emoji, 700, 0) -> /Users/rcombs/Library/Fonts/NotoEmoji-Bold.ttf, -1, NotoEmoji-Bold
Got a font face that already is available! Skipping.
Glyph 0x1F90D not found, broken font? Trying all charmaps
```
<img width="434" alt="image" src="https://user-images.githubusercontent.com/819638/179386030-d008f7de-ae36-421a-9244-652d0c1d5f45.png">

So, this seems to be some sort of bug in the internal memory font handling. What?

**Comment by astiob** [comment]
I suspect we’re using the wrong Unicode cmap, but my question is: why is your mpv-with-attached-font test not select NotoEmoji as the fallback font like your mpv-without-attached-font test does? Is the report fully correct in saying that both tests work in mpv?

**Comment by astiob** [comment]
To clarify further: the last sample works because (as seen in the log) the font is installed system-wide, Core Text knows it contains the glyph, so font fallback chooses the same font (because it is aware of the desired font name), and _after_ font fallback, we try all charmaps as a last resort, which finds the UCS-4 charmap.

I suspect that the first sample was tested when Noto Emoji was _not_ installed system-wide, so font fallback selected something else (LastResort).

And the second sample failed to select any fallback because there was no system font provider (is my interpretation correct?), and I guess our all-charmap branch doesn’t run in this case (maybe it should).

**Comment by astiob** [comment]
(Or maybe we shouldn’t have the all-charmap branch at all or should limit it to only Unicode cmaps when the code point isn’t in ASCII, because if we find it as an index in a non-Unicode cmap, it’ll likely be something completely different.)
