### ISSUE TITLE
Color gap between outline and text

### ISSUE THREAD

**Issue by CastagnaIT** [libass/libass#647]
Recenlty on Kodi (v20) we have found this problem with libass
so when you set an outline border color white with white text, as this screenshot:

![immagine](https://user-images.githubusercontent.com/3257156/190892493-d5b39d12-88da-453c-b4d4-d857caee3b37.png)

a color gap appears around the text

this happens always in these situations:
- Playing native ASS with style overrides: Color gap
- Playing adapted subtitles (e.g. SRT): Color gap

but the gap not appears when you playing a native ASS (without overrides enabled)
more screenshots on https://github.com/xbmc/xbmc/issues/21867

i also found that your wip PR: https://github.com/libass/libass/pull/483
appears to solve the problem at least i dont see color gap anymore

what i am asking is what can influence this gap?
there is a way to minimize this?

**Comment by astiob** [comment]
> what can influence this gap?

The text, outline and background (video) colours and opacities.

The gap is present if your text transparency (alpha) is non-zero, but it may be more or less obvious depending on the exact colours involved.

With zero transparency (PrimaryColour aka \1a and SecondaryColour aka \2a, and no \fade), there should not be any gap at all, as long as you’re using libass 0.15.1 or newer (see https://github.com/libass/libass/pull/470). Maybe the affected user’s overrides include a semitransparent SecondaryColour?

**Comment by astiob** [comment]
I have no significant knowledge of Kodi code, but a search for `PrimaryColour` combined with the report that this is a regression in 20a3 points to https://github.com/xbmc/xbmc/commit/ca1f335e1d382ca4f20621a1c5047b9588226672 as a primary suspect, specifically this line:

```
style->SecondaryColour = ConvColor(subStyle->fontColor, COLOR_OPACITY_30);
```

**Comment by CastagnaIT** [comment]
yes i forgot to mention that we use v0.15.1
as suggested i have done other tests (with adapted SRT and native ass with overrides) and i can confirm:
- if i set  `PrimaryColour`, `SecondaryColour` and `OutlineColour` all them without transparency, the gap problem _not_ happens
- if i set  `PrimaryColour` full solid and `SecondaryColour` with some transparency, and `OutlineColour` full solid, the gap problem happens
- if i set  `PrimaryColour`, `SecondaryColour` and `OutlineColour` all them with transparency, the gap problem happens

so since we use `SecondaryColour` for karaoke we need to set it with a different color
then as you said as workaround i can set it to black without transparency,
this at least fix the normal use case when transparency is not used at all

however if a user want to set a kind of color transparency that affect `PrimaryColour` and `OutlineColour` the problem persists

i have also done same tests by including in v0.15.1 the PR https://github.com/libass/libass/pull/483
and for all use cases (with or without transparency)
there are no color gap problem

**Comment by astiob** [comment]
Yes, that’s expected. #483 will avoid gaps in all cases.

Note that normally, the PrimaryColour and the OutlineColour are contrasting colours, most commonly white (or otherwise light) PrimaryColour and black (or otherwise dark) OutlineColour. And in that case, the gap isn’t very pronounced even if it is present. Setting Primary and Outline to the same colour is sometimes necessary to achieve complex visual effects, but doing it in a user override/for plain-text subtitles seems odd. But again, #483 _will_ take care of that.

Anyway, it seems your question is answered and the current culprit in Kodi has been found, so I’m marking this as closed.

**Comment by CastagnaIT** [comment]
yeah thanks for the support
