### ISSUE TITLE
Can OpenType features be controlled?

### ISSUE THREAD

**Issue by TS40** [libass/libass#652]
Hi, I'm wondering if it's possible to enable/disable font features like for example in [this](https://wiki.contextgarden.net/Featuresets) software? Unfortunately some fonts have this included as a "feature" but software that does not support this make the font unusable. For now, I have not found out if that's possible with libass.

**Comment by astiob** [comment]
Correct: ASS has no mechanism for controlling individual OpenType features.

As a special case, you can ensure that `liga` and `kern` are enabled by doing two things:
* set `Kerning: yes` as an ASS header in the `[Script Info]` section to enable them in libass
* and include a “complex-layout” codepoint such as U+200B ZERO WIDTH SPACE in each and every text segment delimited by ASS override tags and line breaks (and, if you don’t know where your line breaks are, U+0020 spaces) to enable them in non-libass renderers (the VSFilter family). There’s a chance that this actually enables more than just `liga` and `kern`—we don’t actually know the exhaustive list. If you find another feature that is affected, we’d love to hear about that.

**Comment by TheOneric** [comment]
If you're creating subtitles for distribution, I strongly recommend sticking to what's portable between  VSFilter and libass and astiob's comment already covers everything.

If you're creating a transient ASS representation, e.g. on-the-fly conversion from other formats or custom rendering, you can also select language-specific font variations globally via the libass-specific `Language:` header. The header values are currently limited to ISO 639-1 codes *(but this may be extended in the future)*.
