### ISSUE TITLE
How to build .so, .dylib, .dll at one machine?

### ISSUE THREAD

**Issue by wiedymi** [libass/libass#663]
Hello! Is it possible to build the library into three platform format on Mac? so, .dylib, .dll 
Also I would like to have those files built in different platform architecture, so  .dylib should universal, not only arm64.

**Comment by TheOneric** [comment]
> Is it possible to build the library into three platform format on Mac?

If there are suitable cross-compiler available on macOS, likely yes.

Building libass works the same as any other Autotools (here: Autoconf, Automake & libtool) project.

To build for your current macOS machine, run `./configure` and then run `make`. Then if you want to install it in /usr/local, run `make install`.
To cross-build for other platforms, you probably need to tell configure what compilers to use etc.

Nothing about cross-compiling or “universal dylibs” is libass-specific and you'll likely have more luck finding useful info with a web search for macOS cross-compiling and universal dylibs than on this issue tracker.

**Comment by wiedymi** [comment]
I see, I've tried to use --host, but I still get .dylib instead of .so built.


Command I run:

./configure --host=x86_64-linux
./make -B

**Comment by wiedymi** [comment]
Ok, I've built it, but there's missing libass.so.9.1.4

![image](https://user-images.githubusercontent.com/42713027/201735599-45347c85-56de-4a88-a70d-3ac3d9b73976.png)
