### ISSUE TITLE
Noto Sans rendered too short/small?

### ISSUE THREAD

**Issue by sfan5** [libass/libass#668]
#### Description

&nbsp; | LibreOffice | libass
--- | --- | ---
Arial | ![grafik](https://user-images.githubusercontent.com/1042418/208507668-d879dddc-4580-49b2-a08b-fe7ec37c306d.png) | ![grafik](https://user-images.githubusercontent.com/1042418/208505916-d4dda555-6bcd-4d49-b71e-23fbed0e26ac.png)
Noto Sans | ![grafik](https://user-images.githubusercontent.com/1042418/208508651-4f205a40-ac7c-4530-abd7-66a59d8fd099.png) | ![grafik](https://user-images.githubusercontent.com/1042418/208506227-98e90b4e-02ac-469e-854f-6dc18d4b2674.png)

Something is wrong with the rendering of Noto Sans (and only that, I haven't ever noticed this before) in libass.
I initially noticed this in mpv but the pictures on the right were generated using the test utility and [this file](https://0x0.st/o5NJ.txt).

The issue is really noticable with mixed scripts as in the example above, note how the proportions visually don't fit on the bottom-right (almost looks like subscript).

Rendering in LO is show for comparison but I didn't find any other application on my system with this bug.

#### Log

<pre>
test.c: Available font providers (3): 'None', 'Autodetect', 'Fontconfig'.
libass: libass API version: 0x1700000
libass: libass source: commit: 0.17.0-21-g062d4ec598b4fd06f75c0cd6a0f43f5d0939a764
libass: Raster: FreeType 2.12.1
libass: Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 5.3.1 (COMPLEX)
libass: Initialized
libass: Using font provider fontconfig
libass: File size: 652
libass: [0x56230b8332c0] Style: Default,Noto Sans,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,10,10,10,1
libass: Added subtitle file: '/home/stefan/Untitled.ass' (2 styles, 1 events)
libass: fontselect: (Noto Sans, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
libass: Glyph 0x3010 not found, selecting one more font for (Noto Sans, 400, 0)
libass: fontselect: Using default font family: (Noto Sans, 400, 0) -> /usr/share/fonts/OTF/ipag.ttf, 0, IPAGothic
libass: fontselect: (Noto Sans, 400, 0) -> /usr/share/fonts/OTF/ipag.ttf, 0, IPAGothic
1 images blended
</pre>

also reproduces on libass 0.17.0

**Comment by rcombs** [comment]
Does this behavior differ from VSFilter's?

**Comment by sfan5** [comment]
What's the best (minimal) way I could test that?

**Comment by rcombs** [comment]
You could use Aegisub's built-in screenshot feature on Windows, once with the renderer setting set to VSFilter and once with it set to libass.

**Comment by sfan5** [comment]
I downloaded Aegisub 3.2.2 from a random place on the internet as the website is down, not sure if it's latest.

The result with "xy-vsfilter_aegisub" looks as follows:
![dummy_002_0](https://user-images.githubusercontent.com/1042418/208926358-2d8c6a27-7952-4b8a-93ef-62ed32e3a952.png)
With libass Aegisub unfortunately crashes as soon as it tries to render anything.
(I added extra `\fn` tags to make sure it uses IPAGothic for the brackets)

Thus the answer is: no
But I'm still interested to know why Noto Sans is rendered smaller than usual by libass and VSFilter and whether there is a way to disable it.

**Comment by rcombs** [comment]
These images are all different sizes, so it's difficult to compare them 1:1, but as far as I can tell, this seems to be rendering the same between the two renderers. Thus, this is working as designed; libass is intended to emulate the behavior of VSFilter (and thus GDI), not that of LibreOffice.

GDI font sizing is pretty strange in general; it relies on the usWinAscent+usWinDescent values from the OS/2 table, rather than the typographical metrics you might find used in other software. If you want to get visually-even sizing across multiple fonts, you'll likely need to manually adjust `fs` (or `fscx` + `fscy`) to achieve that.

**Comment by sfan5** [comment]
Thanks for the details.
My goal is to get consistent font rendering for the mpv osd/osc so an `ASS_FEATURE_*` would cut it (no need for VSFilter compatibility), I experimented with the relevant code in ass_font.c and getting it to render that way doesn't seem trivial.
Incidentally mpv isn't actually the only application that has size/alignment issue with Noto Sans. Maybe they do have their values messed up, apparently Nimbus Sans has/had(?) [such an issue](https://github.com/primer/css/issues/1209#issuecomment-1100771851) too.

**Comment by astiob** [comment]
What is “consistent rendering” intended to mean? What exactly do you want to stay consistent with what?

Different fonts have different proportions. In general, you can’t just change the font name and expect all font elements to stay the same size, no matter what text rendering implementation you use. The other font may have bigger or smaller lowercase letterforms (x-height) compared to uppercase (cap height), bigger or smaller letterforms compared to line height, higher or lower baseline, etc. This is all set intentionally by font designers as part of every font’s visual identity.

What ASS guarantees is that if you set multiple lines in a single font, the distance between consecutive lines will always be exactly the “font size” number of pixels, no matter what particular font you use. For some fonts, this is indeed inconsistent with other (newer) text rendering/styling systems such as (I think) CSS, which add dedicated line spacing between lines, and for this and other reasons, each font actually specifies _multiple_ groups of designer-chosen values, one for each of multiple historical rendering systems. ASS uses a particular group that has mostly fallen out of favour over the years but was (and continues to be) used by Windows’ oldest text rendering stack, which ASS has to maintain compatibility with. But really, _none_ of the values is a simple “font size” knob, and I actually don’t think I’ve seen a universal normative definition of what combination of values a user-controllable “font size” knob should correspond to, so at the end of the day it’s all about what each implementor thinks makes more sense or what earlier implementation they want to match.

ASS may not be consistent with CSS or LibreOffice, and its exact choice of metric values may be dubious, but it does provide a consistent and predictable line height across all fonts (which nicely happens to be useful in subtitle authoring). If you’re looking for visual consistency in mixed-font English text, you may well want something else to stay consistent across fonts, likely the x-height, and in this case, CSS font-size wouldn’t help you, either.

**Comment by sfan5** [comment]
I'm talking about this ratio:
![test2](https://user-images.githubusercontent.com/1042418/209702938-463c875f-ff7a-4c41-935b-c546dcb7cd04.png)
Of course IPAGothic and whatever is inside the brackets are different fonts with different metrics/proportions but most(?) sans-serif fonts seem to stay within a certain margin. If that's not the case then it looks "inconsistent", as with the initial bottom-right example image.

Since legacy compatibility is the goal I don't blame libass, it's just surprising to have your system font look off in a particular application.
