### ISSUE TITLE
Style names should preserve trailing spaces

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#670]
### Screenshots

VSFilter
![image](https://user-images.githubusercontent.com/80980684/210092668-16dc6adb-3216-44c4-8e06-3cb3c410cead.png)

Libass
![image](https://user-images.githubusercontent.com/80980684/210092688-55463552-f214-4fdd-a13a-67a874fd2151.png)

### Description of the issue

Libass use the style ``***Example     ``, but VSFilter use the style ``Default``.

Warning, if you open the file with Aegisub, you won't see any issue, because it seems that it automatically trim space of the style name when you open an .ass file.
So you will need to edit the style ``***Example`` and add space at the end of it.

I am not sure, but I think VSFilter parse the stylename like that: https://sourceforge.net/p/guliverkli2/code/HEAD/tree/src/subtitles/STS.cpp#l1447

### libass version

0.16.0

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9513-feature-042b7e1be
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 720
PlayResY: 480

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:23.976000:10000:720:480:16:145:190:
Video AR Value: 1.500000
Video Zoom Percent: 1.500000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,35,&H0011FF00,&H000000FF,&H002C2C2C,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,0,2,0,0,72,1
Style: ***Example     ,Arial,48,&H000000FF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\rExample}Example
```

### Special Fonts

The issue doesn't depend on a specific font

**Comment by astiob** [comment]
Thanks!

I think this difference should also manifest if you make multiple styles whose names differ only by the amount of trailing spaces and try to reference them via the usual `Style` field of a `Dialogue` line (as opposed to only via `\r`).

I’m not sure why we remove trailing spaces from style/dialogue fields in the first place:
https://github.com/libass/libass/blob/062d4ec598b4fd06f75c0cd6a0f43f5d0939a764/libass/ass.c#L422-L432
It shouldn’t affect any numeric fields in any detectable way, right? And the style name is the only non-numeric field that matters, right? So we should be able to just remove this trimming.

**Comment by TheOneric** [comment]
> But it shouldn’t affect any numeric fields in any detectable way, right? And the style name is the only non-numeric field that matters, right? So we should be able to just remove this trimming.

For numeric fields not trimming can result in leftover characters when converting to a numeric value, but i *think* though haven't checked this is no issue with our current parsing.

However, the style name isn’t the only non-numeric field extracted via `advance_token_pos`. Font names and `Format:` line column names are also handled by this; both in actual `Style:`/`Dialogue:` parsing via `NEXT` and in `format_line_compare`.
I’m not sure what trimming is supposed to happen on font names, but `Format:` columns definitely should be trimmed at both ends before being compared, so at  least we’d need to add explicit trims for them outside of `advance_token_pos`.
