### ISSUE TITLE
Rendering: When Arabic subtitles are burned into the video, it does not look as it should

### ISSUE THREAD

**Issue by 0TTA** [libass/libass#682]
### Screenshots

When Arabic subtitles are burned into the video, it does not look as it should

When I use the following command in FFmpeg, It gives me the following result, which is wrong:
`-vf "subtitles=test.ass"`

![subtitles](https://user-images.githubusercontent.com/82990310/216534432-27b7b0e8-1abf-4656-9511-f3ea3b9b46dc.png)

mpv:
![mpv](https://user-images.githubusercontent.com/82990310/216473605-883fbe3c-9e54-4109-8554-5591738ae06f.png)

MPC-HC:
![MPC-HC](https://user-images.githubusercontent.com/82990310/216473652-b0f1f5a4-690c-482b-b3fb-e0af3b702ba9.png)

VLC:
![VLC](https://user-images.githubusercontent.com/82990310/216473701-f13f7e68-3c47-46da-aab9-d7da3f223675.png)

### Description of the issue

Let's see what exactly the problem is, because if you are not an Arabic speaker, you might not get what the problem is.

This is a screenshot from MPV Player (not burned):

![mpv](https://user-images.githubusercontent.com/82990310/216535134-f87e7b36-cef4-420b-b01c-2a6199fe848b.png)

And the following one is the result of the following command (it should not look like this):

`-vf "subtitles=test.ass"`

![subtitles](https://user-images.githubusercontent.com/82990310/216534432-27b7b0e8-1abf-4656-9511-f3ea3b9b46dc.png)

### libass version

ffmpeg version N-109745-g7d49fef8b4-20230202

### Is it a regression?

I didn't know.

### ASS Sample

[Script Info]
PlayResX: 384
PlayResY: 288
ScriptType: v4.00+
PlayDepth: 0
ScaledBorderAndShadow: Yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,42,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,2,30,30,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:16:40.00,Default,,0,0,0,,‫هَذَا اَلنَّصِّ هُوَ مِثَالٌ لِنَصِّ!

### Special Fonts

I uploaded or linked to the required font

### System Information

[Fonts - Copy.zip](https://github.com/libass/libass/files/10576467/Fonts.-.Copy.zip)

### Additional info

For more context:
https://github.com/jellyfin/jellyfin-ffmpeg/issues/217#issue-1566849618

**Comment by rcombs** [comment]
This seems to be an ffmpeg bug where `ass_set_shaper` is always called with the "simple" shaper when using the `subtitles` filter (not the `ass` filter). Please report this to them.
