### ISSUE TITLE
[Feature Request] add functions to allocate/deallocate strings on libass heap

### ISSUE THREAD

**Issue by CrystalP** [libass/libass#684]
### Feature Request

Add functions to let the caller allocate/deallocate strings on the heap of libass.
for example:
```
char* ass_alloc_string(char* src)
void ass_free_string(char*src)
```
A few existing functions of ass_utils.h come close, but they are not exported (ass_copy_string, ass_aligned_alloc)

### Motivation

Avoid exceptions in libass and possible memory leaks of the caller when populating directly ASS_Style/ASS_Event strings

`ass_alloc_style` and `ass_alloc_event` allocate space for new structures on libass heap.
The structures can then be accessed and filled by the caller through `track->style+index` and `track->events+index` but there doesn't seem to be a simple way to allocate memory for `ASS_Style.Name`, `ASS_Style.FontName` and `ASS_Event.Name` on libass heap.
As a result, the caller allocates the strings on its own heap.

Impact: failure when `ass_free_events` and `ass_free_style` attempt to free the caller allocated strings,

### Context

The problem was noticed in Kodi and an exception is triggered in debug mode on Windows when skipping/stopping playback that includes srt subs. We would appreciate the API addition.
Some background info: since Sep 2021 Kodi uses libass to render many text formats (including srt). When activating such subs, a custom style is allocated with `ass_alloc_style` and the ASS_Style attributes are populated directly with the user's style preferences. During playback, as sub lines are demuxed, they are transcoded to ass sub-like text, `ass_alloc_event` adds an ASS_Event + sets its attributes before rendering.
There are also a few special actions to clear events when skipping, or changing the text or stop time of an existing event for some sub formats.

**Comment by rcombs** [comment]
Doesn't this only happen if you statically link the libc into a dynamically-linked libass, or dynamically link libass against a different copy of the libc than the caller? Could you just… not do that?

**Comment by CrystalP** [comment]
I don't think that' s what's happening but I'll check another time :-)

On Windows (my environment), libass is internal (ie prebuilt and packaged with the app) and the application and library have the same runtime (dynamically linked).

Kodi is available on many other platforms, I couldn't say what the situation is on them (Android, linux, macOS, iOS, tvOS, custom distros).

**Comment by CrystalP** [comment]
OK I feel silly now, the runtime of the application and libass were the same version but debug vs release. After rebuilding my own library in debug mode the problem went away. Sorry about that.
