### ISSUE TITLE
Rendering: Collision detection does not work if one of the two overlapping lines has the \t tag

### ISSUE THREAD

**Issue by tearfur** [libass/libass#685]
### Screenshots

![vlcsnap-2023-03-04-10h37m33s022](https://user-images.githubusercontent.com/46261767/222871559-67c7f8f8-c88a-4c30-9e47-30a6ad721404.png)

### Description of the issue

Collision detection does not work when one of the overlapping lines have the `\t` tag. I expected the white line to be on top of the yellow line.

The behaviour is the same when testing using VSFilterMod on MPC-BE, but I still think that is wrong.

### libass version

VLC 3.0.18 Vetinari from VideoLAN website

### ASS Sample

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: Default - Copy,Arial,48,&H0000FCFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default - Copy,,0,0,0,,test3…testasdas
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,test1…{\alphaFF\t(1000,1500,\alpha00)}test2
```

### Special Fonts

The issue doesn't depend on a specific font

### System Information

OS: Windows 11
CPU: Intel x86-64

**Comment by rcombs** [comment]
This is the standard ASS behavior, matching the reference implementation. You can work around it by explicitly positioning your lines. We'll likely want to look into improving this in an upcoming future format version (probably by allowing lines to explicitly specify whether or not collision shifting applies to them).
