### ISSUE TITLE
Font size differs from VSFilter for specific fonts

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#707]
Originally reported by @magnilens in https://github.com/mpv-player/mpv/issues/12411

Line heights seem to match, but the visual size of glyphs differs greatly for the top two lines. Note that unlike in #619 the font soize does not only differ for the `@` font but also the non-`@` `Kozuka Gothic Pr6n B`.

**MPC-HC ISR and xy-VSFilter:**
![vsfilter.jpg](https://user-images.githubusercontent.com/145240028/268491627-7578f333-8419-450e-98ee-6a2be7475e47.jpg)

**libass (5c15c883a4783641f7e71a6a1f440209965eb64f):**
![libass](https://user-images.githubusercontent.com/145240028/268491769-7600c151-7404-4533-bdd7-cbdea037f164.jpg)

### Sample

Full file with bundled fonts: [demo.mkv.zip](https://github.com/mpv-player/mpv/files/12642309/demo.zip)

For convenience just the subs:
```ini
﻿[Script Info]
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Gandhi Sans,72,&H00FFFFFF,&H0000FFFF,&H00200000,&H7F404040,0,0,0,0,100,100,0,0,1,4,0,2,180,180,65,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:03.98,Default,,0,0,0,,test line (Gandhi Sans size 72)
Dialogue: 0,0:00:00.00,0:00:03.98,Default,,0,0,0,,{\fnKozuka Gothic Pr6N B}test line (Kozuka Gothic Pr6N B size 72)
Dialogue: 0,0:00:00.00,0:00:03.98,Default,,0,0,0,,{\fn@FOT-SeuratCapie Pro B}test line (@FOT-SeuratCapie Pro B size 72)
```

### System Information

OS: Windows 10 build 19045.3448
originally found with: mpv version 0.36.0 / 20230910 Nightly (September 10, 2023) from https://www.videohelp.com/software/mpv-media-player, confirmed to affect 5c15c883a4783641f7e71a6a1f440209965eb64f

### Log

mpv log of original report: [demo.txt](https://github.com/mpv-player/mpv/files/12642298/demo.txt)

**Comment by astiob** [comment]
Hmm, this is not what I’m seeing.

Here’s what your demo.mkv looks like for me on Windows 11 22H2 with Russian regional formatting in XySubFilter 3.2.0.806:
![astiob_XySubFilter_3 2 0 806](https://github.com/libass/libass/assets/515193/1103e018-539b-411f-9eca-c642ae200bca)

and in the built-in renderer of MPC-HC 2.0.0:
![astiob_MPC-HC_2 0 0](https://github.com/libass/libass/assets/515193/f9a7dee8-c5d7-43bc-81d6-bcb91748bf1c)

In case it matters, among my system fonts, I seem to have GandhiSans-Bold but not either of the other two fonts.

**Comment by astiob** [comment]
Note that this seems to be different from _both_ of your screenshots…

**Comment by astiob** [comment]
For good measure, here it is in mpv 0.36.0, likely with libass 91422bdb9497e8484b3248f5ae7eb50d41e2555d:
![astiob_mpv_shinchiro_0 36 0_20230801](https://github.com/libass/libass/assets/515193/6ce89412-448c-4f63-8777-cd66591be814)
This does seem to match the provided mpv screenshot.

But the only significant difference between this and what I’m seeing in the VSFilters is in the @-font, which (as you point out) is probably due to #619.

**Comment by astiob** [comment]
For what it’s worth, according to fontTools, the Kozuka font has only one set of Microsoft-platform names (and an identical set of Macintosh-platform names), so regional settings shouldn’t play a role here; and it has glyphs for Latin, so it’s not being substituted, either.

**Comment by astiob** [comment]
As established in https://github.com/mpv-player/mpv/issues/12411, the Windows machine in the original report had a different copy of Kozuka Gothic Pr6N Bold installed system-wide, which was getting picked up by VSFilter, whereas the SeuratCapie difference is likely due to #619.
