### ISSUE TITLE
Why is the macro definition 'PARSE_START if (0)' executed

### ISSUE THREAD

**Issue by wencoo** [libass/libass#721]
I am debugging the source code, using gdb debugging, found that the breakpoint runs to the logic after PARSE_START, but the definition of PARSE_START is if(0), the following logic should not run, very strange phenomenon, not clear why

我正在调试源代码，使用gdb调试，发现断点运行到了PARSE_START之后的逻辑，但是PARSE_START的定义是if(0)，后面的逻辑不应该运行的，很奇怪的现象，不清楚为什么

**Comment by rcombs** [comment]
`PARSE_START` begins an if/elseif ladder. The `if (0)` branch is empty and will never run, but various `} else if (…) {` branches may.
