### ISSUE TITLE
image question

### ISSUE THREAD

**Issue by buzai** [libass/libass#724]
I loop the ass tack and save the ass_image, but i find image content is error 
i use opencv save the image
```
void saveImageWithOpenCV(const ASS_Image *assImage, const char *filename) {
    if (!assImage) {
        std::cerr << "Error: Invalid image data." << std::endl;
        return;
    }

    // Create a cv::Mat from ASS_Image bitmap data
    cv::Mat image(assImage->h, assImage->w, CV_8UC4, assImage->bitmap);

    // Convert BGRA to RGBA
    // cv::cvtColor(image, image, cv::COLOR_BGRA2RGBA);

    // Save the image using OpenCV
    cv::imwrite(filename, image);
}
```

**Comment by astiob** [comment]
`assImage->bitmap` is not an RGB image. It is not `CV_8UC4`.

It’s a single-channel alpha mask (`CV_8UC1`). The colour of the whole masked layer is `assImage->color`, which is RGBA but with the A inverted. For comparison, see:

https://github.com/libass/libass/blob/c047dd2ea16f73abb4f448e6db3637158c1226d0/test/test.c#L129-L140

OpenCV probably has APIs that can convert this to a simple RGBA bitmap, but I don’t know OpenCV.

**Comment by astiob** [comment]
Oh, and `assImage->color` may need further adjustment depending on the value of `assTrack->YCbCrMatrix`.

**Comment by TheOneric** [comment]
I’ll take the lack of reply as everything being clear now. If you still have questions feel free to reopen (if directly related) or create a new issue.

**Comment by buzai** [comment]
@astiob I read through the source code for libass and demo earlier, and this is the function I wrote at that time, This lib is really complicated, especially the rendering part


`void savePng(image_t *image, const char *filename) {
         if (!image || !image->buffer) {
             std::cerr << "Error: Invalid image data." << std::endl;
             return;
         }
        cv::Mat alphaMask(image->height, image->width, CV_8UC3, image->buffer);

         // Save the image using OpenCV
         cv::imwrite(filename, alphaMask);
     }`
