### ISSUE TITLE
How to blend ASS_Image to a rgba bitmap

### ISSUE THREAD

**Issue by debugly** [libass/libass#740]
I can't find right way to blend ASS_Image to a rgba bitmap，only find the test demo, but not contained alpha!

https://github.com/libass/libass/blob/c047dd2ea16f73abb4f448e6db3637158c1226d0/test/test.c#L134-L158

Anyone can help me，add alpha channel blend logic ?

Very grateful!

**Comment by cubicibo** [comment]
Let $k$ be the alpha of the new pixel to blend on top of existing bitmap (dst).

Alpha overlaying ($\alpha_0$ is the alpha of the current pixel of the destination):
$\alpha = k + (1-\alpha_0)$

RGB blending with alpha: (C is either R, G, or B)
$C = (C_{1} \cdot k + C_{0} \cdot \alpha_0 \cdot (1-k))\cdot \alpha^{-1}$
$\alpha_0 = k$

You must multiply every coefficient by 255 if you wish to user integer math.

**Comment by arch1t3cht** [comment]
The formula for $\alpha$ doesn't look correct. If $k$ is $1$ and $\alpha_0$ is $0$ then this would be $2$. It should be
$$\alpha = 1 - (1 - k)(1 - \alpha_0)$$
instead.

To see why: Blending one RGBA image $I_2$ onto another one $I_1$ is asking for an RGBA image $B$ such that blending $B$ onto some RGB image $I_0$ is equivalent to first blending $I_1$ and then blending $I_2$. Letting $C_0$, $C_1$, and $C_2$ be the colors of (some RGB channel of) some pixel of $I_0$, $I_1$, I_2$ respectively and letting $\alpha_1$ and $\alpha_2$ be the alpha values of that pixel in $I_1$ and $I_2$, the resulting color of that pixel when blending $I_1$ onto $I_0$ is
$$(1 - \alpha_1)\cdot C_0 + \alpha_1\cdot C_1.$$
Blending $I_2$ onto this yields
$$(1 - \alpha_2)\cdot ((1 - \alpha_1)\cdot C_0 + \alpha_1\cdot C_1) + \alpha_2\cdot C_2.$$
Rearranging, we get
$$(1 - \alpha_2)\cdot (1 - \alpha_1)\cdot C_0 + (1 - \alpha_2)\cdot\alpha_1\cdot C_1 + \alpha_2\cdot C_2.$$
Letting $A := 1 - (1 - \alpha_2)\cdot (1 - \alpha_1)$, we see that this is equal to
$$(1 - A)\cdot C_0 + A\cdot \frac{(1 - \alpha_2)\cdot\alpha_1\cdot C_1 + \alpha_2\cdot C_2}{A}.$$
So the alpha of the corresponding pixel in $B$ should be $A$ and the color value should be
$$\frac{(1 - \alpha_2)\cdot\alpha_1\cdot C_1 + \alpha_2\cdot C_2}{A}.$$

**Comment by cubicibo** [comment]
Thanks, yes, I fixed that up right before you posted.

**Comment by MrSmile** [comment]
You can look how [I'm doing it](https://github.com/libass/libass/blob/master/compare/compare.c#L61) in `compare`. Note that it's premultiplied with inverted alpha (AR, AG, AB, 1−A).
