### ISSUE TITLE
Rendering: Difference in font size with Roboto Medium in VSFilter and libass

### ISSUE THREAD

**Issue by raziel711** [libass/libass#758]
### Screenshots

MPC-HC (internal subtitle renderer): 
![mpc-hc](https://github.com/libass/libass/assets/75226602/739d3c17-70a3-469a-90ac-ce5b749ce797)

mpv:
![mpv](https://github.com/libass/libass/assets/75226602/61d1338b-4ae4-4254-b539-4935b644b350)

### Description of the issue

With subtitles with Roboto Medium as a font for the main dialogue, the font size consistently looks larger when played with VSFilter than with a libass renderer like mpv.

Font:
[font.zip](https://github.com/libass/libass/files/15172303/font.zip)

### libass version

mpv v0.38.0-91-g69d70148 from https://github.com/zhongfly/mpv-winbuild

### Is it a regression?

No

### ASS Sample

Subtitle file:
[subtitle.zip](https://github.com/libass/libass/files/15170657/subtitle.zip)

Sample video:

[sample.zip](https://github.com/libass/libass/files/15172437/sample.zip)

The issue in the screenshot comparison is with the Main style in the script:
`Style: Main,Roboto Medium,26,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1.3,0,2,20,20,23,1`

### Special Fonts

I uploaded or linked to the required font

### System Information

OS: Windows 10 Pro 22H2 19045.4355
CPU: Intel(R) Core(TM) i9-10885H

### Log

[log.txt](https://github.com/libass/libass/files/15172292/log.txt)

**Comment by astiob** [comment]
I can’t reproduce your MPC-HC screenshot in my MPC-HC. It looks the same as the mpv screenshot. I’ve tried the internal VSFilter, the internal libass, and XySubFilter.

**Comment by raziel711** [comment]
I think I figured out what the problem was.  I had a different version of Roboto Medium installed as a system font and MPC-HC was using that instead of the version of the font embedded in the mkv.  After updating Roboto to match the version embedded in the mkv on my system, MPC-HC now looks the same as mpv.
