### ISSUE TITLE
build: Windows 10 + msys2 (with winiconv): passing argument 2 of 'iconv' from incompatible pointer type

### ISSUE THREAD

**Issue by vtorri** [libass/libass#762]
### libass version

0.17.2

### Is it a regression?

yes (0.17.1 was fine)

### How did you invoke configure?

CPPFLAGS="$CPPFLAGS -I$HOME/ewpi_64/include -I$HOME/ewpi_64/include/fribidi -I$HOME/ewpi_64/include/freetype2 -I$HOME/ewpi_64/include/harfbuzz" ./configure --prefix=$3 --host=$4 --disable-static

### System Information

Window 10, using MSYS2+ mingw-w64

### Toolchain

x86_64-w64-mingw32 gcc 14.1.0

### Log of the error

```
libass/ass.c: In function 'sub_recode':
libass/ass.c:1401:35: error: passing argument 2 of 'iconv' from incompatible pointer type [-Wincompatible-pointer-types]
 1401 |                 rc = iconv(icdsc, &ip, &ileft, &op, &oleft);
      |                                   ^~~
      |                                   |
      |                                   char **
In file included from libass/ass.c:32:
C:/Documents/msys2/home/vincent.torri/ewpi_64/include/iconv.h:17:48: note: expected 'const char **' but argument is of type 'char **'
   17 | size_t iconv(iconv_t cd, WINICONV_CONST char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
      |                                              
```

### Additional info

using [winiconv](https://github.com/win-iconv/win-iconv)

**Comment by TheOneric** [comment]
`char **` or more specifically `char **restrict` is the correct type; your iconv headers are broken  
See: https://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv.html

(there used to be an error in the spec where the version documented in the `iconv.h` header didn’t match the version of the `iconv`’ function itself, but that was fixed ages ago. SOme system’s retain a `const` version anyway, but they also configure their compilers to not error on this by default)

win-iconv defaults to a non-compliant setup and you need a build time toggle to make it behave correctly; https://github.com/win-iconv/win-iconv/issues/25

**Comment by vtorri** [comment]
actually, winiconv can modify the constness with WINICONV_CONST, now it works.
maybe gcc 14 changed something, but 0.17.1 did compile when i tried it, as its compilation was part of my package manager. So I'm sure it compiled.
anyway, it is fixed, now
