### ISSUE TITLE
warning: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argumentbuild: 

### ISSUE THREAD

**Issue by vtorri** [libass/libass#763]
### libass version

0.17.2

### Is it a regression?

no

### How did you invoke configure?

CPPFLAGS="$CPPFLAGS -I$HOME/ewpi_64/include -I$HOME/ewpi_64/include/fribidi -I$HOME/ewpi_64/include/freetype2 -I$HOME/ewpi_64/include/harfbuzz" ./configure --prefix=$3 --host=$4 --disable-static

### System Information

windows 10

### Toolchain

w86_64-w64-mingw32 gcc 14.1.0

### Log of the error

several calloc() invocations reverse the order of num and size args :
```
warning: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument
```

### Additional info

if you want, i can provide a PR

**Comment by rcombs** [comment]
PR welcome; otherwise, please specify which invocations this is referring to.

**Comment by vtorri** [comment]
ok, I'll provide a PR

**Comment by vtorri** [comment]
see #764
