### ISSUE TITLE
Rendering: Start Delay Issue in libass Rendering Karaoke Subtitles

### ISSUE THREAD

**Issue by youkaio** [libass/libass#776]
### Description of the issue

**To further incentivize a solution, I am offering a $500 reward for fixing this problem.**

My name is Adam, and I am the creator of Youka, a karaoke maker program that utilizes libass to render karaoke subtitles and burn them using ffmpeg.

I have encountered an issue where the start of the karaoke subtitles is sometimes delayed, which makes it difficult for users to sing along accurately. Unfortunately, I have not been able to identify a consistent pattern for this delay, but it significantly impacts the user experience.

On the web (Electron), I am using the JavascriptSubtitlesOctopus library to render the subtitles. The delay issue is present in both the web and ffmpeg.

I am attaching an example .ass file where the delay occurs at approximately 00:45.98 (Line starts with: "You think"). Your assistance in diagnosing and resolving this issue would be greatly appreciated.

### libass version

0.17.0 bef4b43

### Is it a regression?

No.

### ASS Sample

[Script Info]
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Youka,Arial Bold,32,&Hd08521&,&Hffffff&,&H000000&,&Hffffff&,1,0,0,0,100,100,0,0,1,3,0,2,10,10,50,-1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,00:00:45.98,00:00:49.39,Youka,,0,0,0,,{\an2}{\fad(500,250)}{\K100}{\K14}You {\K4}{\K18}think {\K4}{\K12}I'm {\K6}{\K36}jumpin' {\K4}{\K14}out {\K4}{\K14}the {\K4}{\K34}window? {\K4}{\K16}How {\K6}{\K8}I {\K4}{\K20}got {\K6}{\K10}'em {\K6}{\K32}open?

### Special Fonts

The issue doesn't depend on a specific font

**Comment by rcombs** [comment]
Is this consistent for a given file, or does it vary across attempts? You said this happens in ffmpeg; do you have an ffmpeg invocation that reproduces it? By "delay", do you mean "the output doesn't match what you expect at a particular timestamp", or "rendering a frame takes longer than expected, leading to stuttering during playback"?

**Comment by youkaio** [comment]
Thanks @rcombs.

> Is this consistent for a given file, or does it vary across attempts? 

It consistent for a given file.

> do you have an ffmpeg invocation that reproduces it?

ffmpeg -y -i video.mp4 -i instruments.m4a -filter_complex ass=transcription.ass -map 0:0 -map 1 -preset medium -crf 18 -pix_fmt yuv420p

> By "delay", do you mean "the output doesn't match what you expect at a particular timestamp", or "rendering a frame takes longer than expected, leading to stuttering during playback"?

The output doesn't match what you expect at a particular timestamp. The karaoke effect should start earlier than it does.

**Comment by rcombs** [comment]
Can you produce a .ass sample with a single dialogue line that reproduces the issue, and a particular timestamp that it happens at, for use with the `test` tool provided with libass? Something like `test/test output.png input.ass 46.2`.

Please verify if you get the same output using VSFilter.

**Comment by youkaio** [comment]
## time
45.98

## ass
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Youka,Arial Bold,32,&Hd08521&,&Hffffff&,&H000000&,&Hffffff&,1,0,0,0,100,100,0,0,1,3,0,2,10,10,50,-1
Style: Youka 2,Arial Bold,32,&Hf63d9a&,&Hffffff&,&H000000&,&Hffffff&,1,0,0,0,100,100,0,0,1,3,0,8,10,10,50,-1
Style: Youka 3,Arial Bold,32,&Hde3df5&,&Hffffff&,&H000000&,&Hffffff&,1,0,0,0,100,100,0,0,1,3,0,5,10,10,50,-1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,00:00:45.98,00:00:49.39,Youka,,0,0,0,,{\an2}{\fad(500,250)}{\K100}{\K14}You {\K4}{\K18}think {\K4}{\K12}I'm {\K6}{\K36}jumpin' {\K4}{\K14}out {\K4}{\K14}the {\K4}{\K34}window? {\K4}{\K16}How {\K6}{\K8}I {\K4}{\K20}got {\K6}{\K10}'em {\K6}{\K32}open?

**Comment by youkaio** [comment]
Thanks @clsid2, my bad, the karaoke effect should start at 46.098.

**Comment by youkaio** [comment]
@rcombs I ran the test util, here's the output:

```
./test bug.jpg bug.ass 46.98
test.c: Available font providers (4): 'None', 'Autodetect', 'CoreText', 'Fontconfig'.
libass: libass API version: 0x1702000
libass: libass source: tarball: 0.17.2
libass: Raster: FreeType 2.13.2
libass: Shaper: FriBidi 1.0.14 (SIMPLE) HarfBuzz-ng 8.4.0 (COMPLEX)
libass: Initialized
libass: Using font provider coretext
libass: File size: 1080
libass: [0x6000019a0120] Style: Youka,Arial Bold,32,&Hd08521&,&Hffffff&,&H000000&,&Hffffff&,1,0,0,0,100,100,0,0,1,3,0,2,10,10,50,-1
libass: Added subtitle file: 'bug.ass' (2 styles, 2 events)
libass: fontselect: (Arial Bold, 700, 0) -> /System/Library/Fonts/Supplemental/Arial Bold.ttf, -1, Arial-BoldMT
24 images blended
```

**Comment by pjeanjean** [comment]
For me, the subtitles start properly at 46.98. There is no delay with libass, this is exactly what the line you posted should do: start at `00:00:45.98`, then wait 1s with `{\K100}`. I think you just forgot to make the line start earlier after applying the 1s wait.

![image](https://github.com/libass/libass/assets/7363343/074b0805-00b6-4c66-863e-7a0a49103a84)

**Comment by youkaio** [comment]
Thanks, @pjeanjean. The ASS file is automatically generated based on auto alignment. All the other lines appear on time, but this one does not. The first thing I did was check my alignment to the ASS code, but I can't explain why this issue occurs only with this line.

**Comment by youkaio** [comment]
@rcombs @clsid2  @pjeanjean 

After further investigation, I discovered that the bug in my ASS generation code was unrelated to libass. I appreciate your support and would like to offer you free access to Youka for one year as a token of my gratitude. If you're interested, please let me know, and after you complete your first signup, I'll upgrade your account. Thanks again!
