### ISSUE TITLE
How to select Cascadia Mono font?

### ISSUE THREAD

**Issue by kasper93** [libass/libass#785]
STR:
1. Install fonts from https://github.com/microsoft/cascadia-code
2. Try to use `Cascadia Mono` font
3. 
```
fontselect: ('Cascadia Mono', 327, 0) -> CascadiaCode-Regular, 0, CascadiaCode-Regular4. 
```

libass: 306bf76ca5ac05d936614e5c2ffc23aeac6dfb63
Tried with fontconfig and DirectWrite, result is similar.

How to use `Cascadia Mono`?

**Comment by astiob** [comment]
I’m afraid we’ll need more information about how you installed the fonts. When I download the latest release and inspect CascadiaMono-Regular.otf and CascadiaMono-Regular.ttf and even CascadiaMono.ttf (as much as libass doesn’t fully support variable fonts), none of them contain any CascadiaCode names. My copy of Windows has these fonts already installed (from Windows Terminal), and mpv selects the appropriate face without problem:

```
[sub/ass] fontselect: (Cascadia Mono, 400, 0) -> CascadiaMono-Roman, 0, CascadiaMono-Roman
[sub/ass] fontselect: (Cascadia Code, 400, 0) -> CascadiaCode-Roman, 0, CascadiaCode-Roman
```

**Comment by TheOneric** [comment]
For the sake of completeness, even with the `327` weight, i can't reproduce “Cascadia Code” being selected with all static ttf variants installed for fontconfig (and for the latter additionally also muxed):

Nothing muxed:
```
[sub/ass] fontselect: (Cascadia Mono, 400, 0) -> ~/.fonts/CascadiaCode/CascadiaMono-Regular.ttf, 0, CascadiaMono-Regular
[sub/ass] fontselect: (Cascadia Mono, 327, 0) -> ~/.fonts/CascadiaCode/CascadiaMono-SemiLight.ttf, 0, CascadiaMono-SemiLight
```

All variants muxed and installed:
*(note how a system font fallback get selected for your original weight query)*
```
[sub/ass] fontselect: (Cascadia Mono, 400, 0) -> CascadiaMono-Regular, 0, CascadiaMono-Regular
[sub/ass] fontselect: (Cascadia Mono, 327, 0) -> ~/.fonts/CascadiaCode/CascadiaMono-SemiLight.ttf, 0, CascadiaMono-SemiLight
```

**Comment by TheOneric** [comment]
Just nopticed your logs have single quotes around the font name; did you put those quotes into the ASS source? There shouldn't be any quotes around fontnames in ASS

**Comment by kasper93** [comment]
> I’m afraid we’ll need more information about how you installed the fonts.

I've downloaded the latest release 2404.23 and `Install for all users` all from `static` folder.

> hen I download the latest release and inspect CascadiaMono-Regular.otf and CascadiaMono-Regular.ttf and even CascadiaMono.ttf (as much as libass doesn’t fully support variable fonts), none of them contain any CascadiaCode names.

Sorry, I wasn't clear enough. It fallback to default font, which in my case was `Cascadia Code`. The problem is I cannot seem to select Mono variant.

If I remove default font it just do this:
```
fontselect: ('Cascadia Mono', 400, 0) -> ArialMT, 0, ArialMT
```

> My copy of Windows has these fonts already installed (from Windows Terminal), and mpv selects the appropriate face without problem:

I did another take on that. And it is PEBKAC...

**Comment by astiob** [comment]
> All variants muxed and installed:
> _(note how a system font fallback get selected for your original weight query)_

While I’m glad that the original issue is now understood, what’s going on _here?_

**Comment by kasper93** [comment]
> (as much as libass doesn’t fully support variable fonts)

Unrelated to this issue. I've seen some issues about it. Just a note from me. It works a lot better with fontconfig as opposed to DirectWrite. DirectWrite seems to select only from Regular/Bold variants, but fontconfig does seem to support it "correctly", if you look closely the selection seems weird at times (600 for 845, instead of 700 which is closer), but it is trying. I don't know the libass logic and internals enough to comment more, just wanted to comment on this.

```
[  3.453177]        osd/libass: fontselect: (Cascadia Mono NF, 400, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 0, CascadiaMonoNF-Regular
[  4.208392]        osd/libass: fontselect: (Cascadia Mono NF, 200, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 65536, CascadiaMonoNFRoman_200wght
[  4.208912]        osd/libass: fontselect: (Cascadia Mono NF, 700, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  4.209230]        osd/libass: fontselect: (Cascadia Mono NF, 692, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  4.209524]        osd/libass: fontselect: (Cascadia Mono NF, 697, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  4.445464]        osd/libass: fontselect: (Cascadia Mono NF, 819, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[  4.445940]        osd/libass: fontselect: (Cascadia Mono NF, 525, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 196608, CascadiaMonoNFRoman_350wght
[  5.445652]        osd/libass: fontselect: (Cascadia Mono NF, 849, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[  5.446113]        osd/libass: fontselect: (Cascadia Mono NF, 460, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[  6.446215]        osd/libass: fontselect: (Cascadia Mono NF, 796, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[  6.446714]        osd/libass: fontselect: (Cascadia Mono NF, 458, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[  7.446217]        osd/libass: fontselect: (Cascadia Mono NF, 695, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  7.446740]        osd/libass: fontselect: (Cascadia Mono NF, 694, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  8.446236]        osd/libass: fontselect: (Cascadia Mono NF, 734, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  8.446717]        osd/libass: fontselect: (Cascadia Mono NF, 652, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[  9.446398]        osd/libass: fontselect: (Cascadia Mono NF, 845, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[  9.446854]        osd/libass: fontselect: (Cascadia Mono NF, 470, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[ 10.447098]        osd/libass: fontselect: (Cascadia Mono NF, 846, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[ 10.447512]        osd/libass: fontselect: (Cascadia Mono NF, 469, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[ 11.447597]        osd/libass: fontselect: (Cascadia Mono NF, 462, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[ 12.447502]        osd/libass: fontselect: (Cascadia Mono NF, 461, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[ 13.447444]        osd/libass: fontselect: (Cascadia Mono NF, 850, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[ 14.447504]        osd/libass: fontselect: (Cascadia Mono NF, 847, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
[ 14.447927]        osd/libass: fontselect: (Cascadia Mono NF, 465, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 131072, CascadiaMonoNFRoman_300wght
[ 15.447551]        osd/libass: fontselect: (Cascadia Mono NF, 748, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 393216, CascadiaMonoNFRoman_700wght
[ 15.448027]        osd/libass: fontselect: (Cascadia Mono NF, 635, 0) -> C:/WINDOWS/fonts\CascadiaMonoNF.ttf, 327680, CascadiaMonoNFRoman_600wght
```

**Comment by astiob** [comment]
Oh, right, because the Fontconfig-provided SemiLight also has the VSFilter-incompatible `Cascadia Mono` as a family name and has a closer weight than the attached fonts, of which only CascadiaMono-Regular is detected to have this name. Just another case for #315.

**Comment by TheOneric** [comment]
> Just another case for https://github.com/libass/libass/issues/315.

Yep, checked the selection in more detail to confirm and was just about to write this
