### ISSUE TITLE
Add Windows GDI or DirectWrite fontselect

### ISSUE THREAD

**Issue by rcombs** [libass/libass#79]
After the general internal fontselect changes and CoreText provider are ready, we should look into a Windows provider. @grigorig's fonts branch has at least some amount of work done on a GDI provider (not sure how far along it is?), but we might want to look at DirectWrite instead, since WinXP is out of support anyway.

**Comment by feliwir** [comment]
Any news on this issue?

**Comment by astiob** [comment]
Nope. :(

**Comment by wm4** [comment]
Also it seems unlikely that grigorig will ever pick this up again.

I'm wondering why we can't just do the same as vsfilter, though. If we can, it should be "relatively" simple.

**Comment by astiob** [comment]
And doing the same as VSFilter would potentially be better for compatibility, too.

**Comment by grigorig** [comment]
The fonts branch in grigorig/libass now has a working DirectWrite backend.

**Comment by feliwir** [comment]
It was working fine for me on Win 8.1

**Comment by grigorig** [comment]
Done.
