### ISSUE TITLE
Rendering: Large widths (1000) are ignored on libass

### ISSUE THREAD

**Issue by matheousse** [libass/libass#803]
### Screenshots

mpv v0.38.0-487-gab0a5087

![mpv libass](https://github.com/libass/libass/assets/39730615/fcd9437e-72c1-4bfd-829c-ae0ade10bf69)

pf-xy-VSFilter_textsub via [arch1t3cht/Aegisub commit cb930ab](https://github.com/arch1t3cht/Aegisub/actions/runs/9602539365)

![aegisub xy-vsfilter](https://github.com/libass/libass/assets/39730615/652751c1-f101-44b0-ba84-423c6f7e7b3a)

### Description of the issue

Large widths (in this case, 1000) applied on characters such as `’` (U+2019) (can often be seen in Japanese fonts) are being ignored in libass, while VSFilter does take the width into account.
I should also note that this doesn't *always* happen with 1000-width characters, as `IwaOMinPro-Bd-Fate.ttf` does get correctly rendered while having similar metrics as `IWAMINPRO-BD-STR.OTF`
You can find 2 screenshots of the glyph's width taken via FontForge, the first one being the incorrectly rendered `IWAMINPRO-BD-STR.OTF` and the second shows `IwaOMinPro-Bd-Fate.ttf`, as well as a zip containing said fonts.
I have also attached a screenshot of mpv's rendering of `IwaOMinPro-Bd-Fate.ttf`.

[ghi.zip](https://github.com/user-attachments/files/16169967/ghi.zip)

![IWAMINPRO-BD-STR.OTF](https://github.com/libass/libass/assets/39730615/9e72c2af-21b0-485d-b522-b69e24269f17)
![IwaOMinPro-Bd-Fate.ttf](https://github.com/libass/libass/assets/39730615/f5f0aa99-a62f-4da3-977b-f8d0929af5fc)
![mpv iwaominpro-bd-fate](https://github.com/libass/libass/assets/39730615/77a88ce1-511f-4c9e-bd2b-a8d76098741e)

### libass version

0.17.2-25-gcd35a4dd80e3dbf09ab5ee9a3f793ae7e07191ce via mpv v0.38.0-487-gab0a5087

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9736-feature-0b8bc688f
; http://www.aegisub.org/
ScaledBorderAndShadow: yes
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
Timer: 0.0000
WrapStyle: 0
YCbCr Matrix: TV.709

[Aegisub Project Garbage]
Last Style Storage: Default
Audio File: ../[matheousse] Monogatari Series Off & Monster Season - 01 VOSTFR [WEB 1080p AAC] [F9D0B256].mkv
Video File: ../[matheousse] Monogatari Series Off & Monster Season - 01 VOSTFR [WEB 1080p AAC] [F9D0B256].mkv
Video AR Mode: 4
Video AR Value: 1.777778

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: MarySigns,IwaOMinPro-Fate-Bd-Regular-STR,50,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 1,0:05:15.58,0:05:18.71,MarySigns,,0,0,0,,{\pos(960,430)\fs80\fnIwataMinchoProM-Str\c&H901486&\blur0.6}C’est toi qui fais peur
```

### Special Fonts

I uploaded or linked to the required font

### System Information

OS: Windows 11 Home 22H2 22621.3810 64bit
CPU: 64bit AMD Ryzen 5600X

**Comment by moi15moi** [comment]
None of the font you shared correspond to ``IwataMinchoProM-Str``. 

IWAMINPRO-BD-STR.OTF
Family name: ``IwaMinPro-Bd-Str``
Postscript name: ``IwaMinPro-Bd-Str``

IwaOMinPro-Bd-Fate.ttf
Family name: ``Iwata Mincho Old Pro-Fate B``
Fullname: ``IwaOMinPro-Fate-Bd``

libass display both fonts like VSFilter.

**Comment by TheOneric** [comment]
Thanks for the report matheousse and looking into this moi15moi, seems related to #653 then. Unfortunately one of the heuristics to not break Apple-only fonts proposed over there of “hide morx iff GSUB exists” doesn't seem to work out for this sample, since afaict it doesn't have a GSUB table.

I can confirm there are substitution rules for `U+2016 quoteright` in this font to insert half-width or proportional variants. Additionally there seem to be some kerning rules which libass by default ignores and VSFilter’s *sometimes* apply depending on e.g. other glyphs.

Merging this into #653 to keep all morx-related considerations easy to find in one place
