### ISSUE TITLE
Rendering: Incorrect blur results between ffmpeg(composited video) vs jassub(library/browser)

### ISSUE THREAD

**Issue by lowkey-heonyoung** [libass/libass#810]
### Screenshots

| composited video(ffmpeg)    | browser(jassub) |
| -------- | ------- |
| <img width="800" alt="composited(ffmpeg)" src="https://github.com/user-attachments/assets/969af216-1d7c-4055-975d-37bcb695c1de"> | <img width="800" alt="preview(jassub)" src="https://github.com/user-attachments/assets/7918b5bd-a505-43e6-9d61-78e3a3ec9196">|

### Description of the issue

I'm using [jassub](https://github.com/ThaUnknown/jassub) library(which uses **libass**) to render ASS subtitles on the browser with `<video>` tag.
As you can see above Screenshots, especially when blur is applied, the results of **ffmpeg** and **jassub** are different.

(I've asked to **jassub** earlier, but it seems that this issue is coming from **libass**.)

**Details:**
I've set blur to **3** to `어때요` text, then do composite video through **ffmpeg** with ASS subtitle data.
I'll appreciate it if someone could help me.

### libass version

0.17.3

### Is it a regression?

No, it's first time.

### ASS Sample

[font files.zip](https://github.com/user-attachments/files/16451364/font.files.zip)

```
[Script Info]
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None
WrapStyle: 0
Collisions: Reverse

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Title,Pretendard ExtraBold,28,&H00ffffff,&H00ffffff,&H00000000,&H00000000,0,0,0,0,100,100,,,1,0.5,1.0,2,10,10,161,
Style: Title-box,Pretendard ExtraBold,28,&H00000000,&H00000000,&H00000000,&Hff000000,0,0,0,0,100,100,,,3,1.0,,2,10,10,161,
Style: Subtitle,KOTRA HOPE,44,&H001c1cd3,&H00ffffff,&H00000000,&Hf0000000,0,0,0,0,100,100,,,1,1.0,1.0,2,10,10,77,
Style: Custom1,NanumSquare Neo ExtraBold,44,&H001c1cd3,&H00ffffff,&H00000000,&H0022f6ff,0,0,0,0,100,100,,,1,2.0,2.4,2,10,10,77,
Style: Custom2,NanumSquare Neo ExtraBold,22,&H001c1cd3,&H00ffffff,&H00000000,&Hf0000000,0,0,0,0,100,100,,,1,1.0,1.0,2,10,10,77,

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 11,0:04:27.00,0:04:30.00,Title,,0,0,0,,{\blur6}자 오늘 주제는 뭐죠?
Dialogue: 10,0:04:27.00,0:04:30.00,Title-box,,0,0,0,,자 오늘 주제는 뭐죠?
Dialogue: 1,0:04:27.18,0:04:28.20,Subtitle,,0,0,0,,{\rCustom2}아니{\r} {\rCustom1}{\blur3}어때요?{\r}
```

### Special Fonts

I uploaded or linked to the required font

### System Information

MacOS (Sonoma 14.1) with Apple M3 Pro

**Comment by rcombs** [comment]
Looks like jassub isn't calling `ass_set_storage_size`. Blur has this kind of scaling behavior when that isn't called; this is expected. Please report downstream.

**Comment by lowkey-heonyoung** [comment]
> Looks like jassub isn't calling `ass_set_storage_size`. Blur has this kind of scaling behavior when that isn't called; this is expected. Please report downstream.

Thanks a lot for your help. I'll report it to them.

**Comment by astiob** [comment]
If by any chance you’re the author of the subtitles, you can also resolve this issue by adding `LayoutResX` and `LayoutResY` headers to your ASS, with values equal to your current video stream resolution.

**Comment by lowkey-heonyoung** [comment]
> If by any chance you’re the author of the subtitles, you can also resolve this issue (for recent versions of libass) by adding `LayoutResX` and `LayoutResY` headers to your ASS, with values equal to your current video stream resolution.

I'm trying to solve it by adding `LayoutResX` and `LayoutResY` according to your comment, but it fails unfortunately.
Thanks for your comment.

---

the **jassub** library owner will try debug it soon.
https://github.com/ThaUnknown/jassub/issues/45#issuecomment-2262844842

**Comment by astiob** [comment]
> I'm trying to solve it by adding `LayoutResX` and `LayoutResY` according to your comment, but it fails unfortunately.

If adding the headers does nothing, then your copy of jassub is probably using an old version of libass.

**Comment by TheOneric** [comment]
jassub git indeed has an older libass version from about a year ago, but this is still new enough for `LayoutRes*`. There also was a npm release last week, albeit the last git tag is from 2020 and inherited from JSO. TO make sure: did you really use the **video** resolution from the video stream used in the “composite” example image? Judgin from the screenshot it should probably be:
```
LayoutResX: 1920
LayoutResY: 1080
```

If you used another value the effect will be different. If you used that _and_ use newest jassub, somethings off but most likely the problem is inside jassub or your particular configuration of it.

**Comment by lowkey-heonyoung** [comment]
Sorry my bad. If I set `LayoutResX` and `LayoutResY` fields appropriately, it's working well.
Thanks for your help. @astiob @TheOneric
