### ISSUE TITLE
Rendering: Drawing with \N is different

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#814]
### Screenshots

libass
![image](https://github.com/user-attachments/assets/cc802416-c075-42f9-b0ba-1aaea5baf370)

xy-VSFilter
![image](https://github.com/user-attachments/assets/ce7e3fe5-48a3-4d8b-aac1-98ce5a671e42)

### Description of the issue

xy-VSFilter display a totally different draw.
If I remove the ``\N`` in the draw, libass has the same draw as xy-VSFilter.

xy-VSFilter ignore the coordinate after the ``\N``.
Note what you can replace ``\N`` with any character except ``l`` and ``p`` and it will also ignore the coordinates after that character.

### libass version

0.17.1

### Is it a regression?

No

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9746-feature-aa68c2e66
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:03.00,Default,,0,0,0,,{\an7\pos(0,0)\bord0\shad0\p1}m 664 328 l 1232 328 1232 600 664 600 m 670 334 l 670 594 1226 594\N1226 334
```

### Special Fonts

The issue doesn't depend on a specific font

**Comment by TheOneric** [comment]
> libass version
> 0.17.1

This was already fixed in 0.17.2
