### ISSUE TITLE
ASS v5.0  Vertical spacing tag (\fspy)

### ISSUE THREAD

**Issue by jxaujunjun** [libass/libass#823]
How to use, can you give a specific example, thank you

**Comment by astiob** [comment]
ASS v5.0 doesn’t exist, and neither does a vertical spacing tag. You can’t use it. If you’re asking this because you’ve seen it mentioned on our wiki, that’s just a wish list of what people would like to have sometime in the future. However, there are no concrete plans for implementing any of it.

**Comment by jxaujunjun** [comment]
Thank you. Is there a field that controls line spacing? Thank you

**Comment by TheOneric** [comment]
There is none. If you have pre-determined linebreaks you can insert an additional empty or `\h` line in-between and scale its size with `\fs`.

**Comment by jxaujunjun** [comment]
> There is none. If you have pre-determined linebreaks you can insert an additional empty or `\h` line in-between and scale its size with `\fs`.

\fs is to control the size of the text, I am Chinese can not use space, there are other ways or relevant examples recommended, thank you

**Comment by TheOneric** [comment]
`\fs` can be used to scale the size of inserted spacing lines. Completely empty lines only take up half the space of lines containing e.g an `\h` character. Here’s an example:
```ini
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an1}Line 1\N{\fs+0}\N{\fs}Line 2
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an2}Line 1\N{\fs+30}\N{\fs}Line 2
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an3}Line 1\N{\fs+30}\h\N{\fs}Line 2
```

![line-scaling.png](https://github.com/user-attachments/assets/315319b7-c599-4c4b-8fa8-1ea6609adfe6)

For more info and options read https://github.com/libass/libass/issues/625

**Comment by jxaujunjun** [comment]
> `\fs` can be used to scale the size of inserted spacing lines. Completely empty lines only take up half the space of lines containing e.g an `\h` character. Here’s an example:
> 
> ```ini
> Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an1\pos(10,1070)}Line 1\NLine 2
> Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an1\pos(310,1070)}Line 1\N{\fs+0}\N{\fs}Line 2
> Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an2}Line 1\N{\fs+30}\N{\fs}Line 2
> Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an3}Line 1\N{\fs+30}\h\N{\fs}Line 2
> ```
> 
> ![line-scaling.png](https://private-user-images.githubusercontent.com/1668471/366440794-b1770a97-0169-4aeb-9a60-1b9295303103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE0MjcsIm5iZiI6MTcyNjA2MTEyNywicGF0aCI6Ii8xNjY4NDcxLzM2NjQ0MDc5NC1iMTc3MGE5Ny0wMTY5LTRhZWItOWE2MC0xYjkyOTUzMDMxMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTMyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTljYmRlZDg2NjlmMjAyOWZmMWZlODhjY2YwMzIwMDVhNmM2M2Q1NmM2MTIyYmI1NDhhZjhmODMxN2I0MzJjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VRM92n4MgeIY9nD049ZYGYYrMd9XUpOJIJblZGb7pHc)
> 
> For more info and options read #625

> 
Thank you very much for your reply. {\fs+30}\N{\fs} This is not an identif{\fs+30}\N{\fs}ier \N occupies a vertical distance of 30 pixels


Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(205,205)}{\fsp20}test\Nrock
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(500,500)}{\fsp20}test\N{\fs+0}\N{\fs}rock
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(700,700)}{\fsp20}test\N{\fs+30}\N{\fs}rock
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(900,900)}{\fsp20}test\N{\fs+60}\N{\fs}rock
> 
![微信图片_20240911212646](https://github.com/user-attachments/assets/0846a631-ffce-49f5-a783-b817ff20d80d)

**Comment by TheOneric** [comment]
To avoid confusion `a\N{\fs+30}\N{\fs}b` does *not* necessarily result in a 30 pixel gap. `\fs+N` increases the empty lines font size relative to the previous font size via `newfs = oldfs * (1.0 + N / 10)`. Similarly `\fs-N` decreases font size by an relative amount.
If you want a fixed amount of pixels as spacing use absolute font sizes *(no `+` or `-` prefix)*

**Comment by astiob** [comment]
For extra clarity, if you want to add a fixed gap of, say, 12345 pixels, you can use:

* `test\N{\fs12345}\N\N{\fs}rock`
* `text\N{\fs24690}\N{\fs}rock`
* `text\N{\fs12345}\h\N{\fs}rock`

As mentioned above, a fully blank line has its height halved. `\h` is U+00A0 NO-BREAK SPACE, which _looks_ blank but does not count as a blank line; although you should ideally ensure that your font actually has a glyph for it.

If instead you want the line height to be scaled relative to the font size, use the other syntax suggested, `\fs+` or `\fs-`.

If you want to set your lines closer together instead of wider apart, that’s unfortunately impossible with tricks like this. You’ll have to split the event and explicitly position each line—or to modify the font file (instead of the subtitles) to reduce its line height.

---

Also, if you ever put a lot of lines in a single event (e. g. a whole letter or poem), be aware that the actual heights may be very slightly different due to subpixel rounding when rendered in VSFilter: this is usually unnoticeable but can add up to a visible difference after many lines.

**Comment by jxaujunjun** [comment]
> For extra clarity, if you want to add a fixed gap of, say, 12345 pixels, you can use:
> 
> * `test\N{\fs12345}\N\N{\fs}rock`
> * `text\N{\fs24690}\N{\fs}rock`
> * `text\N{\fs12345}\h\N{\fs}rock`
> 
> As mentioned above, a fully blank line has its height halved. `\h` is U+00A0 NO-BREAK SPACE, which _looks_ blank but does not count as a blank line; although you should ideally ensure that your font actually has a glyph for it.
> 
> If instead you want the line height to be scaled relative to the font size, use the other syntax suggested, `\fs+` or `\fs-`.
> 
> If you want to set your lines closer together instead of wider apart, that’s unfortunately impossible with tricks like this. You’ll have to split the event and explicitly position each line—or to modify the font file (instead of the subtitles) to reduce its line height.
> 
> Also, if you ever put a lot of lines in a single event (e. g. a whole letter or poem), be aware that the actual heights may be very slightly different due to subpixel rounding when rendered in VSFilter: this is usually unnoticeable but can add up to a visible difference after many lines.

Thank you for your reply. Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels  #？
![1111](https://github.com/user-attachments/assets/f0b586fa-6af3-4e51-96ac-b2c29a6aa945)




[Script Info]
; Script generated by Aegisub
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&HCD0000,&H000000,&HA730EE,&H3D8B6E,-1,0,0,0,100,100,0,0.00,0,0,0,7,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(205,205)}{\fsp20}aaa\N111
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(500,500)}{\fsp20}aaa\N{\fs+0}\N{\fs}222
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(700,700)}{\fsp20}aaa\N{\fs30}\N{\fs}333
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(800,800)}{\fsp20}aaa\N{\fs+30}\N{\fs}444
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(900,900)}{\fsp}aaa\N{\fs30}\N{\fs}555

**Comment by jxaujunjun** [comment]
> Thank you for your reply. Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels #？ ![1111](https://private-user-images.githubusercontent.com/18544541/366692234-f0b586fa-6af3-4e51-96ac-b2c29a6aa945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDYzNzksIm5iZiI6MTcyNjEwNjA3OSwicGF0aCI6Ii8xODU0NDU0MS8zNjY2OTIyMzQtZjBiNTg2ZmEtNmFmMy00ZTUxLTk2YWMtYjJjMjlhNmFhOTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxNTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZTY4MmEwMDU2MGM1MzI2NjE3MTY5NDE3MGQ3NWFhOTgzZmJlNDgyNmFhNGE3YTU1MDIwYmZkY2JjOTkwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vs3vF_3f1aHPWg7rGBFvd9xNPU3FSDhrvkR92W0tVGs)
> 
> [Script Info] ; Script generated by Aegisub ; http://www.aegisub.org/ Title: Default Aegisub file ScriptType: v4.00+ WrapStyle: 0 PlayResX: 1920 PlayResY: 1080
> 
> [V4+ Styles] Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding Style: Default,Arial,20,&HCD0000,&H000000,&HA730EE,&H3D8B6E,-1,0,0,0,100,100,0,0.00,0,0,0,7,0,0,0,1
> 
> [Events] Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(205,205)}{\fsp20}aaa\N111 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(500,500)}{\fsp20}aaa\N{\fs+0}\N{\fs}222 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(700,700)}{\fsp20}aaa\N{\fs30}\N{\fs}333 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(800,800)}{\fsp20}aaa\N{\fs+30}\N{\fs}444 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(900,900)}{\fsp}aaa\N{\fs30}\N{\fs}555



> Thank you for your reply. Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels #？ ![1111](https://private-user-images.githubusercontent.com/18544541/366692234-f0b586fa-6af3-4e51-96ac-b2c29a6aa945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDYzNzksIm5iZiI6MTcyNjEwNjA3OSwicGF0aCI6Ii8xODU0NDU0MS8zNjY2OTIyMzQtZjBiNTg2ZmEtNmFmMy00ZTUxLTk2YWMtYjJjMjlhNmFhOTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxNTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZTY4MmEwMDU2MGM1MzI2NjE3MTY5NDE3MGQ3NWFhOTgzZmJlNDgyNmFhNGE3YTU1MDIwYmZkY2JjOTkwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vs3vF_3f1aHPWg7rGBFvd9xNPU3FSDhrvkR92W0tVGs)
> 
> [Script Info] ; Script generated by Aegisub ; http://www.aegisub.org/ Title: Default Aegisub file ScriptType: v4.00+ WrapStyle: 0 PlayResX: 1920 PlayResY: 1080
> 
> [V4+ Styles] Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding Style: Default,Arial,20,&HCD0000,&H000000,&HA730EE,&H3D8B6E,-1,0,0,0,100,100,0,0.00,0,0,0,7,0,0,0,1
> 
> [Events] Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(205,205)}{\fsp20}aaa\N111 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(500,500)}{\fsp20}aaa\N{\fs+0}\N{\fs}222 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(700,700)}{\fsp20}aaa\N{\fs30}\N{\fs}333 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(800,800)}{\fsp20}aaa\N{\fs+30}\N{\fs}444 Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(900,900)}{\fsp}aaa\N{\fs30}\N{\fs}555


Thank you for your reply. Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels #？

![Uploading 1111.png…]()


[Script Info]
; Script generated by Aegisub
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&HCD0000,&H000000,&HA730EE,&H3D8B6E,-1,0,0,0,100,100,0,0.00,0,0,0,7,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(205,205)}{\fsp20}aaa\N111
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(500,500)}{\fsp20}aaa\N{\fs+0}\N{\fs}222
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(700,700)}{\fsp20}aaa\N{\fs30}\N{\fs}333
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(800,800)}{\fsp20}aaa\N{\fs+30}\N{\fs}444
Dialogue: 0,0:00:00.00,0:00:59.90,Default,,0,0000,0,,{\pos(900,900)}{\fsp}aaa\N{\fs30}\N{\fs}555

**Comment by astiob** [comment]
> Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels #？

It’s 15. Because you have a blank line at \fs30:

> \N{\fs30}\N

there’s nothing between the two line breaks, so the line is blank. And as the line is blank, its height is halved.

The remaining 5 pixels you’ve measured are probably just the descender space below the `aaa`, which is part of the `aaa` line. If you put `ggg` instead, the hooks of the `g`s will occupy this space. The next line doesn’t begin until after this space ends.

**Comment by jxaujunjun** [comment]
> > Why is the spacing of aaa\N{\fs30}\N{\fs}333 20 pixels instead of 30 pixels #？
> 
> It’s 15. Because you have a blank line at \fs30:
> 
> > \N{\fs30}\N
> 
> There’s nothing between the two line breaks, so the line is blank. And as the line is blank, its height is halved.
> 
> The remaining 5 pixels you’ve measured are probably just the descender space below the `aaa`, which is part of the `aaa` line. If you put `ggg` instead, the hooks of the `g`s will occupy this space. The next line doesn’t begin until after this space ends. (The `555` line may also have a little extra ascender space at the top, depending on the font, but likely much less than the descender space below `aaa`.)


Thank you for your reply, aaa\N{\fs30}\N{\fs}555 is not the first \N occupies half the height of the font, and then the second \N occupies 15 pixels in height

**Comment by jxaujunjun** [comment]
aaa{fs30}\N\N{\fs}444
aaa\N{fs30}N{\fs}444

What is the difference between the two? Can you give specific examples? Thank you.

**Comment by astiob** [comment]
> aaa\N{\fs30}\N{\fs}555 is not the first \N occupies half the height of the font, and then the second \N occupies 15 pixels in height

The first \N terminates the first line, which is not blank because it contains `aaa`. The height of the first line is the initial value of Fontsize in pixels.

The second \N terminates the second line, which is blank because there’s nothing else on that line besides the \N itself. The height of the second line is thus half of its \fs.

The third line contains `555`, so its height is the full value of its \fs, which in this case (due to the no-argument \fs tag) is the original value of Fontsize from the style definition, the same as the height of the `aaa` line.

> aaa{\fs30}\N\N{\fs}444  
> aaa\N{\fs30}\N{\fs}444
> 
> What is the difference between the two?

With `aaa{\fs30}\N` and an initial Fontsize of 20, you raise the height of the first line to 30, because the line break is sort of considered to be part of the line it terminates. If your Fontsize were 30 or bigger to begin with, this would have no effect, but as it is 20, this line becomes higher than usual to fit the 30-pixel-high \N.

With `aaa\N{\fs30}`, you don’t change the font size (line height) until after the line has truly ended, so it keeps its initial Fontsize of 20.

In both cases, the second line is blank because it contains only a single line break, its font size is 30, and so its actual height is 15 px.

**Comment by astiob** [comment]
See also [this Fansubbing Wiki FAQ](https://fansubbers.miraheze.org/wiki/Guide:Typesetting/Frequently_asked_questions#How_do_I_adjust_the_line_spacing_when_using_\N?), which describes another alternative approach.

**Comment by jxaujunjun** [comment]
> See also [this Fansubbing Wiki FAQ](https://fansubbers.miraheze.org/wiki/Guide:Typesetting/Frequently_asked_questions#How_do_I_adjust_the_line_spacing_when_using_%5CN?) or [this blog post](https://www.md-subs.com/blog/line-spacing-in-ssa), which describe another alternative approach.

Thank you
