### ISSUE TITLE
MacOS 15 ships some system fonts in a custom format FreeType can't parse yet

### ISSUE THREAD

**Issue by Tsukimeizi** [libass/libass#828]
when I play a movie with srt sub file, mpv can not display the sub and get the error as below:

[sub/ass] fontselect: (PingFang TC, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[sub/ass] Glyph 0x592A not found, selecting one more font for (PingFang TC, 400, 0)
[sub/ass] Error opening font: '/System/Library/PrivateFrameworks/FontServices.framework/Resources/Reserved/PingFangUI.ttc', 0

it seems that libass can not read macOS 15 Sequoia's new PingFang font.

**Comment by TheOneric** [comment]
It appears Apple invented a new format for here so atm no one but Apple  can use it: https://gitlab.freedesktop.org/freetype/freetype/-/issues/1281
