### ISSUE TITLE
Character width and height

### ISSUE THREAD

**Issue by jxaujunjun** [libass/libass#829]
How to calculate character width and height, can use specific languages, for example :python, thank you !

**Comment by TheOneric** [comment]
In general character width and height may mean several things. There’s _logical_ character size usually used for text layout and there’s _visual_ size which may be larger or smaller than the logical size depending on transforms and e.g. decorative elements in fonts.

But regardless, libass currently does not provide any API for either type; see: #348. You can more or less obtain the visual size of whole glyph runs by computing the bounding box of resulting `ASS_Image`s but if multiple mapping glyph runs appear simultaneously there’s no easy mapping between input text and `ASS_Image`s.

libass only provides C API, but almost everything can integrate C APIs so I’m sure it’s possible to use libass from Python, but we cannot help with that.
