### ISSUE TITLE
ScaledBorderAndShadow is set to no, but the subtitle shadows are still very heavy

### ISSUE THREAD

**Issue by shuiyi24** [libass/libass#831]
ScaledBorderAndShadow is set to no, but the subtitle shadows are still very heavy.  Both shadow and border are set to 1
![image](https://github.com/user-attachments/assets/9849df77-73ba-41f4-859e-2e0f7c025142)

**Comment by TheOneric** [comment]
I’m guessing the player you’re using does not set storage size therefore forcing libass to make a guess which ends up smaller than the real storage size in turn increasing the final border size. You’re post is severely missing in details though; if you need anything more provide all the same info as asked for in the “Wrong rendering report” template.
