### ISSUE TITLE
Line breaks cause render exceptions Render exceptions

### ISSUE THREAD

**Issue by tolink-Mengtianfu** [libass/libass#832]
Why do my line breaks cause render exceptions? For example, in the case of AAAA\\nBBB, only BBB is rendered; No line feed rendering;
I have to. Each pattern value of WrapStyle has been tried. They all have the same problem;

**Abnormal effect**
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/54d628c0-ca88-413a-b941-95ca059b7637">

**FonStyle**
        auto font = textEdit->currentFont;
        ASS_Style *style = (ASS_Style *)malloc(sizeof(ASS_Style));
        style->Name = strdup("Default");
        style->FontName = strdup(font.family().toUtf8().constData());
        style->FontSize = font.pointSize();
        style->PrimaryColour = 0x0000FF00; // bgr
        style->SecondaryColour = 0x000000FF; // bgr
        style->OutlineColour = 0x00000000; // bgr
        style->Bold = font.bold();
        style->Italic = font.italic();
        style->Underline = 1;
        style->StrikeOut = font.strikeOut();
        // style->Alignment = 0; // 居中对齐
        style->BorderStyle = 0; // 带边框
        style->Outline = 0;
        style->Shadow = 0;
        style->ScaleX = 1.0;
        style->ScaleY = 1.0;
        style->MarginL = 0;
        style->MarginR = 0;
        style->MarginV = 0;
        style->Encoding = 134;

**Core code**

SubtitleRenderer::SubtitleRenderer(int width, int height, ASS_Style *style, int rollDirection, int posX, int posY, int eventCount, int scrollSpeed, const char* scrollText)
    : width(width), height(height) {
    ass_library = ass_library_init();
    ass_renderer = ass_renderer_init(ass_library);

    // 创建一个 ASS_Track 并手动设置样式和事件
    ass_track = ass_new_track(ass_library);

    // 设置样式数量
    ass_track->max_styles = 1;
    ass_track->n_styles = 1;
    ass_track->styles = style;

    // 设置事件数量
    ass_track->max_events = eventCount;
    ass_track->n_events = eventCount;
    ass_track->events = (ASS_Event *)malloc(sizeof(ASS_Event) * ass_track->max_events);

    // 初始化样式和事件
    setupTrackStyles();
    setupTrackEvents(rollDirection, posX, posY, scrollSpeed, scrollText);

    ass_set_pixel_aspect(ass_renderer, 1.0);
    ass_set_frame_size(ass_renderer, width, height);
    ass_set_storage_size(ass_renderer, width, height);
    ass_set_fonts(ass_renderer, nullptr, ass_track->styles->FontName, 1, nullptr, 1);
}

SubtitleRenderer::~SubtitleRenderer() {
    // 释放资源
    for (int i = 0; i < ass_track->n_styles; ++i) {
        free((void*)ass_track->styles[i].Name);
        free((void*)ass_track->styles[i].FontName);
    }
    free(ass_track->styles);

    for (int i = 0; i < ass_track->n_events; ++i) {
        free((void*)ass_track->events[i].Effect);
        free((void*)ass_track->events[i].Text);
    }
    free(ass_track->events);

    ass_free_track(ass_track);
    ass_renderer_done(ass_renderer);
    ass_library_done(ass_library);
}

void SubtitleRenderer::setupTrackStyles() {
    ass_track->PlayResX = width;
    ass_track->PlayResY = height;
    ass_track->LayoutResX = width;
    ass_track->LayoutResY = height;
    ass_track->WrapStyle = 2;
}

void SubtitleRenderer::setupTrackEvents(int rollDirection, int posX, int posY, int scrollSpeed, const char* scrollText) {

    const char* effectFormat;
    // 定义滚动区域的 y1 和 y2
    int y1 = 0, y2 = 0;
    switch (rollDirection) {
    case 0: // 从左到右
        effectFormat = "Banner;%d;1"; // 向右滚动，左到右
        break;
    case 1: // 从右到左
        effectFormat = "Banner;%d;0"; // 向左滚动，右到左
        posX = width; // 起始位置从右边界
        break;
    case 2: // 从上到下
        effectFormat = "Scroll down;%d;%d;%d"; // 向下滚动
        y1 = -40; // 起始位置从上边界（假设字体高度为40）
        y2 = height; // 终止位置在下边界
        break;
    case 3: // 从下到上
        effectFormat = "Scroll up;%d;%d;%d"; // 向上滚动
        y1 = height; // 起始位置从下边界
        y2 = 0; // 终止位置在上边界
        break;
    default:
        effectFormat = "Banner;%d;0"; // 默认从右到左滚动
        break;
    }

    for (int i = 0; i < ass_track->n_events; ++i) {
        ASS_Event *event = &ass_track->events[i];
        event->Start = i * 30000;
        event->Duration = 30000;
        event->Style = 0;

        char effect_str[100];
        if (rollDirection == 2 || rollDirection == 3) {
            // 如果是上下滚动，使用 Scroll 特效
            snprintf(effect_str, sizeof(effect_str), effectFormat, y1, y2, scrollSpeed);
        } else {
            // 如果是左右滚动，使用 Banner 特效
            snprintf(effect_str, sizeof(effect_str), effectFormat, scrollSpeed);
        }
        event->Effect = strdup(effect_str);

        char pos_str[200];
        snprintf(pos_str, sizeof(pos_str), "{\\pos(%d,%d)}%s", posX/2, 50, "AAA\\nBBB");
        event->Text = strdup(pos_str);
    }
}

ASS_Track* SubtitleRenderer::getTrack() const {
    return ass_track;
}
}

**Comment by astiob** [comment]
How do you blend the ASS_Images onto the output? AAA and BBB are in two separate ASS_Images.

**Comment by tolink-Mengtianfu** [comment]
Ok, thanks for your answer. This inspires me, and I'll check my ASS_Images blend method
@astiob
