### ISSUE TITLE
Is there a way for me to get the size of the image generated by entering all the text?

### ISSUE THREAD

**Issue by tolink-Mengtianfu** [libass/libass#833]
Is there a way for me to get the size of the image generated by entering all the text?

I am making an advertising LED light box application. In this scenario, I need to scroll horizontally from right to left until the end of the text disappears to the left;

But for now, I can only set an event duration, such as 10 seconds. In this case, if my scroll speed is set to be relatively slow, it will appear at 10 seconds, and my text is not fully rolled to show the event is over. Unable to scroll through a complete sentence;

For example: my AD text is 123456789ABCD, scroll from right to left in 10 seconds. When the scrolling speed is slow, at 10 seconds, the title frame may only be displayed at 123456789 at the end of the event; Cause incompleteness

To solve this problem, I figured out how to dynamically scroll a message from right to left by entering the width, height and speed of the rendered text. Total time required.

**Comment by astiob** [comment]
libass doesn’t provide any way to measure text (yet). See #348 and #825 for future prospects.

If you know your font has all the necessary glyphs, you can use `hb-shape` from HarfBuzz to obtain the metrics. (It outputs each glyph separately; just add them together.)
