### ISSUE TITLE
For the same piece of text, the pixel of the ass_render_frame font will be slightly different each time the text is called under scrolling conditions. Resulting in a jitter and flicker sensation when scrolling render

### ISSUE THREAD

**Issue by tolink-Mengtianfu** [libass/libass#834]
First of all, I want to express my gratitude for the incredible work you’ve done on this project. It has been a tremendous help to me. However, I have encountered two small issues that I hope you could assist me with.

**Question 1**
As shown in the image below, this is the same piece of text using Banner;%d;0 for scrolling. When capturing the generated subtitle frames at different times, I found that the glyph pixels vary slightly each time, which causes the subtitles to appear jittery and flicker during actual video blending. Is this normal? I expected that the same piece of text should have consistent pixels at different times.

I am unsure if this issue is caused by my blending method.
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/db54fc9a-94e5-4bd8-bac8-b07ae1a8c5f4">

**Question 2**
The subtitle images generated in the following style have semi-transparent text pixels, resulting in inconsistent colors.  Since I ultimately need the subtitles for driving an LED advertising lightbox, where the pixel resolution is generally low, inconsistent colors will lead to very poor display quality.

Therefore, I hope that each pixel’s color is uniform and has no transparency, without using any shadow or border settings.  There should not be any semi-transparency.

I am unsure whether this is an issue with the library itself or if my pixel blending method is incorrect.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/48e58113-6115-4bd4-bf53-58e10fb1021a">

  ```
    ass_set_pixel_aspect(ass_renderer, 1.0);
    ass_set_frame_size(ass_renderer, 200, 200);
    ass_set_storage_size(ass_renderer, width, height);

    ass_track->PlayResX = 200;
    ass_track->PlayResY = 200;
    ass_track->LayoutResX = 200;
    ass_track->LayoutResY = 200;

 ASS_Style *style = (ASS_Style *)malloc(sizeof(ASS_Style));
        style->Name = strdup("Default");
        style->FontName = strdup(font.family().toUtf8().constData());
        style->FontSize = 20;
        style->PrimaryColour = 0x0000FF00; // bgr
        style->SecondaryColour = 0x0000FF00; // bgr
        style->OutlineColour = 0x00000000; // bgr
        style->Bold = 0;
        style->Italic = 0;
        style->Underline = 0;
        style->StrikeOut = 0;
        style->BorderStyle = 0;
        style->Outline = 0;
        style->Shadow = 0;
        style->ScaleX = 1;
        style->ScaleY = 1;
        style->MarginL = 0;
        style->MarginR = 0;
        style->MarginV = 0;
        style->Blur =0;
        style->BackColour = 0;
```

```
void SubtitleRenderer::renderAssImagesToAVFrame(int timestamp, AVFrame *frame)
{
    int detect_change = 1; // 检测变化的标志
    ASS_Image *images = ass_render_frame(ass_renderer, ass_track, timestamp, &detect_change);
    ASS_Image *img = images;

    while (img) {
        blendSingleFrame(frame, img);
        img = img->next;
    }

    std::string output_filename = "/Users/tolink-mtf-01/ffmpeg/test1/T" + std::to_string(timestamp) + ".png";

    saveFrameAsImage(frame,output_filename.c_str());

}

void SubtitleRenderer::blendSingleFrame(AVFrame *frame, ASS_Image *img)
{

    unsigned char r = img->color >> 24;
    unsigned char g = (img->color >> 16) & 0xFF;
    unsigned char b = (img->color >> 8) & 0xFF;
    unsigned char a = 255 - (img->color & 0xFF);

    unsigned char *src = img->bitmap;


    unsigned char *dst = frame->data[0] + img->dst_y * frame->linesize[0] + img->dst_x * 4;

    for (int y = 0; y < img->h; ++y) {
        for (int x = 0; x < img->w; ++x) {
            unsigned k = ((unsigned)src[x]) * a;
            unsigned rounding_offset = 255 * 255 / 2;

            dst[x * 4 + 0] = (k * r + (255 * 255 - k) * dst[x * 4 + 0] + rounding_offset) / (255 * 255);  // R 通道
            dst[x * 4 + 1] = (k * g + (255 * 255 - k) * dst[x * 4 + 1] + rounding_offset) / (255 * 255);  // G 通道
            dst[x * 4 + 2] = (k * b + (255 * 255 - k) * dst[x * 4 + 2] + rounding_offset) / (255 * 255);  // B 通道
            dst[x * 4 + 3] = (k * 255 + (255 * 255 - k) * dst[x * 4 + 3] + rounding_offset) / (255 * 255); // A 通道
        }
        src += img->stride;
        dst += frame->linesize[0];
    }
}
```

**Comment by rcombs** [comment]
This is simply how antialiased text rendering works: you can imagine the vector glyphs as being rasterized to 1-bit bitmaps at a higher resolution, then downsampled to 8-bit bitmaps at the target resolution. This results in semitransparent edge pixels, and avoids visual "pixelation" artifacts.

Some variation in rendering is expected when characters are rendered at inconsistent subpixel positions, which is almost inevitable when using scroll effects at speeds that aren't an exact integer number of pixels per frame. Antialiasing is meant to reduce the visible impact of this, but it can indeed result in a "shimmer" effect at lower resolutions; software designed for your use-case would generally enable font hinting, which results in glyph vectors being automatically realigned to the bitmap grid before rasterization (though this can result in some additional apparent judder in animations, or apparent inconsistency in glyph spacing).

This project is designed for rendering subtitles, which is generally done at reasonably high resolutions and full-color bit depth, where antialiasing is desirable and hinting isn't. If your application involves low-resolution or low-bit-depth output, you may have better results drawing your text using FreeType's monochrome renderer with hinting enabled, or (at *very* low resolutions) using a bitmap font.

**Comment by tolink-Mengtianfu** [comment]
Thank you for your reply. I think I understand. Does libass have a corresponding api to enable FreeType's monochrome renderer with hinting enabled
@rcombs

**Comment by rcombs** [comment]
No, libass isn't designed for this use-case, and likely wouldn't be practical to adapt for it. I'd recommend you check out a more general-purpose text rendering library, like Cairo.

**Comment by tolink-Mengtianfu** [comment]
ok Thank you 。qt also doesn't seem to have a ready-made api for drawing vector graphics
I think I can only use freetype to generate vector bitmaps and handle the scrolling effect myself to achieve this @rcombs

**Comment by astiob** [comment]
Personally, it sounds to me like you very much want to use bitmap fonts rather than vector ones in any case. libass doesn’t support bitmap fonts at all, but I think FreeType does. Not sure though, as I’ve never used them myself. I’m afraid we (libass developers) can’t really help you further.
