### ISSUE TITLE
Alignment mode

### ISSUE THREAD

**Issue by jxaujunjun** [libass/libass#835]
{\an8}123456\N{\an7}abc

I think the whole is center aligned, and the paragraph is left aligned, but the above setting has no effect. How should I set it, thank you

**Comment by rcombs** [comment]
Alignment applies to an entire event; if you want to render multiple lines with different alignments, use multiple separate events.

**Comment by jxaujunjun** [comment]
> Alignment applies to an entire event; if you want to render multiple lines with different alignments, use multiple separate events.

I would like to ask you, if you use multiple separate events to set the alignment, then the whole paragraph is particularly complicated, but also to set coordinate points, there is no other simple way, it is best to give an example, thank you.

**Comment by rcombs** [comment]
I don't understand what you're asking.

**Comment by astiob** [comment]
If you want to put the whole paragraph in the middle of the screen but align the lines inside the paragraph to the paragraph’s left edge, that’s not (in general) possible in ASS.

If you’re using libass via the API to render text on screen but don’t intend to distribute them as an ASS file, you can achieve this by setting the `Justify` field in the `ASS_Style` to `ASS_JUSTIFY_LEFT`. If you’re watching subtitles in mpv and want to override their alignment during playback, you can similarly use `--sub-ass-style-overrides=Justify=1` (for all styles) or `--sub-ass-style-overrides=StyleName.Justify=1` (for a specific style).

But if you’re authoring proper ASS subtitles for distribution, there’s no way to do this in general. You’ll have to compute the coordinates and use `\pos`.

It may be possible in some special cases, but the code will look ugly. In particular, if you somehow know which of your lines is the longest one, here’s a way to achieve this:

```tex
{\q2\an8}123456{the longest line}\N{\alpha&HFF}abc{\alpha}abc{\alpha&HFF}123456\N{\alpha&HFF}def{\alpha}def{\alpha&HFF}123456
```

for

```
123456
abc
def
```

That is, pad out the shorter lines with invisible text that places them at the desired position after centring, like this:

```
   123456
abcabc123456
defdef123456
```

**Comment by jxaujunjun** [comment]
> If you want to put the whole paragraph in the middle of the screen but align the lines inside the paragraph to the paragraph’s left edge, that’s not (in general) possible in ASS.
> 
> If you’re using libass via the API to render text on screen but don’t intend to distribute them as an ASS file, you can achieve this by setting the `Justify` field in the `ASS_Style` to `ASS_JUSTIFY_LEFT`. If you’re watching subtitles in mpv and want to override their alignment during playback, you can similarly use `--sub-ass-style-overrides=Justify=1` (for all styles) or `--sub-ass-style-overrides=StyleName.Justify=1` (for a specific style).
> 
> But if you’re authoring proper ASS subtitles for distribution, there’s no way to do this in general. You’ll have to compute the coordinates and use `\pos`.
> 
> It may be possible in some special cases, but the code will look ugly. In particular, if you somehow know which of your lines is the longest one, here’s a way to achieve this:
> 
> ```
> {\q2\an8}123456{the longest line}\N{\alpha&HFF}abc{\alpha}abc{\alpha&HFF}123456\N{\alpha&HFF}def{\alpha}def{\alpha&HFF}123456
> ```
> 
> for
> 
> ```
> 123456
> abc
> def
> ```
> 
> That is, pad out the shorter lines with invisible text that places them at the desired position after centring, like this:
> 
> ```
>    123456
> abcabc123456
> defdef123456
> ```

Thank you ,  One problem here is that the first line of text can be minimal, for example:
123
abcdef
0000000000
