### ISSUE TITLE
ASS shadow

### ISSUE THREAD

**Issue by jxaujunjun** [libass/libass#836]
In ASS file, can you set the depth of the shadow is X axis or Y axis: \xshad, \yshad, what parameters can you set the radius of the shadow, thank you

**Comment by jxaujunjun** [comment]
> Refere

Want to set the effect on the picture, thank you
![Uploading 微信图片_20241008203702.png…]()

**Comment by astiob** [comment]
That’s a blurred border: `\bordX\blurY`.

**Comment by TheOneric** [comment]
If you’re new to ASS and unsure what base effects are possible and how, you might want to go through [all override tags](https://aegisub.org/docs/latest/ass_tags/). There are already some example images in the linked doc, but recreating each tag and playing around with its settings and combinations with other tags in [Aegisub](https://github.com/arch1t3cht/Aegisub/releases/latest) could be helpful.
